### PR TITLE
config: Fix Image InsecureRegistries Doc

### PR DESCRIPTION
**Pull request by adambkaplan**
Change "SSL certificate" to "TLS certificates"

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bparees 

fyi @bmcelvee per https://github.com/openshift/openshift-docs/pull/14989#discussion_r287431412

**Comment by adambkaplan** [comment]
@bparees cherrypick this for `release-4.1`? Would the new swagger doc require a bump in origin?

**Comment by bparees** [comment]
> @bparees cherrypick this for release-4.1? 

for something this minor i would not bother

> Would the new swagger doc require a bump in origin?

yes, but again for something this minor i'd just wait, eventually someone will bump origin and it'll get picked up.  It's not worth an explicit bump.

**Pull request merged**
