### PR TITLE
OCPNODE-2436: SigstoreImageVerification featuregate marker for the ClusterImagePolicy and ImagePolicy

### PR DESCRIPTION
**Pull request by QiWang19**
ClusterImagePolicy and ImagePolicy use SigstoreImageVerification instead of ImagePolicy

### CODE REVIEW

**Comment by deads2k** [comment]
Is the ImagePolicy featureGate in use?  if not, please remove it here.

**Review by wking — APPROVED** [review]
/lgtm

**Review by wking — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
/retitle OCPNODE-2436: SigstoreImageVerification featuregate marker for the ClusterImagePolicy and ImagePolicy

**Pull request merged**
