### PR TITLE
Add eligible CAPI-install platforms to TechPreview

### PR DESCRIPTION
**Pull request by patrickdillon**
- aws
- nutanix
- openstack
- powervs
- vsphere

Have all passed e2e tests using the capi installer.

Depends on https://github.com/openshift/installer/pull/8343
Depends on https://issues.redhat.com/browse/CORS-3477

### CODE REVIEW

**Comment by patrickdillon** [comment]
/hold
for https://github.com/openshift/installer/pull/8343

**Comment by patrickdillon** [comment]
> We should see this fail with a message like:

doh, I forgot that we won't see any installer changes until we vendor this

**Comment by patrickdillon** [comment]
/cc @JoelSpeed 
I will create a pr to the installer vendoring the local version of this pr

**Comment by patrickdillon** [comment]
Created https://github.com/openshift/installer/pull/8372 vendoring my local copy, and commented with proof of local testing

**Comment by patrickdillon** [comment]
/hold cancel

Confirmed that the most recent nightly, https://amd64.ocp.releases.ci.openshift.org/releasestream/4.16.0-0.nightly/release/4.16.0-0.nightly-2024-05-08-222442 can now run the capi installer

@JoelSpeed I think this is ready to move forward, or at least for review

**Comment by JoelSpeed** [comment]
/test all
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-techpreview

Is it possible to trigger some cluster bot test workflows using this PR for PowerVS, OpenStack and Nutanix to prove we aren't breaking those by promoting these gates?

**Comment by patrickdillon** [comment]
> Is it possible to trigger some cluster bot test workflows using this PR for PowerVS, OpenStack and Nutanix to prove we aren't breaking those by promoting these gates?

We can't test effectively only with this PR because it is essentially a no op until the changes are vendored to the installer, but I can try with https://github.com/openshift/installer/pull/8372

I triggered e2e presubmits for nutanix and openstack to see if it breaks normal installs. There are apparently no powervs presubmits. 

I can try clusterbot to test if we break techpreview, but on the other hand, there are no existing tests for techpreview, because my pr to add them was merged just yesterday. So we don't really have a baseline to compare it to.

**Comment by patrickdillon** [comment]
Clusterbot can only test openstack in techpreview:

> Patrick Dillon

>   1:07 PM
> launch 4.16,openshift/installer#8372 nutanix,techpreview
> New
> 
> Cluster Bot
> APP  [1:07 PM](https://redhat-internal.slack.com/archives/D045Z7YTWFP/p1715274455805789)
> configuration error, unable to find prow job matching job-architecture=amd64,job-env=nutanix,job-type=launch with parameters=techpreview
> 
> 
> Patrick Dillon
>   [1:07 PM](https://redhat-internal.slack.com/archives/D045Z7YTWFP/p1715274456920629)
> launch 4.16,openshift/installer#8372 powervs,techpreview
> 
> Cluster Bot
> APP  1:07 PM
> unrecognized option: powervs

**Comment by deads2k** [comment]
Glad to see gating be used to good purpose.  Targeted at TechPreview (not default), I'm in favor.

/approve

**Pull request merged**
