### PR TITLE
[CNF-5644] Add MachineAPI capability

### PR DESCRIPTION
**Pull request by qJkee**
Add MachineAPI capability to make autoscaler, machine-api and machine-approver operators optional

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/hold

Give me 24 hours to check on this with the team

**Comment by deads2k** [comment]
I'm ok with this once @JoelSpeed is ok with it and knows how he will manage it.


/assign @JoelSpeed

**Comment by JoelSpeed** [comment]
I've spoken with the team today and we think a single capability for these components is the best approach. The CMA would run into an error loop without the Machine CRD installed in the cluster, so it must be tied to MAO. Likewise the Autoscaler has similar dependencies.

As I understand it, we need to annotate all of our manifests with the capability name, is that correct @qJkee?

Note, without CMA, this means CSR approval for serving certificates becomes manual, what will replace that in a cluster that doesn't have CMA enabled?

**Comment by JoelSpeed** [comment]
What will happen to something like the Console that also depends on the CRDs installed within this capability? Will it suddenly stop working?

**Comment by qJkee** [comment]
@JoelSpeed 
Until we merge annotations with capability names to operator's manifests it would do nothing.
If something depends on that as well, we can use "dependency" as described in the proposal - `cap1 + cap2`

**Comment by JoelSpeed** [comment]
/hold

Until the machine approver is taught to behave without a Machine API present in the cluster, we cannot proceed with merging this capability.

**Pull request closed without merging**
