### PR TITLE
mark clusterversion.status.availableUpdates and conditions as omitempty

### PR DESCRIPTION
**Pull request by joelddiaz**
Mark AvailableUpdates and Conditions as 'omitempty'.

### CODE REVIEW

**Comment by joelddiaz** [comment]
FWIW, in hive we're trying to cache/copy a clusters clusterversion.Status, and we're failing validation when we try to apply the empty availableUpdates (validation failure list:\nstatus.clusterVersionStatus.availableUpdates in body must be of type array: \"null\").

**Comment by csrwng** [comment]
@deads2k I don't see why we should be setting an empty array in a field that we don't use. Do we do that anywhere else in Kubernetes?

**Comment by joelddiaz** [comment]
FWIW, we handle the posibility of nil 'availableUpdates' and 'conditions' now ( https://github.com/openshift/hive/blob/master/pkg/controller/clusterdeployment/clusterdeployment_controller.go#L650-L663 ). I'll update this PR to also mark 'conditions' as omitempty

**Comment by deads2k** [comment]
/close

closing without prejudice due to age.

**Pull request closed without merging**
