### PR TITLE
SPLAT-1441: promote vSphere failure domain template field

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/hold

placing hold for payload testing

**Comment by rvanderp3** [comment]
/payload-with-prs 4.16 nightly informing openshift/installer#7908 openshift/cluster-control-plane-machine-set-operator#275

**Comment by rvanderp3** [comment]
i believe the build01 issues resulted in a broad payload failure but the vSphere jobs seemed to be ok.  I'm going to rerun the test and check in the morning.

**Comment by rvanderp3** [comment]
/payload-with-prs 4.16 nightly informing openshift/installer#7908 openshift/cluster-control-plane-machine-set-operator#275

**Comment by JoelSpeed** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-7908-openshift-cluster-control-plane-machine-set-operator-275-openshift-api-1759-nightly-4.16-e2e-vsphere-static-ovn/1755699220578308096

The `periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn` job is the one I think we need to make green, but its not yet. CPMS is doing a rollout, which I wouldn't have expected for that particular job. In future lets just run the one job `/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn` to save on the others

**Comment by rvanderp3** [comment]
> https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-7908-openshift-cluster-control-plane-machine-set-operator-275-openshift-api-1759-nightly-4.16-e2e-vsphere-static-ovn/1755699220578308096
> 
> The `periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn` job is the one I think we need to make green, but its not yet. CPMS is doing a rollout, which I wouldn't have expected for that particular job. In future lets just run the one job `/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn` to save on the others

Make sense, I'll do that.

**Comment by rvanderp3** [comment]
> https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-7908-openshift-cluster-control-plane-machine-set-operator-275-openshift-api-1759-nightly-4.16-e2e-vsphere-static-ovn/1755699220578308096
> 
> The `periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn` job is the one I think we need to make green, but its not yet. CPMS is doing a rollout, which I wouldn't have expected for that particular job. In future lets just run the one job `/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-static-ovn` to save on the others

Thanks for looking through the results.  @vr4manta believes to have addressed this in https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/276 .  so we'll retest now that that has merged.

tbh, ive been trying to determine how best to use the payload command.  I'll be more selective in the future for sure.

**Comment by rvanderp3** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-techpreview

**Comment by rvanderp3** [comment]
payload jobs look ok, dropping hold

/hold cancel

**Pull request merged**
