### PR TITLE
operator/ingress: Default Azure to LoadBalancer

### PR DESCRIPTION
**Pull request by Miciah**
Use `LoadBalancerService` as the default endpoint publishing strategy type on Azure.

This commit is related to [NE-185](https://jira.coreos.com/browse/NE-185).

* `operator/v1/types_ingress.go` (`IngressControllerSpec`): Document that the default endpoint publishing strategy type on Azure is `LoadBalancerService`.
* `operator/v1/zz_generated.swagger_doc_generated.go`: Regenerate.

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @smarterclayton for approval

**Comment by soltysh** [comment]
/hold
we need to create release-4.1 first

**Pull request merged**
