### PR TITLE
helm/v1beta1: Rename files to use the default run-level for updates

### PR DESCRIPTION
**Pull request by wking**
I'd meant to do these in 9e3e820a70 (#1541), but flubbed my regexp.  Fixed now, with:

```console
$ rename 's/0000_[0-9][0-9][_-]/00_/' helm/*/*.yaml
$ sed -i 's/0000_[0-9][0-9][_-]/00_/' helm/*/*.testsuite.yaml
```

### CODE REVIEW

**Comment by bparees** [comment]
/approve

@jhadvig for the lgtm

**Comment by bparees** [comment]
@jhadvig bump

**Comment by bparees** [comment]
/override ci/prow/verify-crd-schema 

file has not actually changed(other than the rename) so ignore the complaint about the boolean field.

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
