### PR TITLE
features: client generator expects singular objects

### PR DESCRIPTION
**Pull request by rphillips**
I was getting this error on my informer. Note FeatureList does not exist, and Feature**s**List does. We need to redo the pluralization and update the go-client.

```
I0305 14:38:13.242898   22751 reflector.go:169] Listing and watching *v1.Features from github.com/openshift/client-go/config/informers/externalversions/factory.go:101
E0305 14:38:13.244280   22751 reflector.go:134] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: Failed to list *v1.Features: no kind "FeatureList" is registered for version "config.openshift.io/v1" in scheme "github.com/openshift/client-go/c
onfig/clientset/versioned/scheme/register.go:14" 
```

### CODE REVIEW

**Comment by sjenning** [comment]
@rphillips are we sure this is the issue?
@deads2k not sure if this is how we want to fix it if it is.

**Comment by rphillips** [comment]
@sjenning I'm pretty certain the generator works this way. We can force the pluralization constructs with a comment, but we should probably conform to the defaults.

**Comment by deads2k** [comment]
/hold

No, we need a generator fix.  Maybe it didn't publish

**Comment by sjenning** [comment]
i think we should adhere to the upstream convention for resource naming rather than special-case the code generator.  @deads2k what do you think?

**Comment by rphillips** [comment]
Closing in favor of https://github.com/openshift/kubernetes-code-generator/pull/1

**Pull request closed without merging**
