### PR TITLE
[OCPNODE-1671] ImagePolicy uses byte format for base64 fields 

### PR DESCRIPTION
**Pull request by QiWang19**
suggested from https://github.com/openshift/machine-config-operator/pull/4160#discussion_r1480649597.
In the code, we need to use []byte format of base64 data, but []byte will be encoded/decoded when JSON marshal/unmarshal, so set the original field to byte so we do not need to process the data type in the code.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@QiWang19 Can you please provide a PR description to explain why we are making this change, and link to the initial PR that introduced these fields? Do we have a bug report?

**Comment by JoelSpeed** [comment]
[GoPlayground](https://go.dev/play/p/FLnrRd3BDor) shows this is a compatible type change from a json serialisation perspective

**Comment by QiWang19** [comment]
@JoelSpeed update the description https://github.com/openshift/api/pull/1765#issue-2128127165

**Comment by deads2k** [comment]
joel intended for this merge

/approve

**Pull request merged**
