### PR TITLE
NP-874: Promote SDN Live Migration to GA

### PR DESCRIPTION
**Pull request by martinkennelly**
CI history for this feature:

master
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn)
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback)
4.15
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/?job=pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn)
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn-rollback)

/hold

### CODE REVIEW

**Comment by martinkennelly** [comment]
/test e2e-gcp 

Unrelated.

**Comment by martinkennelly** [comment]
Depends on **https://github.com/openshift/cluster-network-operator/pull/2236**

**Comment by martinkennelly** [comment]
This PR is continuation of https://github.com/openshift/api/pull/1714
Contributor of that PR on PTO.
Please see original discussion in that PR.

**Comment by martinkennelly** [comment]
@deads2k We added the constraint in cluster network operator to only allow this feature on standalone managed clusters. PTAL.

**Comment by martinkennelly** [comment]
cc @JoelSpeed

**Comment by JoelSpeed** [comment]
LGTM, will let @deads2k tag once he's verified that the degraded condition changes that have merged were in line with his expectations

**Comment by martinkennelly** [comment]
Thanks. I've linked the PR in the cluster network operator above for your validation @deads2k.

**Comment by deads2k** [comment]
I found the check in https://github.com/openshift/cluster-network-operator/pull/2236

I'm devoting effort to addressing different featuregates per featureset depending on cluster context, but this will prevent mis-use in unsupported environments in 4.16.  The backport (https://github.com/openshift/cluster-network-operator/pull/2243 I believe) must merge prior to the api backport to 4.15.

/approve
/lgtm

**Comment by martinkennelly** [comment]
Please keep us in the loop for this effort.

**Pull request merged**
