### PR TITLE
update documentation on SCCs

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@deads2k ptal

**Comment by deads2k** [comment]
@stevekuznetsov @kargakis  how much trouble is it to have a bot?  Is it easier in a month?

**Comment by deads2k** [comment]
> @deads2k: changing LGTM is restricted to assignees, and assigning you to the PR failed.

Well, I have half a bot

**Comment by kargakis** [comment]
You need to add the bot as a collaborator in the repo.

**Comment by stevekuznetsov** [comment]
Write access is necessary for the bots

**Pull request merged**
