### PR TITLE
Bug 2066388: Add example for s3.regionEndpoint

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
/assign @JoelSpeed 
for approval

**Review by JoelSpeed — COMMENTED** [review]
As I understand it, this field was added a long time ago. Have the validation rules changed (which would be a breaking API change) or is this just an effort to improve the documentation?

**Comment by dmage** [comment]
Maybe one day we'll change the validation rules, but so far this just an effort to improve the documentation.

**Comment by JoelSpeed** [comment]
> Maybe one day we'll change the validation rules, but so far this just an effort to improve the documentation.

I'm just trying to clarify if something has changed in the backend that means this is now required, or was it always the case it must be a valid scheme?

**Comment by dmage** [comment]
It was always the case. Lack of schema most likely will make the operator degraded.

**Pull request merged**
