### PR TITLE
[release 4.8] Bug 2040407 list type

### PR DESCRIPTION
**Pull request by EmilyM1**
Making list atomic to prevent GitOps overwrite for 4.8 backport

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by EmilyM1** [comment]
Hello @sttts Is `// +listType=atomic` is wrong?
This has passed QA/merged/been reviewed on 4 PR's so far. 
What are your thoughts?

**Pull request closed without merging**
