### PR TITLE
NP-874: Promote sdnLiveMigration featureGate to GA

### PR DESCRIPTION
**Pull request by pliurh**
CI history for this feature:
- master
  - [pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn)
  - [pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback)
- 4.15
  - [pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/?job=pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn)
  - [pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn-rollback)

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Do we have any E2E that covers this feature that could be shown to prove the feature is stable before promoting? Would also be good if we could get a QE ack that they're happy with the feature to be promoted?

**Comment by pliurh** [comment]
@JoelSpeed we're working on those. I just want the API team to take a look at the patch first, and see if I missed anything in the PR.

**Comment by JoelSpeed** [comment]
From a code perspective for the promotion, I think we are good. I would just appreciate an up to date PR description with the "proof" that the feature is ready for promotion :)

**Comment by mffiedler** [comment]
/label qe-approved

ACK from QE to remove the feature gate and we can continue testing of SD scenarios.

**Comment by abhat** [comment]
@JoelSpeed can you ptal?

**Comment by JoelSpeed** [comment]
I have higher level concerns about promoting this feature presently, I've raised them in the strat card, https://issues.redhat.com/browse/OCPSTRAT-427.

The strat talks about this being a service delivery only feature, yet, there's no such thing. 

If we merge this PR, every customer will have access to the field, and therefore the ability to enable the live migration, yet the comments in the strat suggest that we haven't fully explored that possibility and that there's more work to do to make that possible.

/hold for now until we can have some more discussion about what's missing for the general OpenShift user

**Comment by deads2k** [comment]
> The strat talks about this being a service delivery only feature

In 4.16, we will make this more practical to do. For this feature on this release, we have an unofficial mechanism available to determine that we're running in an SD managed cluster.  Leverage that mechanism to only honor the setting for SD clusters and we can promote the feature on an SD+QE acceptance.

To learn how, you can get me or @zshi-redhat on slack.

**Comment by weliang1** [comment]
@pliurh Will this PR solve the issue reported in https://issues.redhat.com/browse/OCPBUGS-24692 or the needing to `oc edit featuregate cluster` to edit `spec: featureSet: TechPreviewNoUpgrade`? Or solve both manual actions?

**Comment by pliurh** [comment]
> @pliurh Will this PR solve the issue reported in https://issues.redhat.com/browse/OCPBUGS-24692 or the needing to `oc edit featuregate cluster` to edit `spec: featureSet: TechPreviewNoUpgrade`? Or solve both manual actions?

This PR is only part of the work for solving the issue. We also need to vendor this change in CNO and Cluster Config Operator. After those are all done, live migration can be triggered in SD clusters without modifying the featuregate CR.

**Comment by martinkennelly** [comment]
Depends on https://github.com/openshift/cluster-network-operator/pull/2225

**Comment by martinkennelly** [comment]
Progressing this in PR: https://github.com/openshift/api/pull/1747
@pliurh  is on PTO

/close

**Pull request closed without merging**
