### PR TITLE
[release-4.14] CFE-1047:  Added new field for capacityReservationGroupID in AzureMachineProviderSpec

### PR DESCRIPTION
**Pull request by anirudhAgniRedhat**
Manual back-port for https://github.com/openshift/api/pull/1866

### CODE REVIEW

**Comment by anirudhAgniRedhat** [comment]
Hey @JoelSpeed Can I get the approval for these as Scott has give approval for further Back-port
https://redhat-internal.slack.com/archives/CBZHF4DHC/p1721939852676219?thread_ts=1712582367.529309&cid=CBZHF4DHC

**Comment by anirudhAgniRedhat** [comment]
@JoelSpeed As 4.15 back-port is completed can we start back-port for 4.14?

**Comment by JoelSpeed** [comment]
@anirudhAgniRedhat Yes I think so, are the other PRs ready to go? Do you think if we merge this now we will be able to get all PRs into a single weekly z?

**Comment by anirudhAgniRedhat** [comment]
Yeah!! @JoelSpeed All remaning PRs are up except the CPMS bump one, I am planning to raise it as soon as API merges.
Anyways We cannot merge this until @sdodson is back from PTO which is monday, I need 'valid-bug` tagfrom him.

**Comment by JoelSpeed** [comment]
/lgtm
/label backport-risk-assessed

Ack, you can have my tags, pending scott to add the final one for merge

**Comment by anirudhAgniRedhat** [comment]
@xingxingxia, @gangwgr , @wangke19 Can anyone of you would help me with the required tag?

**Pull request merged**
