### PR TITLE
CORS-3582: remove unused installer feature gates

### PR DESCRIPTION
**Pull request by r4f4**
The CAPI features gates are not needed anymore for platforms where CAPI provisioning is the default.

Also CAPI/aws replaced the AWS SDK provisioner, so the AlternateInfrastructureAWS feature gate is not needed anymore.

### CODE REVIEW

**Comment by r4f4** [comment]
This is being done in conjunction with https://github.com/openshift/installer/pull/8703

/cc @patrickdillon

**Comment by JoelSpeed** [comment]
/hold

I'll check with @sdodson and @deads2k when they are back, but, I believe at the moment we cannot remove gates, only promote or remove from feature sets. I think there are some tooling limitations.

We may have to defer this until 4.18

**Comment by r4f4** [comment]
If we defer to 4.18, we might be able to remove all capi gates.

This is not a blocker in any way, since the installer can just ignore the gates for platforms using capi by default. It's more of a tech debt.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts and added Azure, GCP, and PowerVS to the list of removed gates.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by r4f4** [comment]
/label acknowledge-critical-fixes-only
The requirement for the label has already been dropped.

**Comment by r4f4** [comment]
@JoelSpeed are we good to remove the hold now?

**Pull request merged**
