### PR TITLE
[release-4.13] OCPBUGS-10036: promote aesgcm for apistorage to default

### PR DESCRIPTION
**Pull request by dgrisonnet**

### CODE REVIEW

**Comment by deads2k** [comment]
agreed last week in staff eng, testing shows ok, backports completed.

/lgtm
/approve
/hold

holding for the master vendoring, can be removed once the masters merge and show ok.

**Comment by dgrisonnet** [comment]
Unholding now that all the PRs have been merged in 4.14:
- https://github.com/openshift/cluster-config-operator/pull/289
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/1462
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/526
- https://github.com/openshift/cluster-authentication-operator/pull/601

/unhold

**Comment by dgrisonnet** [comment]
@JoelSpeed it seems like https://github.com/openshift/client-go/pull/239 broke `verify-client-go`, could you advise on the path forward?

**Comment by dgrisonnet** [comment]
@deads2k I investigated the failure a bit and shouldn't the verify-client-go job check the relevant branch instead of comparing o/api@release-4.13 with o/client-go@master? https://github.com/openshift/release/blob/ac7d9f5f3f9de912c2b27a20299f610238508af5/ci-operator/config/openshift/api/openshift-api-release-4.13.yaml#LL52

**Comment by JoelSpeed** [comment]
@dgrisonnet Yes I think you might be right, seems there is an issue in the configuration of the job, I would expect this verify-client-go job to fail because of a merge to master, given this is going into 4.13

**Pull request merged**
