### PR TITLE
Add a minimal integration tests for each CRD in openshift/API

### PR DESCRIPTION
**Pull request by JoelSpeed**
Now that we have the ability to define integration tests for our CRDs that will run pre-merge for API changes, we can add a very basic integration test for each of the CRDs in this package.

The minimal test consists of:
- Installing the CRD to check the CRD file is valid (eg storage and served versions are correct - this has come up recently)
- Creating a single instance of the CR with the minimal spec (ie only the required fields)

The aim of adding these is:
- We should be able to catch breaking changes to the API (if anyone adds a new required field to an API by mistake the tests will catch it)
- We should be able to catch broken CRD files (such as in https://github.com/openshift/api/pull/1256#issuecomment-1255145575 where an accidental change broke the CRD)
- Boilerplate is set up for adding more tests so it should be easier to ask people to add new tests for new API changes

First commit contains a script that I'm using to generate these, then if there are any required fields they need to be added manually.

Usage `./tests/hack/gen-minimal-test.sh <path to API package> <API version>`, eg `./tests/hack/gen-minimal-test.sh ./config/v1 v1`

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/test verify

Can't reproduce the failure locally, was it a flake? 🤔

**Comment by deads2k** [comment]
let's get this started

/lgtm

**Comment by JoelSpeed** [comment]
Had to rebase because of some conflicts in a recent merge (someone changed a CRD file name), but this is working now, will introduce a script to check each CRD has an appropriate test suite later this week, I have a script WIP for this already

**Pull request merged**
