### PR TITLE
Do not register external types

### LINKED ISSUE #270: ImageStream API should not re-register SecretList
Occording to @DirectXMan12, in comment https://github.com/kubernetes-sigs/controller-runtime/issues/362#issuecomment-477767432, OpenShift should not re-register `corev1.SecretList` under its own Group/Version.

This breaks the controller-runtime and causes: https://github.com/kubernetes-sigs/controller-runtime/issues/362

https://github.com/openshift/api/blob/b772cc93d057f30f40f93347a043c3bcef11d268/image/v1/register.go#L48

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #270 
/assign @deads2k 
This is refreshed version of #272

### CODE REVIEW

**Comment by deads2k** [comment]
This is likely to break the image secrets API that makes use of this.

**Comment by soltysh** [comment]
> This is likely to break the image secrets API that makes use of this.

@deads2k are you talking about image change, I can't think how other would?

**Comment by smarterclayton** [comment]
The image secrets sub resource returns secrets list.  This should be easy to test in a PR.

**Comment by soltysh** [comment]
Let's see how https://github.com/openshift/openshift-apiserver/pull/66 turns out.

**Pull request closed without merging**
