### PR TITLE
Enable ValidatingAdmissionPolicy for tech preview.

### PR DESCRIPTION
**Pull request by benluddy**

### CODE REVIEW

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by benluddy** [comment]
Proof https://github.com/openshift/cluster-config-operator/pull/343 is green, including the tech preview E2E job. I'm in the process of doing a smoke test now to confirm that this feature is in fact usable on a tech preview cluster (the point of the whole exercise).

**Pull request merged**
