### PR TITLE
Remove AdmissionWebhookMatchConditions feature gate

### PR DESCRIPTION
**Pull request by dinhxuanvu**
AdmissionWebhookMatchConditions is enabled by default starting k8s 1.28 as beta.

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@bertinatto PTAL. Thanks

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Typically we ask for green CI on a cluster-config-operator PR bumping the API dependency to approve removal/promotion of a feature gate, is there a PR to config operator?

**Comment by dinhxuanvu** [comment]
Looking for an approval. PTAL @soltysh. Thanks!

**Comment by dinhxuanvu** [comment]
> Typically we ask for green CI on a cluster-config-operator PR bumping the API dependency to approve removal/promotion of a feature gate, is there a PR to config operator?

I’m opening one and will link it over here. Thanks!

**Comment by dinhxuanvu** [comment]
Proof PR on config-operator: https://github.com/openshift/cluster-config-operator/pull/359

**Comment by dinhxuanvu** [comment]
@JoelSpeed The CI is all green on the proof PR on cluster-config-operator.

**Pull request merged**
