### PR TITLE
STOR-1077: promote CSIInlineVolumeAdmission feature gate to GA

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1077
/hold for some e2e test results after https://github.com/openshift/origin/pull/27682
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
The [e2e tests](https://github.com/openshift/origin/pull/27682) merged and the [sippy results](https://sippy.dptools.openshift.org/sippy-ng/tests/4.13/details?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Afalse%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522serial%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522techpreview%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522CSIInlineVolumeAdmission%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage) look good so far. I'll be on the lookout for test failures.
The `CSIInlineVolumeAdmission` feature gate was already dropped with the k8s 1.26 rebase, so I would be comfortable merging this since there's nothing that depends on this feature gate now.
/unhold
/assign @jsafrane @deads2k

**Comment by dobsonj** [comment]
/assign @deads2k 
for `/approve`. e2e [test results](https://sippy.dptools.openshift.org/sippy-ng/tests/4.13/details?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Afalse%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522serial%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522techpreview%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522CSIInlineVolumeAdmission%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage) are showing 100% pass rate so far.

**Comment by deads2k** [comment]
> /assign @deads2k for `/approve`. e2e [test results](https://sippy.dptools.openshift.org/sippy-ng/tests/4.13/details?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Afalse%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522serial%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522techpreview%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522CSIInlineVolumeAdmission%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage) are showing 100% pass rate so far.

past 100 runs, 100% pass rate

**Pull request merged**
