### PR TITLE
add management type field that specifies the management system for ibmcloud clusters

### PR DESCRIPTION
**Pull request by relyt0925**
This adds a field that can be used to determine what system is being utilized to deploy IBM Cloud clusters. Possible systems include the openshift-installer repo or the Red Hat Openshift on IBMCloud managed service

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal
This will help to distinguish clusters on IBM Cloud that are either self-managed or managed by ROKS.

**Comment by bparees** [comment]
it looks ok to me but i defer to @deads2k and @sttts as our official api-reviewers

**Comment by deads2k** [comment]
@sttts you're more likely to get bit.  I'm not clear on how this intersects with an external topology mode or what operators are supposed to do with roks versus installer.

**Comment by deads2k** [comment]
> @bparees ptal
> This will help to distinguish clusters on IBM Cloud that are either self-managed or managed by ROKS.

Yeah, but why do we need to know this?  What changes the way it reacts?  Does that team know they need to make changes?

**Comment by relyt0925** [comment]
1)
It doesn't matter currently but it will be able to be a signal for various components to do the proper behavior. There are some hypothetical changes that might need to be in a "non cloud managed" environment (not roks). That is why it's optional. One major thing is traditional OC4 runs with in cluster master nodes on IBM Cloud versus roks uses a hypershift deployment model which will result in different configs and potentially operators needing to do different behavior.


2) Operators would look at this resource to determine the proper behavior if there are any changes necessary

3) No team needs to make changes currently (which is why it's optional) it just enables the possibility. 

4) The component that creates the Infrastructure resource handles it in updated clusters. Hypershift will be the first component using this so it will be one of the operators in it's component.

5) Not guaranteed to have a value currently. Just provides the option for future potential use cases.

**Comment by bparees** [comment]
>  There are some hypothetical changes that might need to be in a "non cloud managed" environment (not roks). That is why it's optional. One major thing is traditional OC4 runs with in cluster master nodes on IBM Cloud versus roks uses a hypershift deployment model which will result in different configs and potentially operators needing to do different behavior.

is that really a unique distinction to the ibm cloud provider though?  

"external control plane" is a higher level concept that's not tied to any particular cloud provider.

so does this really belong under the ibm cloud provider config?

**Comment by csrwng** [comment]
@bparees @deads2k Currently in IBM Cloud an external control plane implies a cluster created by IBM's managed service (ROKS). However, in the not so distant future, you will be able to create a cluster with an external control plane that is not managed by IBM using hypershift. What this means for an operator like Ingress is that it will need to decide whether it needs to create wildcard dns entries itself.  The operator needs to distinguish within the use case that a cluster is running on IBMCloud platform AND has an external control plane, whether it is 1) managed by ROKS or 2) created by the user via hypershift. In the first case, it should not create wildcard dns records, in the second case it should. See https://github.com/openshift/cluster-ingress-operator/pull/659

**Comment by bparees** [comment]
>  The operator needs to distinguish within the use case that a cluster is running on IBMCloud platform AND has an external control plane, whether it is 1) managed by ROKS or 2) created by the user via hypershift.


```
// IBMCloudManagementTypeInstaller signifies the IBMCloud clusters deployment is being orchestrated through
// the openshift installer
```

should this say orchestrated via hypershift then, not orchestrated through the openshift installer?  and/or should the name be "IBMCloudManagementTypeHypershift" or something else that is more specific to a user-controlled hypershift managed installation mechanism?

And is there ever going to be an IBM cloud option that has a self-hosted control plane?

**Comment by bparees** [comment]
> @bparees Yes there is an IBM Cloud that is self hosted. That is work going in 4.10 - UPI/IPI support for IBM cloud

so what would this value would this field take for that cluster?

it seems like there are really 3 possible values:

1) managementype=selfhosted
2) managementtype=hypershift
3) managementype=roks(?)

**Comment by csrwng** [comment]
The management type would only apply to external control plane clusters. But in any case, @sttts suggested that we add a config knob to the cluster ingress operator instead of having it distinguish between different platform details.

**Pull request closed without merging**
