### PR TITLE
add imageconfig

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton i've discussed this with @deads2k so i think i understand some of the intent behind the original PR, but i'd still like to discuss this face to face because the world you guys seem to have in mind doesn't align with how i envision admin's driving this configuration, and seems to introduce additional levels of complexity/confusion for the admin.

**Comment by stevekuznetsov** [comment]
Does this repo have Travis disabled? `tide` is having an issue merging this as the context is required but missing

**Comment by deads2k** [comment]
@sanchezl @juanvallejo incoming.  First one to volunteer gets to wire it. :)

@bparees you got a client-go pull to go with this?

**Comment by bparees** [comment]
@deads2k it's over here, but it's currently using my fork for glide: https://github.com/openshift/client-go/pull/63

**Comment by bparees** [comment]
@stevekuznetsov are you looking into the travis blockage here, or is that something @openshift/sig-master owns?

**Comment by bparees** [comment]
wow. that actually worked.

**Pull request merged**
