### PR TITLE
Bug 2081457: kubebuilder validation format hostname is not RFC compliant

### PR DESCRIPTION
**Pull request by candita**
Cherry-pick #1120 to [release-4.8]

### CODE REVIEW

**Comment by candita** [comment]
@deads2k @soltysh could you please approve this final cherrypick of https://github.com/openshift/api/pull/1120 ?

**Comment by candita** [comment]
@soltysh @sttts @s-urbaniak @tkashem can one of you please add the backport-risk-assessed label and approval?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
