### PR TITLE
Bug 1785289: add deprecaction notice for build pipeline strategy

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/openshift-team-developer-experience @akram @siamaksade FYI

/assign @bparees 
(@adambkaplan is not in the OWNERS files that I see)

### CODE REVIEW

**Comment by gabemontero** [comment]
> /lgtm

thanks @bparees but fyi going to need this again ... trying to get the various update/verify scripts  passing locally so I can get this repo's verify job to pass

**Comment by bparees** [comment]
@gabemontero np, ping me when you're set.

**Comment by gabemontero** [comment]
> @gabemontero np, ping me when you're set.

ok we are good now @bparees

**Pull request merged**
