### PR TITLE
OCPBUGS-36523: Rename Dockerfile

### PR DESCRIPTION
**Pull request by ashwindasr**
Refactor name to `Dockerfile.ocp` as a better, version independent, alternative since contents are actually rhel9. 

CI: https://github.com/openshift/release/pull/53997 (probably needs to merge first)

Please follow up with other changes in this/other repos if necessary. ART has setup the necessary [fallbacks](https://github.com/openshift-eng/ocp-build-data/pull/5039), but only for 4.17, if backporting this PR, please give us a heads up.

### CODE REVIEW

**Comment by ashwindasr** [comment]
The release [PR](https://github.com/openshift/release/pull/53997) probably needs to merge first for tests to pass

**Comment by JoelSpeed** [comment]
/lgtm
/hold

@ashwindasr to unhold at the right time

**Pull request merged**
