### PR TITLE
features: add capi-installer gate per platform

### PR DESCRIPTION
**Pull request by patrickdillon**
Adds a capi-installer feature gate for each platform.

/cc @JoelSpeed @deads2k 

FYI:
@r4f4 
@jhixson74 
@bfournie 
@cjschaef 
@yanhua121 
@stephenfin 
@mjturek
@rvanderp3

### CODE REVIEW

**Comment by r4f4** [comment]
So we'll need 2 feature gates to use a capi provider? `ClusterAPIInstall` and then ` ClusterAPIInstallAWS` for AWS, e.g.

**Comment by JoelSpeed** [comment]
> So we'll need 2 feature gates to use a capi provider? ClusterAPIInstall and then  ClusterAPIInstallAWS for AWS, e.g.

I would expect it to be an or semantic. We want to start adding each of these to the TPNU set as they mature, but the original gate will stay for custom setups only.

@patrickdillon Do you have a PR for the installer that pairs with this?

**Comment by JoelSpeed** [comment]
/lgtm

Scanned over the installer PR and seems like what I was expecting

**Pull request merged**
