### PR TITLE
ImageImportControllerConfig: support the number of workers

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/IR-462

/cc @flavianmissi @dmage

### CODE REVIEW

**Comment by flavianmissi** [comment]
Looking good. We need a matching PR on the openshift controller manager side that makes use of this new field too before we can merge this one right? I think the api change and the functionality need to go in together (as much as possible).

**Comment by hongkailiu** [comment]
> Looking good. We need a matching PR on the openshift controller manager side that makes use of this new field too before we can merge this one right? I think the api change and the functionality need to go in together (as much as possible).

Thanks for the review. I got a question as a first time PR author to api repo. :) 
How can we compile openshift-controller-manager without upgrading its [dependency](https://github.com/openshift/openshift-controller-manager/blob/3369227f301f7bc98e3f364c9bfb6fff788302d6/go.mod#L14) of api including this new field?

**Comment by hongkailiu** [comment]
> > How can we compile openshift-controller-manager without upgrading its [dependency](https://github.com/openshift/openshift-controller-manager/blob/3369227f301f7bc98e3f364c9bfb6fff788302d6/go.mod#L14) of api including this new field?
> 
> You can't. What you can do is temporarily upgrade/replace it to your fork's branch with the changes in this PR. Something like (untested):
> 
> ```
> replace github.com/openshift/api => github.com/hongkailiu/api IR-462
> ```
> 
> Then run `go mod tidy && go mod vendor`. Once you know everything is working on both ends and the changes in this PR merge you can remove the replace and do a proper bump of openshift/api.

Thanks for the pointer. I will try it out.

**Comment by hongkailiu** [comment]
/close


As hinted in slack discussion, this might not achieve what I wanted: more workers to do the imports which are handled by the api-server eventually. The workers here might be something else.

**Pull request closed without merging**
