### PR TITLE
Promote AWSEFSDriverVolumeMetrics to GA

### PR DESCRIPTION
**Pull request by bertinatto**
With QE's approval, the Storage Team would like to promote this feature to GA in 4.18 and 4.17.

This feature is behind a feature gate because it introduces new fields in the `ClusterCSIDriver` object. However, it's only used by AWS EFS CSI Driver operator, which is an optional operator installed via OLM.

CC @gcharot @openshift/storage

### CODE REVIEW

**Comment by chao007** [comment]
QE tested steps and resutls as below:
1.oc patch featuregate cluster -p '{"spec": {"featureSet": "TechPreviewNoUpgrade"}}' --type merge
```
    enabled:
    - name: AWSEFSDriverVolumeMetrics
```
2.Create clustercsidriver
oc get clustercsidriver/efs.csi.aws.com -o json | jq .spec.driverConfig
```
{
  "aws": {
    "efsVolumeMetrics": {
      "state": "RecursiveWalk"
    }
  },
  "driverType": "AWS"
}
```
3.Create storageclass/pvc/pod
```
oc get pvc -n test3
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
pvc1   Bound    pvc-fcc4f858-21ec-4af3-84a6-54433d7fbc8b   1Gi        RWO            efs-sc         <unset>                 150m
```
4.Check metrics reported.
```
      {
        "metric": {
          "__name__": "kubelet_volume_stats_capacity_bytes",
          "endpoint": "https-metrics",
          "instance": "10.0.83.148:10250",
          "job": "kubelet",
          "metrics_path": "/metrics",
          "namespace": "test3",
          "node": "ip-10-0-83-148.us-east-2.compute.internal",
          "persistentvolumeclaim": "pvc1",
          "service": "kubelet"
        },
        "value": [
          1724060972.753,
          "0"
        ] 
```
5. Update the clustercsidriver
```
{
  "aws": {
    "efsVolumeMetrics": {
      "state": "Disabled"
    }
  },
  "driverType": "AWS"
}
```
6.Created pvc/pod
7.Check metrics reported, no values from efs csi driver.

**Comment by JoelSpeed** [comment]
/lgtm
/retest
/override ci/prow/verify

No E2E in origin but QE testing shows this is ready

**Comment by bertinatto** [comment]
> /lgtm /retest /override ci/prow/verify
> 
> No E2E in origin but QE testing shows this is ready

/override ci/prow/verify

**Pull request merged**
