### PR TITLE
NE-799: config/ingress: "loadbalancer" → "loadBalancer"

### PR DESCRIPTION
**Pull request by Miciah**
Change the json tag for the recently added `LoadBalancer` field from "loadbalancer" to "loadBalancer" for consistency with other APIs.

Follow-up to #1209.

* `config/v1/types_ingress.go` (`IngressSpec`): Change "loadbalancer" to "loadBalancer".
* `config/v1/0000_10_config-operator_01_ingress.crd.yaml`: 
* `config/v1/zz_generated.swagger_doc_generated.go`: 
* `openapi/generated_openapi/zz_generated.openapi.go`:
* `openapi/openapi.json`: Regenerate.

### CODE REVIEW

**Comment by miheer** [comment]
Hi @Miciah! I tested this with the installer but the units test fail.

git clone installer code
cd installer
git rebase origin/master

GO111MODULE=on GOFLAGS=-mod=vendor go mod edit -replace=github.com/openshift/api=github.com/openshift/api@24ee13c10f3bf7c3320392ba687a5a42bb3c04c4

**Comment by deads2k** [comment]
/approve
/hold

holding so @Miciah can chase usage and be sure the change will work.

**Pull request merged**
