### PR TITLE
16450 add mce

### PR DESCRIPTION
**Pull request by cameronmwall**
/hold

### CODE REVIEW

**Comment by deads2k** [comment]
Can I get a link to the enhancement in the description here please?

**Comment by cameronmwall** [comment]
Here is our repo for our component: https://github.com/stolostron/backplane-operator
And here is our documentation for the tech preview version of MCE: https://stolostron.github.io/mce-docs/
Is this what you're looking for?

**Comment by deads2k** [comment]
At a high level, it seems unusual to include an API for what appears to be managing multiple openshift clusters (maybe?) inside of the openshift/api which is lifecycled at an OCP cadence.


Is there an enhancement describing this?  The API is shaped as though it's a move from somewhere, but I'm not sure where that someone is.

**Pull request closed without merging**
