### PR TITLE
update cipher profiles to respect Go/Kube options

### PR DESCRIPTION
**Pull request by stlaz**
This PR removes some of the cipher suites that come from Mozilla recommendation that are not implemented by the Go package.

It also removes the possibility to configure maximum TLS version that is not possible to be done using the Kubernetes [SecureServingOptions](https://github.com/kubernetes/apiserver/blob/master/pkg/server/options/serving.go#L37) which are used in most (if not all) our operands.

Another change this PR brings is removal of the `DHParamSize`. Golang's crypto only implements the elliptic curve form of Diffie-Hellman algorithms and does not allow this parameter to be set.

There's also a minor change of tls version string constants where these are changed to what we can simply pass to the above mentioned `SecureServingOptions` but this may not be necessary as we can map it directly.

-------

cc @danehans @ironcladlou @deads2k

### CODE REVIEW

**Comment by danehans** [comment]
> Could you elaborate on why we would want that parameter to be configurable (my assumption and hope is that TLS 1.3 will not have protocol-level vulnerability -.-)?
1) The original PR was based on 4.2 of Mozilla's server-side tls [recommendations](https://wiki.mozilla.org/Security/Server_Side_TLS), where TLS 1.3 was not included in all the recommended configurations. 2) The OpenSSL version used by the current version of haproxy does not support TLS 1.3:
```
HA-Proxy version 1.8.17 2019/01/08
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
<SNIP>
```

> I was also looking into `DHParamSize`. Golang does not actually support any of the "bare" Diffie-Hellman ciphers, only EC versions, and as such it does not offer a way to configure this parameter. Is it just something you need for your own use? I don't think it should appear in the API in APIServer object if we're not able to respect it.

We need the ability to control `DHParamSize` to support the [Old Profile](https://wiki.mozilla.org/Security/Server_Side_TLS#Old_backward_compatibility) as implemented by the haproxy [config template](https://github.com/openshift/router/blob/master/images/router/haproxy/conf/haproxy-config.template#L64-L92).

> With regards to the above, we should probably throw away all the ciphers suites that are not available to our Go operands? That would mean all DHE-* + some others that don't directly map to a certain golang suite name.

The intention of the original api was to support managing ingress controller (haproxy) security profiles based on Mozilla's server-side tls [recommendations](https://wiki.mozilla.org/Security/Server_Side_TLS). By removing DHE ciphers, we are diverging from upstream. @knobunc what are your thoughts on diverging?

**Comment by danehans** [comment]
@ironcladlou @Miciah ptal

**Comment by Miciah** [comment]
As Daneyon said, the security API was designed with HAProxy in mind.  Later it was recharacterized as a more general API and adopted by the API server.  Go's limitations should not dictate the shape of the API since not all consumers are Go-based.

**Comment by stlaz** [comment]
>   2) The OpenSSL version used by the current version of haproxy does not support TLS 1.3:

That does not mean we have to have `tlsMaxVersion`, we can just say that maximum TLS version supported by the component will be used.

Also, won't the "Modern" TLS Profile break the proxy, then?
 
> We need the ability to control `DHParamSize` to support the [Old Profile](https://wiki.mozilla.org/Security/Server_Side_TLS#Old_backward_compatibility) as implemented by the haproxy [config template](https://github.com/openshift/router/blob/master/images/router/haproxy/conf/haproxy-config.template#L64-L92).

We don't if we remove the no-EC DH ciphers which we should hopefully be able to do.
 
> > With regards to the above, we should probably throw away all the ciphers suites that are not available to our Go operands? That would mean all DHE-* + some others that don't directly map to a certain golang suite name.
> 
> The intention of the original api was to support managing ingress controller (haproxy) security profiles based on Mozilla's server-side tls [recommendations](https://wiki.mozilla.org/Security/Server_Side_TLS). By removing DHE ciphers, we are diverging from upstream. @knobunc what are your thoughts on diverging?

We would be diverging from a recomendation by reducing the number of cipher suites, that does not sound all that terrible, but I'll gladly hear @knobunc thoughts.

> As Daneyon said, the security API was designed with HAProxy in mind. Later it was recharacterized as a more general API and adopted by the API server. Go's limitations should not dictate the shape of the API since not all consumers are Go-based.

AFAIK most consumers will be Go-based. It was chosen to have a common API, which means both sides should be respected. If I say that HAProxy limitations (like no TLS1.3 support, mentioned above) should not limit the shape of the API, I would also be correct. It's about finding the sweet spot for both IMO.

**Comment by Miciah** [comment]
> AFAIK most consumers will be Go-based. It was chosen to have a common API, which means both sides should be respected. If I say that HAProxy limitations (like no TLS1.3 support, mentioned above) should not limit the shape of the API, I would also be correct. It's about finding the sweet spot for both IMO.

We have already decided that a component must ignore unknown ciphers, and I believe the same should be true for other parameters.  That is, the TLS profile should be the intersection of what the user requests and what the component supports.  The greater risk is in allowing something that should be prohibited, not vice versa.

**Comment by danehans** [comment]
> Also, won't the "Modern" TLS Profile break the proxy, then?

The profile will either not be available for ingress or the ingress operator will not consume the tls security api until haproxy is updated to a version that supports TLS 1.3.

**Comment by knobunc** [comment]
I think this revision is reasonable.  I can't honestly think of a case where you want to restrict the max version (unless, I guess, if a new revision has some horrible problem that comes to light after it has come out, but that seems like a small risk).

As to reducing the ciphers, it doesn't really hurt to remove them now, and we can add them back later.  But I agree with @Miciah's concern, is this supposed to be a lowest common denominator API, or is it supposed to cover the desired set of config, and if something can not handle a cipher, or a tls setting, it should be ignored in that implementation.  If that results in no available ciphers, then the component should put that in its status.

Anyway, for now, we can handle a reduced cipher set, and then when we decide these issues, we can add more in (if desired).  It's harder to go the other way...

/lgtm

**Pull request merged**
