### PR TITLE
Move CAPI install platforms to default feature set

### PR DESCRIPTION
**Pull request by patrickdillon**
Moves AWS, Nutanix, OpenStack & vSphere capi installs to default feature set.

### CODE REVIEW

**Comment by patrickdillon** [comment]
/test verify

Reading the logs I can't tell what the error is! Not sure if this is a flake/fluke

**Comment by JoelSpeed** [comment]
Based on the linked sippy dashboards above, it appears that the installation success rate of these platforms is good, and that the features being promoted to default here are not negatively affecting installs.

/override ci/prow/verify
/lgtm

/hold In slack there is conversation about some nightly blocking payload commands on an installer PR as a pre-requisite to this, have we got that?

**Comment by stbenjam** [comment]
https://github.com/openshift/api/pull/1895 has an example of how we might test platform and install-specific feature gates, but I'll leave that for Monday for @deads2k to look at.

But TRT is sufficiently satisfied these gates were tested properly.

/lgtm

**Comment by JoelSpeed** [comment]
/hold cancel
/label acknowledge-critical-fixes-only

Welcome to the product Cluster API 🫡

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-ovn-hypershift

These gates do not affect HyperShift, they are limited to the openshift-install and the standalone topology

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-ovn-hypershift

These gates do not affect HyperShift, they are limited to the openshift-install and the standalone topology

**Pull request merged**
