### PR TITLE
Revert config/v1/Node CRD yaml

### PR DESCRIPTION
**Pull request by swghosh**
Revert node-crd.yaml from config/v1 as it is causing e2e-upgrade tests on our CI to fail.

Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Comment by swghosh** [comment]
/hold
Using this PR commits to re-vendor [o/cluster-config-operator](https://github.com/openshift/cluster-config-operator/) in order to test if the CI could signal green for failing e2e-upgrade tests.

**Comment by deads2k** [comment]
This removal is fine to fix the situation we have in 4.11. We never shipped this CRD in 4.10, so this change is acceptable.  The order will look l ike

1. merge this delete
2. vendor the delete into cluster-config-operator
3. get a nightly and ci payload without the CRD
4. merge the re-add of this CRD yaml
5. vendor the re-add into cluster-config-operator

That path should avoid breaking payloads.

**Pull request merged**
