### PR TITLE
Bug 1843043: Improve the config api resource description

### PR DESCRIPTION
**Pull request by drichtarik**

### CODE REVIEW

**Comment by drichtarik** [comment]
@mfojtik @smarterclayton

**Comment by bparees** [comment]
@drichtarik can you be a bit more constructive/positive in your PR title+commit text?  Some person wrote that original description and yeah, it's not the best, but no need to antagonize.

e.g. "Improve the config api resource description"

**Comment by drichtarik** [comment]
@bparees I was only copying the bug name because I thought it's the way i should name the PR. I did not file the bug, nor gave it it's name.

**Comment by bparees** [comment]
> @bparees I was only copying the bug name because I thought it's the way i should name the PR. I did not file the bug, nor gave it it's name.

Fair enough, but for future reference while including the bug # in the PR title/commit is important, you don't have to carry the exact bug title/description, especially if it can be improved upon

(and i'm not trying to make a big deal out about it, i just want to help us maintain a welcoming/safe culture)

**Comment by smarterclayton** [comment]
We need to take accountability when we don't communicate clearly.  Terrible is accurate since explain and api explorer and docs are all generated from this.  We do terrible things to our users when we don't clearly explain - so let's explain better!

**Comment by drichtarik** [comment]
Looks like prow did not catch the /lgtm label as tide is still pending

**Comment by bparees** [comment]
(it'll probably figure it out eventually)

**Comment by drichtarik** [comment]
Probably won't detect it without a restart

**Comment by bparees** [comment]
/retitle Bug 1843043: Improve the config api resource description

**Pull request merged**
