### PR TITLE
OCPVE-645: add CloudCredential capability

### PR DESCRIPTION
**Pull request by qJkee**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
CC @jstuever @dlom can either of you think of issues that might occur with disabling this operator. Is it _strictly_ required for any of the other capabilities to operate? I would have initially proposed that this should only be disabled if all other cloud functionality is disabled but I expect we can be a bit more relaxed here since users could supply their own credentials right?

**Comment by jstuever** [comment]
> CC @jstuever @dlom can either of you think of issues that might occur with disabling this operator. Is it _strictly_ required for any of the other capabilities to operate? I would have initially proposed that this should only be disabled if all other cloud functionality is disabled but I expect we can be a bit more relaxed here since users could supply their own credentials right?

Correct. The various components can operate just fine if the required credential secrets are being manually managed by the user. This is logically the equivalent to CCO being enabled in cluster and in manual mode.... at which point it does practically nothing (STS aside).

**Pull request merged**
