### PR TITLE
types_network: Change API that enables IPsec

### PR DESCRIPTION
**Pull request by markdgray**
Remove requirement to set "enable" flag.

Signed-off-by: Mark Gray <mark.d.gray@redhat.com>

### CODE REVIEW

**Comment by markdgray** [comment]
@abhat @danwinship @sttts Updated as per further discussions.

**Comment by sttts** [comment]
Lgtm. Waiting for lgtm from network team before approving.

**Comment by abhat** [comment]
@markdgray thanks for updating the API spec. this looks more intuitive and cleaner. Appreciate the diligence. Kudos!

**Comment by markdgray** [comment]
> @markdgray thanks for updating the API spec. this looks more intuitive and cleaner. Appreciate the diligence. Kudos!

Yeah, I agree, it looks better.

**Pull request merged**
