### PR TITLE
operator: add cloudcredential type

### PR DESCRIPTION
**Pull request by sjenning**
@derekwaynecarr @joelddiaz @dgoodwin 

First step to getting OCP conformant operator config

This spec will eventually need to contain a field that allows disabling credential creation as the special configmap does today.  We will need to write a sync routine to copy the intent from the configmap to the new operator config for cluster upgrade.

### CODE REVIEW

**Comment by dgoodwin** [comment]
Apologies Seth but could we get a little more info on why this is being done, CCO is almost relegated to a side project we're trying to maintain so we're not 100% in the headspace and having a bit of trouble keeping up.

What is an OCP conformant config operator? Is there anything we could read up on for that? It sounds as though you plan to introduce another operator layer above the CCO to manage it?

I raised the use of ConfigMap vs a specific CRD on the group g arch call way back when we took our first pass at disabled CCO and the configmap seemed to be the preferred approach.

**Comment by sjenning** [comment]
/hold

I think I'm just going to bolt on the static asset controller to the existing codebase for now.  Then I might try to do the refactor that would require this change.

**Comment by joelddiaz** [comment]
/close
will have to revisit this another day

**Comment by joelddiaz** [comment]
actually, most of this was addressed in https://github.com/openshift/api/pull/692

**Pull request closed without merging**
