### PR TITLE
MULTIARCH-4776: MULTIARCH-4770: installer: promote MultiArchInstall FGs

### PR DESCRIPTION
**Pull request by r4f4**
Add MultiArchInstallAWS and MultiArchInstallGCP to the Default feature set.

AWS multi-arch day-0 periodics: [sippy link](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-heterogeneous-day-0%22%7D%5D%7D)
GCP multi-arch day-0 periodics: [sippy link](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-heterogeneous-day-0%22%7D%5D%7D)

### CODE REVIEW

**Comment by r4f4** [comment]
/assign @JoelSpeed 

We're very close to the 95% for GCP. AWS already reached that.
```
error: only 0 tests found, need at least 5 for "MultiArchInstallAWS" on {aws amd64 hypershift}
error: "install should succeed: overall" only passed 94%, need at least 95% for "MultiArchInstallGCP" on {gcp amd64 ha} 
```

The hypershift "0 tests" is expected: it doesn't support arm64 control plane node pools yet and it doesn't use the openshift-install code for provisioning, so these feature gates have no effect there.

**Comment by bryan-cox** [comment]
> /assign @JoelSpeed
> 
> We're very close to the 95% for GCP. AWS already reached that.
> 
> ```
> error: only 0 tests found, need at least 5 for "MultiArchInstallAWS" on {aws amd64 hypershift}
> error: "install should succeed: overall" only passed 94%, need at least 95% for "MultiArchInstallGCP" on {gcp amd64 ha} 
> ```
> 
> The hypershift "0 tests" is expected: it doesn't support arm64 control plane node pools yet and it doesn't use the openshift-install code for provisioning, so these feature gates have no effect there.

Yeah this doesn't affect HyperShift. We don't use the openshift-install for provisioning.

**Comment by r4f4** [comment]
Installer testing of o/api bump: https://github.com/openshift/installer/pull/8808

**Comment by JoelSpeed** [comment]
Based on testing information provided above, I think we are good to move forward here
/lgtm
/override ci/prow/verify

**Pull request merged**
