### PR TITLE
Cluster scope for config/v1 node CRD

### PR DESCRIPTION
**Pull request by swghosh**
Node CRD added in openshift/api#1107 should be made cluster scoped instead of namespace scoped since the enhancement proposals [1] [2] also intends to make cluster level changes.

[1] https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md#proposal
[2] https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md#api-extensions

Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Review by sairameshv — APPROVED** [review]

**Comment by swghosh** [comment]
Also, due to this line being present, though CRD yaml for now contains `scope: Namespaced` https://github.com/openshift/api/blob/1d1610eb722f617ce726dd21194097a72a24848b/config/v1/types_node.go#L6 I think the corresponding [openshift/client-go clientset node](https://github.com/openshift/client-go/blob/25b55b99bd2427b2c7e09c53b502469280a2dd0b/config/clientset/versioned/typed/config/v1/node.go) is also not working as expected. Get/List/etc. client seems to be namespace scoped, producing errors at runtime `node.config.openshift.io NotFound`.

We used the following last time to generate the CRD yaml from the [types_node.go](https://github.com/openshift/api/blob/abf6417c27488f872d29b991734059c7ae449273/config/v1/types_node.go) directly which created a namespace scoped CRD.
```
make ensure-controller-gen
_output/tools/bin/controller-gen-v0.7.0 object paths=./config/v1 +output:artifacts:config=./config/v1 crd webhook
```
So I added this line to instruct kubebuilder to generate a Cluster scoped CRD this time:
https://github.com/openshift/api/blob/1d1610eb722f617ce726dd21194097a72a24848b/config/v1/types_node.go#L13

Any better tooling available to generate CRDs for new resource might help.

**Comment by swghosh** [comment]
/remove-hold

@deads2k Can you PTAL? I added status as a subresource in the crd yaml.

**Comment by omertuc** [comment]
Looks like this broke the e2e-upgrade job when vendored in cluster-config-operator:
```
E0405 11:32:50.139004       1 task.go:112] error running apply for customresourcedefinition "nodes.config.openshift.io" (51 of 787): CustomResourceDefinition.apiextensions.k8s.io "nodes.config.openshift.io" is invalid: spec.scope: Invalid value: "Cluster": field is immutable
```

**Pull request merged**
