### PR TITLE
operator/ingress: Default GCP to LoadBalancer

### PR DESCRIPTION
**Pull request by Miciah**
Use `LoadBalancerService` as the default endpoint publishing strategy type on GCP.

* `operator/v1/types_ingress.go` (`IngressControllerSpec`): Document that the default endpoint publishing strategy type on GCP is `LoadBalancerService`.
* `operator/v1/zz_generated.swagger_doc_generated.go:` Regenerate.

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @smarterclayton for approval

**Comment by soltysh** [comment]
We're missing 4.1 branches, holding merges temporarily.

**Comment by ironcladlou** [comment]
@knobunc can you tag this one in?

**Pull request merged**
