### PR TITLE
Bug 1794804: Remove Description from CLI output to improve its display

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1794804

@benjaminapetersen

### CODE REVIEW

**Comment by rhamilto** [comment]
@benjaminapetersen, @spadgett review please?

**Comment by spadgett** [comment]
@benjaminapetersen is this file generated?

/hold

**Comment by spadgett** [comment]
/hold cancel

I see only the schema is generated. Sorry for the noise

**Pull request merged**
