### PR TITLE
MON-3538: Promote MetricsServer FeatureGate to GA

### PR DESCRIPTION
**Pull request by slashpai**
Placeholder to promote MetricsServer FeatureGate to GA.

This is also to test if tests are failing when promoted to GA

Enhancement proposal: https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/replace-prometheus-adapter-with-metrics-server.md

Autoscaling/HPA uses resource metrics api and we see techpreview jobs for HPA is passing 100%

[HPA/Autoscaling Sippy Test Link](https://sippy.dptools.openshift.org/sippy-ng/tests/4.16/details?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522current_runs%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25227%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522never-stable%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522Feature%253AHPA%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522techpreview%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage)

Testing APIService during upgrade: https://issues.redhat.com/browse/MON-3539

cc: @simonpasquier @jan--f @juzhao

### CODE REVIEW

**Comment by slashpai** [comment]
cc: @simonpasquier @jan--f 

This was used to trigger all the tests

**Comment by deads2k** [comment]
Can you either

1.    link to the automated tests results in periodic jobs running on a schedule to ensure regression protection both from the owning component and other components via side-effect (cluster-node-tuning-operator just benefited from such protection when an MCO PR broke them)
2.    A direct QE sign off that this feature is ready.

See deeper examples of how to be promoted here: https://github.com/openshift/enhancements/blob/master/dev-guide/featuresets.md#id-like-to-declare-a-feature-accessible-by-default--what-is-the-process

**Comment by juzhao** [comment]
ci/prow/verify failed for
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/1851/pull-ci-openshift-api-master-verify/1778771838210412544
```
 F0412 13:26:08.030722  159687 root.go:64] Error running codegen: error: only 0 tests found, need at least 5 for "MetricsServer" on {vsphere-ipi amd64 ha}
error: only 0 tests found, need at least 5 for "MetricsServer" on {aws amd64 hypershift}
error: only 0 tests found, need at least 5 for "MetricsServer" on {aws amd64 ha}
error: only 0 tests found, need at least 5 for "MetricsServer" on {azure amd64 ha}
error: only 0 tests found, need at least 5 for "MetricsServer" on {gcp amd64 ha}
make: *** [Makefile:54: verify-scripts] Error 255 
```
no tests in this PR. QE is working on test this PR

**Comment by juzhao** [comment]
tested on AWS and hypershift-host cluster, metrics-server is enabled by default, just a small bug https://issues.redhat.com/browse/OCPBUGS-32342 should be fixed after GA, metrics-server works well. I think we can merge this PR.

**Comment by juzhao** [comment]
see from https://issues.redhat.com/browse/MON-3539 upgrade test is done, no issue.
/label qe-approved

**Comment by deads2k** [comment]
QE has signed off
/override ci/prow/verify

/lgtm
/approve

**Pull request merged**
