### PR TITLE
Rename console extension CRDs

### PR DESCRIPTION
**Pull request by benjaminapetersen**
We don't need the extra noise in the file names:
- `0000_10_config-operator_01_consoleclidownload.crd.yaml` -> `0000_10_consoleclidownload.crd.yaml`

/cc @spadgett @bparees

### CODE REVIEW

**Comment by spadgett** [comment]
Did you miss renaming the sample CRD?

**Comment by soltysh** [comment]
@benjaminapetersen you need a rebase

**Comment by benjaminapetersen** [comment]
Rebased.
Though... no actual code changes required :open_mouth:

**Pull request merged**
