### PR TITLE
Allow multiple FeatureGates in integration test config

### PR DESCRIPTION
**Pull request by swghosh**
Using a comma separated string containing multiple feature gates in a single string in `SuiteSpec` (integration test config).

### CODE REVIEW

**Comment by swghosh** [comment]
@JoelSpeed PTAL

**Comment by JoelSpeed** [comment]
I think this looks ok generally, but, any idea why it thinks the controlplanemachineset without MachineAPIMigration file now has no CRD to match with?

And, do we have anything we can use to demonstrate that this achieves what we want? Allowing combinations of gates for tests?

**Comment by chiragkyal** [comment]
>I think this looks ok generally, but, any idea why it thinks the controlplanemachineset without MachineAPIMigration file now has no CRD to match with?
>
> And, do we have anything we can use to demonstrate that this achieves what we want? Allowing combinations of gates for tests?

https://github.com/openshift/api/pull/2086/commits/77b2eb581ec428278e131914a6c2b32898cff158 can fix the issue and demonstrate that it works as expected.

**Comment by JoelSpeed** [comment]
/lgtm
/label acknowledge-critical-fixes-only

No effect on the payload for this PR

Thanks @swghosh

**Pull request merged**
