### PR TITLE
Make config/v1 package default to optional in kubebuilder

### PR DESCRIPTION
**Pull request by damemi**
This adds the package-level `optional` tag, defaulting every field to `optional` unless explicitly set with `+kubebuilder:validation:Required`

Note that this will make *all* fields optional, and component owners should take care to verify that their fields are appropriately marked. See https://jira.coreos.com/browse/MSTR-790

### CODE REVIEW

**Comment by deads2k** [comment]
This is the correct behavior.  All config types should be able to run completely empty.

/hold 
hold for agreement.

**Comment by smarterclayton** [comment]
Not true for cluster version unfortunately.

**Comment by smarterclayton** [comment]
Also, I assume this doesn't change rules around metadata?  Just spec?

**Comment by smarterclayton** [comment]
(I kind of expected this to be used to regenerate the crds schema and prove that no fields changed, or those that did were reviewed)

**Comment by damemi** [comment]
@smarterclayton right, this only affects types under this package. I do have an example pull demonstrating the current effects of this change here: https://github.com/openshift/cluster-config-operator/pull/78

However you are also correct that there are required fields that will need to be properly marked, which we've opened a Jira card to break down by component and track https://jira.coreos.com/browse/MSTR-790

**Comment by smarterclayton** [comment]
Should I comment there?

**Comment by damemi** [comment]
@smarterclayton if you can help us identify what should be required (or who owns the affected components) please do!

**Comment by smarterclayton** [comment]
There's a ton of things that should be marked required, this is great data (and the teams need to review).  I would recommend having each responsible team review the required's on your other pull and then open bugs fixing them.

**Comment by sttts** [comment]
@smarterclayton see https://github.com/openshift/api/pull/393. The questionable fields that are new are all in status. For them we don't care as only operators write them.

For everything pre-existing in 4.1, we cannot make them suddenly required without breaking customer config that already exist. A review for those is too late.

**Comment by deads2k** [comment]
/hold cancel

This restores the behavior we had in 4.1.  The fields that have been added since are operator managed, so they can fix up their required separately if they wish..

/lgtm

**Pull request merged**
