### PR TITLE
make additionaltrustedca a pointer

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k ptal

I will follow up w/ the client-go PR if you agree w/ this change.

**Comment by bparees** [comment]
(also it's going to become really difficult to make breaking/incompatible api changes once we have multiple operators consuming these config objects.  That's a feature post-GA but right now it's going to be painful).

**Comment by smarterclayton** [comment]
We’re planning on a few api “days of destruction” during the next few milestones to sort these out.

**Comment by deads2k** [comment]
We have used pointers in the past for 

1. preserving an empty choice instead of no choice.  I don't think this one qualifies since empty configmap ref (at least for this field) is the same as no choice and I can't think of a practical difference for it.
2. being able to default bools to `false`.  Obviously not, but point it out.  I think we should avoid this in the future.
3. one-of choices.  Only one should be non-nil when choosing something like a volume source.  It should be paired with a discriminator to make intent safer across serialization versions.

Practically for a user we need to consider whether it is easier for a user in terms of specifying patch, update, and apply.  And also easier in our code to require many nil checks (or risk NPE) instead of a length check.

I don't see the benefit here.  If we find a benefit in the majority of cases (or if I've missed one) we can revisit.

**Pull request closed without merging**
