### PR TITLE
Move PowerVS CAPI install platform to default feature set

### PR DESCRIPTION
**Pull request by hamzy**
Moves PowerVS capi installs to default feature set.

### CODE REVIEW

**Comment by hamzy** [comment]
@JoelSpeed Do you know why the verify test is failing?

**Comment by JoelSpeed** [comment]
```
INSUFFICIENT CI testing for "ClusterAPIInstallPowerVS".
F0529 14:16:38.351201  168895 root.go:64] Error running codegen: error: only 0 tests found, need at least 5 for "ClusterAPIInstallPowerVS" on {aws amd64 hypershift}
error: only 0 tests found, need at least 5 for "ClusterAPIInstallPowerVS" on {aws amd64 ha}
error: only 0 tests found, need at least 5 for "ClusterAPIInstallPowerVS" on {azure amd64 ha}
error: only 0 tests found, need at least 5 for "ClusterAPIInstallPowerVS" on {gcp amd64 ha}
error: only 0 tests found, need at least 5 for "ClusterAPIInstallPowerVS" on {vsphere-ipi amd64 ha}
```

To promote features to default, we are asking for QE sign off or testing. There is some automated gating for tests in origin for feature gates, but, your feature doesn't meet the requirements (and I don't think can, so don't worry).

Can you please link in the PR description to show what testing has been done so far? And ideally, get QE sign off for the promotion of the gate?

**Pull request closed without merging**
