### PR TITLE
[release-4.13] DNS: Add awsPrivateHostedZoneRole

### PR DESCRIPTION
**Pull request by patrickdillon**
4.13 backport of https://github.com/openshift/api/pull/1460

Adds a field to the DNS config to hold a role to assume when performing cross-account installs in an AWS shared VPC environment.

### CODE REVIEW

**Comment by mrunalp** [comment]
@JoelSpeed @deads2k ptal

**Comment by JoelSpeed** [comment]
This appears to be a backport of https://github.com/openshift/api/pull/1460

I would expect the original approvers to tag this too, CC @deads2k @Miciah

**Comment by gcs278** [comment]
I've reviewed and also LGTM

**Comment by patrickdillon** [comment]
/hold
ready for review & tags but we need to line up the rest of the 4.13 backports to ship in a btach

**Comment by patrickdillon** [comment]
@deads2k @JoelSpeed 
As part of this backport should I add `privateHostedZoneAWS` to the default feature set for 4.13? I'm not sure where we stand with that functionality in 4.13.
https://github.com/openshift/api/blob/61a5301895a5b980f4b80885ecb2397ccc446164/config/v1/types_feature.go#L200

**Comment by JoelSpeed** [comment]
> As part of this backport should I add privateHostedZoneAWS to the default feature set for 4.13?

Was this feature introduced behind a feature gate, but then promoted to stable in 4.14? If the intention is for this backport to be available by default in 4.14, then backporting the feature gate to the stable set serves little purpose as far as I can tell

**Comment by patrickdillon** [comment]
/retitle [release-4.13] OCPSTRAT-659: DNS: Add awsPrivateHostedZoneRole

**Pull request merged**
