### PR TITLE
Bug 1978798: Revert "Update ovnKubernetesConfig.policyAuditConfig Default"

### PR DESCRIPTION
**Pull request by astoycos**
Remove the unecessary yaml patch for the ClusterNetworkOperator
CRD since this wasn't working as intended anyways. See bz for more info

This reverts commit 6f0ce8c5f8b21d0262af50e99f3f9a6dcc0008e3.

### CODE REVIEW

**Comment by astoycos** [comment]
@sttts If you get the chance can you PTAL a look at this?

**Comment by deads2k** [comment]
Worst diff ever.  Was there a difference between nil and empty in the handling code?

**Comment by astoycos** [comment]
Yaml patches introduced these ugly diffs in the first place I believe :/ 

This patch hack was originally needed because of this [Kubebuilder bug](https://github.com/kubernetes-sigs/controller-tools/issues/622) and only effected users on clusters upgrading from when the new audit logging config object didn't exist (Pre-4.8).  In 4.8 and later the defaults for the audit logging config are properly populated, and in upgrade clusters the workaround is documented in the bug. 

Regardless the [kubebuilder defaults](https://github.com/openshift/api/blob/master/operator/v1/0000_70_cluster-network-operator_01.crd.yaml#L359) still work just fine when the policyAuditConfig exists AND the [CNO handles if the config is null ](https://github.com/openshift/cluster-network-operator/blob/master/pkg/network/ovn_kubernetes.go#L787).

Lastly, The CNO doesn't need to distinguish between "nil" and "empty" in this case.

**Comment by andreaskaris** [comment]
@deads2k @astoycos Any consensus here?

**Comment by astoycos** [comment]
> So the thought is that clusters that are upgrading to 4.12 will already have this stanza? If so, I'm ok with this

They should and if for some reason they don't it's very easy to add 

> In the future, try to avoid using pointers and defaults in configuration APIs. Empty objects help with discoverability and handling "no opinion" differently that user selected choices allows for evolution over time. 

Agreed, at the time I was just following the advice from the team.

**Pull request merged**
