### PR TITLE
Allow consistent verification across platforms with container verify target

### PR DESCRIPTION
**Pull request by JoelSpeed**
As a mac user, I can generate assets with `RUNTIME=docker make generate-with-container`. However, this takes a really long time so on occasion, it might be easier to update (eg godoc changes into swagger) the assets manually.

At the moment, because I run the generation in container, the assets are built for linux, not darwin, so the verify target fails. I know others have also had issues with running verify locally so I thought it might be useful to have a container based verify for those who aren't able to run it within their own development environments easily.

### CODE REVIEW

**Comment by elmiko** [comment]
i ran this locally (fedora 35) and it failed with this output (which is similar to what i get when running `make verify`):

```
podman run -ti --rm -v /home/mike/dev/openshift-api:/go/src/github.com/openshift/api:z -w /go/src/github.com/openshift/api openshift-api-generator make verify                                                                                                                             
Running `gofmt -s -l` on 368 file(s).                                                                                                                                                                                                                                                        
go vet -mod=vendor ./_output/... ./annotations/... ./apiserver/... ./apps/... ./authorization/... ./build/... ./cloudnetwork/... ./cmd/... ./config/... ./console/... ./dependencymagnet/... ./github.com/... ./helm/... ./image/... ./imageregistry/... ./kubecontrolplane/... ./legacyconfig
/... ./machine/... ./network/... ./networkoperator/... ./oauth/... ./openshiftcontrolplane/... ./operator/... ./operatorcontrolplane/... ./operatoringress/... ./osin/... ./pkg/... ./project/... ./quota/... ./route/... ./samples/... ./security/... ./securityinternal/... ./servicecertsig
ner/... ./sharedresource/... ./template/... ./third_party/... ./tls/... ./tmp/... ./tools/... ./unidling/... ./user/...                    
go: warning: "./_output/..." matched no packages                                                                                           
go: warning: "./dependencymagnet/..." matched no packages                                                                                  
go: warning: "./third_party/..." matched no packages                                                                                       
go: warning: "./tls/..." matched no packages                                                                                               
go: warning: "./tmp/..." matched no packages                                                                                               
# github.com/openshift/api/github.com/openshift/api/console/v1alpha1                                                                       
vet: github.com/openshift/api/console/v1alpha1/zz_generated.deepcopy.go:13:11: undeclared name: ConsolePlugin                              
# github.com/openshift/api/github.com/openshift/api/image/docker10                                                                         
vet: github.com/openshift/api/image/docker10/zz_generated.deepcopy.go:13:11: undeclared name: DockerConfig                                 
# github.com/openshift/api/github.com/openshift/api/image/dockerpre012                                                                     
vet: github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go:13:11: undeclared name: Config                                   
# github.com/openshift/api/github.com/openshift/api/network/v1                                                                             
vet: github.com/openshift/api/network/v1/zz_generated.deepcopy.go:13:11: undeclared name: ClusterNetwork                                   
# github.com/openshift/api/github.com/openshift/api/oauth/v1                                                                               
vet: github.com/openshift/api/oauth/v1/zz_generated.deepcopy.go:13:11: undeclared name: ClusterRoleScopeRestriction                        
# github.com/openshift/api/github.com/openshift/api/networkoperator/v1                                                                     
vet: github.com/openshift/api/networkoperator/v1/zz_generated.deepcopy.go:13:11: undeclared name: EgressRouter                             
# github.com/openshift/api/github.com/openshift/api/operatorcontrolplane/v1alpha1                                                          
vet: github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go:13:11: undeclared name: LogEntry                      
# github.com/openshift/api/github.com/openshift/api/operatoringress/v1                                                                     
vet: github.com/openshift/api/operatoringress/v1/zz_generated.deepcopy.go:13:11: undeclared name: DNSRecord                                
# github.com/openshift/api/github.com/openshift/api/route/v1                                                                               
vet: github.com/openshift/api/route/v1/zz_generated.deepcopy.go:13:11: undeclared name: Route                                              
# github.com/openshift/api/github.com/openshift/api/operator/v1alpha1                                                                      
vet: github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go:13:11: undeclared name: DelegatedAuthentication                   
# github.com/openshift/api/github.com/openshift/api/samples/v1                                                                             
vet: github.com/openshift/api/samples/v1/zz_generated.deepcopy.go:13:11: undeclared name: Config                                           
# github.com/openshift/api/github.com/openshift/api/securityinternal/v1                                                                    
vet: github.com/openshift/api/securityinternal/v1/zz_generated.deepcopy.go:13:11: undeclared name: RangeAllocation                         
# github.com/openshift/api/github.com/openshift/api/servicecertsigner/v1alpha1                                                             
vet: github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.deepcopy.go:13:11: undeclared name: ServiceCertSignerOperatorConfig  
# github.com/openshift/api/github.com/openshift/api/user/v1                                                                                
vet: github.com/openshift/api/user/v1/zz_generated.deepcopy.go:13:11: undeclared name: Group                                               
# github.com/openshift/api/github.com/openshift/api/apiserver/v1                                                                           
vet: github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go:14:11: undeclared name: APIRequestCount                                
# github.com/openshift/api/github.com/openshift/api/cloudnetwork/v1                                                                        
vet: github.com/openshift/api/cloudnetwork/v1/zz_generated.deepcopy.go:14:11: undeclared name: CloudPrivateIPConfig                        
# github.com/openshift/api/github.com/openshift/api/quota/v1                                                                               
vet: github.com/openshift/api/quota/v1/zz_generated.deepcopy.go:14:11: undeclared name: AppliedClusterResourceQuota                        
# github.com/openshift/api/github.com/openshift/api/helm/v1beta1                                                                           
vet: github.com/openshift/api/helm/v1beta1/zz_generated.deepcopy.go:14:11: undeclared name: ConnectionConfig                                  
# github.com/openshift/api/github.com/openshift/api/osin/v1                                                                                   
vet: github.com/openshift/api/osin/v1/zz_generated.deepcopy.go:14:11: undeclared name: AllowAllPasswordIdentityProvider                          
# github.com/openshift/api/github.com/openshift/api/sharedresource/v1alpha1                                                                      
vet: github.com/openshift/api/sharedresource/v1alpha1/zz_generated.deepcopy.go:14:11: undeclared name: SharedConfigMap                                
# github.com/openshift/api/github.com/openshift/api/console/v1                                                                                        
vet: github.com/openshift/api/console/v1/zz_generated.deepcopy.go:15:11: undeclared name: ApplicationMenuSpec                                                        
# github.com/openshift/api/github.com/openshift/api/build/v1                                                                                                 
vet: github.com/openshift/api/build/v1/zz_generated.deepcopy.go:14:11: undeclared name: BinaryBuildRequestOptions                                            
# github.com/openshift/api/github.com/openshift/api/apps/v1                                                                                                                                
vet: github.com/openshift/api/apps/v1/zz_generated.deepcopy.go:15:11: undeclared name: CustomDeploymentStrategyParams                                                
# github.com/openshift/api/github.com/openshift/api/authorization/v1                                                                                                 
vet: github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go:16:11: undeclared name: Action                                                                        
# github.com/openshift/api/github.com/openshift/api/config/v1                                                                                                                 
vet: github.com/openshift/api/config/v1/zz_generated.deepcopy.go:15:11: undeclared name: APIServer                                                                                                                      
# github.com/openshift/api/github.com/openshift/api/image/v1                                                                                                                               
vet: github.com/openshift/api/image/v1/zz_generated.deepcopy.go:14:11: undeclared name: DockerImageReference                                                                               
# github.com/openshift/api/github.com/openshift/api/machine/v1                                                                                                                                            
vet: github.com/openshift/api/machine/v1/zz_generated.deepcopy.go:15:11: undeclared name: AWSFailureDomain                                                                                                
# github.com/openshift/api/github.com/openshift/api/machine/v1beta1                                                                                                                                                                            
vet: github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go:16:11: undeclared name: AWSMachineProviderCondition                                                                                              
# github.com/openshift/api/github.com/openshift/api/security/v1                                                                                                                                                         
vet: github.com/openshift/api/security/v1/zz_generated.deepcopy.go:14:11: undeclared name: AllowedFlexVolume                                                                                                                          
# github.com/openshift/api/github.com/openshift/api/project/v1                                                                                                                                                                        
vet: github.com/openshift/api/project/v1/zz_generated.deepcopy.go:14:11: undeclared name: Project                                                                                                                                              
# github.com/openshift/api/github.com/openshift/api/template/v1                                                                                                                                                                                        
vet: github.com/openshift/api/template/v1/zz_generated.deepcopy.go:14:11: undeclared name: BrokerTemplateInstance                                                                                                                                      
# github.com/openshift/api/github.com/openshift/api/operator/v1                                                                                                                                                                                              
vet: github.com/openshift/api/operator/v1/zz_generated.deepcopy.go:16:11: undeclared name: AWSClassicLoadBalancerParameters                                                                                                                                         
# github.com/openshift/api/github.com/openshift/api/kubecontrolplane/v1                                                                                                                                                                                                  
vet: github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go:14:11: undeclared name: AggregatorConfig                                                                                                                                                           
# github.com/openshift/api/github.com/openshift/api/openshiftcontrolplane/v1                                                                                                                                                                                                      
vet: github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go:16:10: undeclared name: AllowedRegistries                                                                                                                                                           
# github.com/openshift/api/github.com/openshift/api/legacyconfig/v1                                                                        
vet: github.com/openshift/api/legacyconfig/v1/zz_generated.deepcopy.go:15:11: undeclared name: ActiveDirectoryConfig                       
# github.com/openshift/api/github.com/openshift/api/imageregistry/v1                                                                         
vet: github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go:18:11: undeclared name: Config                                        
make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk:26: verify-govet] Error 2                       
make: *** [Makefile:71: verify-with-container] Error 2                
```

**Comment by elmiko** [comment]
i ran this on an ubuntu vm with a fresh checkout and docker installed, it worked as expected

**Comment by elmiko** [comment]
i cleaned my local repository on the fedora box and ran the tests again. it worked cleanly this time, but i do see some SELinux alerts during the process. here is an example:

```
SELinux is preventing mv from relabelto access on the file zz_generated.swagger_doc_generated.go.
```
i think this is related to moving files from inside the container to outside, additional info:
```
Additional Information:
Source Context                system_u:system_r:container_t:s0:c677,c820
Target Context                system_u:object_r:fusefs_t:s0
Target Objects                zz_generated.swagger_doc_generated.go [ file ]
Source                        mv
Source Path                   mv
```

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
