### PR TITLE
STOR-1119, STOR-751: CSI migration for vSphere and Azure file are GA

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
For reviewers, this would be nice to have *before* rebase to Kubernetes 1.26 lands. The feature gates are beta (enabled) in upstream Kubernetes 1.25 and we disable them in 4.12 via these feature gates. They are GA in 1.26 and cannot be disabled there. Using them as `--feature-gate` on cmdline results in warnings.

**Comment by bertinatto** [comment]
CSI migration for vSphere and Azure File are currently Tech Preview, so we can use related jobs to confirm the feature is working:

## vSphere
* https://testgrid.k8s.io/redhat-openshift-ocp-release-4.12-informing#periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-ovn-techpreview
* Generic ephemeral tests should be fixed with https://github.com/openshift/origin/pull/27588. Waiting for a job run that confirms that.
### Azure File
* https://testgrid.k8s.io/redhat-openshift-ocp-release-4.12-informing#periodic-ci-openshift-release-master-ci-4.12-e2e-azure-sdn-techpreview
* Azure File tests are passing, job is failing for unrelated reasons.

**Comment by bertinatto** [comment]
Placeholder PRs to bump openshift/api:

KCM operator: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/672
Apiserver operator: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1414
Scheduler operator: https://github.com/openshift/cluster-kube-scheduler-operator/pull/450
MCO: https://github.com/openshift/machine-config-operator/pull/3443

Because of the carry-patches we have in k/o, the ordering which these PRs merge doesn't matter much, **but** we will merge MCO last because to make the operation more atomic (Attach Detach Controller (KCM) will effectively enable the CSI migration only after the Kubelet does that).

**Comment by JoelSpeed** [comment]
Thanks @bertinatto @jsafrane for the additional context, you may merge this when you are ready
/approve

**Comment by bertinatto** [comment]
/label qe-approved
This is required to merge for the k8s 1.26 rebase.

**Pull request merged**
