### PR TITLE
Add vSphere platform status

### PR DESCRIPTION
**Pull request by jcpowermac**
Like the other non-cloud platforms adding
vSphere to include status struct for virtual
ip addresses.

### CODE REVIEW

**Comment by jcpowermac** [comment]
Enhancements:
vSphere IPI: https://github.com/openshift/enhancements/pull/154
Baremetal Networking: https://github.com/openshift/enhancements/pull/148

**Comment by jcpowermac** [comment]
@adambkaplan when you have a moment can you PTAL?

**Comment by deads2k** [comment]
the API is acceptable (consistent and well-formed), but I cannot speak for whether it is correct.

/approve

@sdodson please find someone from the installer to have a look for correctness and/or completeness of the status here.

**Comment by deads2k** [comment]
> @sdodson please find someone from the installer to have a look for correctness and/or completeness of the status here.

if it changes significantly, please hold so I can have another look.

**Comment by mtnbikenc** [comment]
LGTM, however no permissions

**Comment by sdodson** [comment]
> LGTM, however no permissions
I've applied the label on your behalf.

**Pull request merged**
