### PR TITLE
SPLAT-820: graduate multi-zone API from tech preview

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/uncc @derekwaynecarr 
/uncc @knobunc 

uncc'ing folks to cut down on noise until we are ready for a review

**Comment by rvanderp3** [comment]
/assign @jcpowermac 
/assign @JoelSpeed 

Performed an installation with no feature gates with a release image built from this PR and cluster-config-operator#277 and with installer#6782.  My concern about the way that I did this change was that I backed out the `Default` and `TechPreviewNoUpgrade` feature definitions from the infrastructure object altogether.  Let me know what you think about this approach but it didn't make sense to be to keep the definitions around since there weren't any tech preview specific changes any longer. 

Confirmed that the infrastructure resource contained the topology provided by the installer.  Once this PR is merged, cluster-config-operator#277 will be updated to reference the this change.

**Comment by JoelSpeed** [comment]
API changes look good as far as I'm concerned, can we get some QE validation on this feature before we remove the TP gate? Do we want to get the CCMO changes in first and have those validated?

**Comment by JoelSpeed** [comment]
/approve

Can we get QE to check this pre-merge as well? Which team is owning QE for this feature?

**Comment by rvanderp3** [comment]
> /approve
> 
> Can we get QE to check this pre-merge as well? Which team is owning QE for this feature?

Sure thing, I'll follow up on this.

**Comment by rvanderp3** [comment]
@JoelSpeed @sgaoshang tested this https://issues.redhat.com/browse/SPLAT-865 it passed pre-merge testing.

**Pull request merged**
