### PR TITLE
Add API for MTU migration

### PR DESCRIPTION
**Pull request by jcaamano**
Adds MTU migration parameters to config and operator network CRDs.

Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/network/allow-mtu-changes.md

Sign ed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

### CODE REVIEW

**Comment by knobunc** [comment]
/approve

Looks reasonable to me.  I'd like another person to look over it too, so holding off on the lgtm.

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
