### PR TITLE
Power VS: Move Power VS to CAPI by default

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Comment by mjturek** [comment]
@JoelSpeed @patrickdillon We are feeling pretty good about the results of the CAPI job, could we merge this? https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-ppc64le-powervs-capi

**Comment by JoelSpeed** [comment]
Did we reach a conclusion about whether we are ok not having disconnected support in 4.17?

Do you have a sippy link that shows the jobs over time?

**Comment by mjturek** [comment]
The conclusion from the multiarch PM is that having the disconnected path for 4.17 be install with 4.16 and upgrade to 4.17 is okay.

I believe the recommendation is a week of data from the periodics. The 4.17 CAPI job was broken until recently so sippy would not show the same success we are currently seeing.

**Comment by JoelSpeed** [comment]
So I'm looking at both the [capi](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-ppc64le-powervs-capi%22%7D%5D%7D) and [terraform](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-ppc64le-powervs-original%22%7D%5D%7D) runs and you're right, both aren't fantastic if you look back over time 😅 

But the [CAPI runs](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-ppc64le-powervs-capi%22%7D%5D%7D&sortField=timestamp&sort=desc) do appear to be looking good as far as I can tell.

Is there anyone else you need to get an LGTM from before we promote this? Perhaps @patrickdillon?

**Comment by mjturek** [comment]
absolutely! @patrickdillon I would love your input

**Comment by patrickdillon** [comment]
> absolutely! @patrickdillon I would love your input

This LGTM. I'm happy to see PowerVS go default with CAPI installs.

**Comment by JoelSpeed** [comment]
/lgtm
/override ci/prow/verify

/retest-required

Based on test output mentioned in https://github.com/openshift/api/pull/1979#issuecomment-2263379124, LGTM with Patricks approval

**Pull request merged**
