### PR TITLE
OCPBUGS-35051: Bump runlevel for ConsolePlugin CRD

### PR DESCRIPTION
**Pull request by jhadvig**
It looks like the ConsolePlugin v1 api object is not created in time for the console-operator, since after the 4.11 -> 4.12 update  console-operator is reporting:

```
...
2024-06-04T09:52:52.887020412Z W0604 09:52:52.886992       1 reflector.go:424] github.com/openshift/client-go/console/informers/externalversions/factory.go:101: failed to list *v1.ConsolePlugin: the server could not find the requested resource (get consoleplugins.console.openshift.io)
2024-06-04T09:52:52.887020412Z E0604 09:52:52.887011       1 reflector.go:140] github.com/openshift/client-go/console/informers/externalversions/factory.go:101: Failed to watch *v1.ConsolePlugin: failed to list *v1.ConsolePlugin: the server could not find the requested resource (get consoleplugins.console.openshift.io)
2024-06-04T09:53:30.853354736Z I0604 09:53:30.853322       1 shared_informer.go:281] stop requested
2024-06-04T09:53:30.853354736Z F0604 09:53:30.853338       1 base_controller.go:96] unable to sync caches for ConsoleOperator
```

/assign @wking

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Run level is part of an annotation on the API type, and then the file names are generated from there. Please review the Go type itself and you should see the `// +` marker to update

**Comment by JoelSpeed** [comment]
No, more like the annotation on https://github.com/openshift/api/blob/a837bee24500e12cf6b5608620a36983d96b1e36/operator/v1/types_serviceca.go#L14

There's a CVO run level I think is the one you want to change

**Comment by jhadvig** [comment]
Right, unfortunatelly I dont see these in `release-4.12` branch, which the PR aims against. Shall I add it ?

**Comment by JoelSpeed** [comment]
I did not notice this is for 4.12, is this updating the files to match what's present in master now?

**Comment by jhadvig** [comment]
Not necessarily, the issue is that API is not present on the 4.12 cluster after upgrade from 4.11.

**Comment by JoelSpeed** [comment]
> Not necessarily, the issue is that API is not present on the 4.12 cluster after upgrade from 4.11.

I suspect you are going to need to adjust the run level in master, to make sure it's installed prior to your operator being upgraded, and then backport from there.

But there's also the ordering within the run level, I'd have thought you could change that to make sure the CRD is installed in 4.12 prior to your operator being upgraded and breaking

**Comment by jhadvig** [comment]
I see that the consoleplugin go type has [runlvl 90](https://github.com/openshift/api/tree/master/console/v1/zz_generated.crd-manifests) and other console manifest are at `00`, is that correct ?

**Comment by JoelSpeed** [comment]
The rest of your manifests are at run level 90 in the operator repo itself, https://github.com/openshift/console-operator/tree/master/manifests

I think you need to add the run level, not the operator ordering, so it becomes run level 90 and operator order 01

**Pull request closed without merging**
