### PR TITLE
machine: azureprovider: data disk: add deletion policy

### PR DESCRIPTION
**Pull request by damdo**
It implements the api changes described in https://github.com/openshift/enhancements/pull/1070 to add a deletion policy field to Azure Data Disks.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Comment by damdo** [comment]
This project is not a part of the no-ff process, as such QE, PX and Docs labels need to be added manually

/label px-approved
/label qe-approved
/label docs-approved

**Pull request merged**
