### PR TITLE
CORS-3488: Add GCP CAPI installer to tech preview feature set.

### PR DESCRIPTION
**Pull request by barbacbd**
Depends on:

- [x] https://github.com/openshift/installer/pull/8386
- [ ] https://github.com/openshift/release/pull/51942

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Change looks good, please provide some basic proof that an install works with the feature and we can merge

**Comment by patrickdillon** [comment]
/lgtm

> Depends on:
> https://github.com/openshift/release/pull/51942 

We can merge this without the CI jobs, they are needed for promotion from TechPreview -> Default/GA, but not for this to merge. Also, we're doing testing in the techpreview set, not individual gates. Will leave comment on the release pr.

**Comment by barbacbd** [comment]
> Change looks good, please provide some basic proof that an install works with the feature and we can merge

@JoelSpeed the output below is running the installer after vendoring in these local changes.

```
apiVersion: v1
baseDomain: installer.gcp.devcluster.openshift.com
featureSet: TechPreviewNoUpgrade
metadata:
  name: bbarbach-20240513-162715
INFO Credentials loaded from environment variable "GOOGLE_APPLICATION_CREDENTIALS", file "/home/barbacbd/.gcp/bbarbach-norm-gcp-key.json" 
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.16.0-ec.3-x86_64). Please be warned, this is not advised 
INFO Consuming Install Config from target directory 
WARNING Failed to find information on quotas iam.googleapis.com/quota/service-account-count 
WARNING FeatureSet "TechPreviewNoUpgrade" is enabled. This FeatureSet does not allow upgrades and may affect the supportability of the cluster. 
INFO Creating infrastructure resources...         
INFO Started local control plane with envtest     
INFO Stored kubeconfig for envtest in: /home/barbacbd/dev/installer/assets/auth/envtest.kubeconfig 
INFO setting "GOOGLE_APPLICATION_CREDENTIALS" to /home/barbacbd/.gcp/bbarbach-norm-gcp-key.json for capg infrastructure controller 
INFO Running process: Cluster API with args [-v=2 --diagnostics-address=0 --health-addr=127.0.0.1:33003 --webhook-port=43181 --webhook-cert-dir=/tmp/envtest-serving-certs-2664346797] 
INFO Running process: gcp infrastructure provider with args [-v=2 --diagnostics-address=0 --health-addr=127.0.0.1:37649 --webhook-port=34221 --webhook-cert-dir=/tmp/envtest-serving-certs-2499959536] 
INFO Created manifest *v1.Namespace, namespace= name=openshift-cluster-api-guests 
INFO Created manifest *v1beta1.Cluster, namespace=openshift-cluster-api-guests name=bbarbach-20240513-162-mgqnq 
INFO Created manifest *v1beta1.GCPCluster, namespace=openshift-cluster-api-guests name=bbarbach-20240513-162-mgqnq 
INFO Waiting up to 15m0s (until 4:42PM EDT) for network infrastructure to become ready... 
INFO Network infrastructure is ready  
```

**Pull request merged**
