### PR TITLE
ETCD-488: Move etcd hardware speed feature to GA

### PR DESCRIPTION
**Pull request by dusk125**

### CODE REVIEW

**Comment by tjungblu** [comment]
/hold

waiting for apiserver confirmation the retry configs are reflected

**Comment by deads2k** [comment]
Can you either

1.    link to the automated tests results in periodic jobs running on a schedule to ensure regression protection both from the owning component and other components via side-effect (cluster-node-tuning-operator just benefited from such protection when an MCO PR broke them)
2.     A direct QE sign off that this feature is ready.

See deeper examples of how to be promoted here: https://github.com/openshift/enhancements/blob/master/dev-guide/featuresets.md#id-like-to-declare-a-feature-accessible-by-default--what-is-the-process

**Comment by soltysh** [comment]
This is waiting for https://github.com/openshift/origin/pull/28726

**Comment by dusk125** [comment]
/hold
for https://github.com/openshift/origin/pull/28726

**Comment by eggfoobar** [comment]
/hold

@dusk125 Apologies for the hold, but it seems like this addition will cause an increase in disruptions for SingleNode, we might want to consider what to do in this [test](https://github.com/openshift/origin/blob/5f629ff051c71eb4b08f96a68fa972bb42d56740/test/extended/etcd/hardware_speed.go#L19-L27) and how we want to handle it for SNO.

**Comment by eggfoobar** [comment]
/unhold

We decided to skip the test that would cause a high disruption, because the test currently only executes on techpreview, this shouldn't effect currently running SNO jobs. PR to skip test is here https://github.com/openshift/origin/pull/28800

**Comment by hasbro17** [comment]
It seems like we have enough runs of the `[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to update the hardware speed` test in the tech preview serial jobs where it is passing.

See [periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn-techpreview-serial](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.16?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn-techpreview-serial%22%7D%5D%7D) and [job history](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.16/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn-techpreview-serial%22%7D%5D%7D&sortField=timestamp&sort=desc).

**Comment by soltysh** [comment]
/override ci/prow/verify
The provided above results are satisfactory and will allow the feature to be promoted to stable.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label acknowledge-critical-fixes-only

**Comment by geliu2016** [comment]
Hello @soltysh , I saw you just retest this pr, I'm not sure whether we may start pre-merge test, because I just try to test it with 4.16.0-0.ci.test-2024-05-21-041439-ci-ln-vjhzitb-latest, but the this feature not ready yet.

$ oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.0-0.ci.test-2024-05-21-041439-ci-ln-vjhzitb-latest   True        False         38m     Cluster version is 4.16.0-0.ci.test-2024-05-21-041439-ci-ln-vjhzitb-latest
$ oc patch etcd/cluster --type=merge -p '{"spec": {"controlPlaneHardwareSpeed": "Slower"}}'
Warning: unknown field "spec.controlPlaneHardwareSpeed"
etcd.operator.openshift.io/cluster patched (no change)

**Pull request merged**
