### PR TITLE
API-1783: Promote ValidatingAdmissionPolicy to GA

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Set ValidatingAdmissionPolicy feature to be enabled by default

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Hold until after branching
/hold
@soltysh FYI

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/override ci/prow/verify 
this is needed for k8s 1.30 bump

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-hypershift
this is being tracked in https://issues.redhat.com/browse/TRT-1672

**Pull request merged**
