### PR TITLE
Add aliyun config api types

### PR DESCRIPTION
**Pull request by DahuK**
The PR contains changes needed to facilitate Alibaba Cloud support for cloud-credential-operator

### CODE REVIEW

**Comment by DahuK** [comment]
cc @deads2k @bparees , thanks

**Comment by bparees** [comment]
/approve

but i assume this isn't going into 4.8, right?
/hold

**Comment by DahuK** [comment]
> but i assume this isn't going into 4.8, right?

Yes, I think so

**Comment by bparees** [comment]
ok.  we'll have to wait until 4.9 branch cut is done to lift the hold, then.

**Comment by DahuK** [comment]
> ok. we'll have to wait until 4.9 branch cut is done to lift the hold, then.

got it, thanks

**Comment by DahuK** [comment]
@bparees  this hold a long time, please review again when you free, thx!
/remove-lifecycle stale

**Comment by DahuK** [comment]
Duplicate with #970 , close this one

**Pull request closed without merging**
