### PR TITLE
Migrate to build-machinery-go

### PR DESCRIPTION
**Pull request by tnozicka**
With github.com/openshift/build-machinery-go we can finally remove manually copying the alpha-build-machinery folder into hack. It is also out of date.

/cc @deads2k @sttts @soltysh @mfojtik

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
I am fixing the CI config. Also travis is going to be replaced

**Comment by tnozicka** [comment]
CI fixes https://github.com/openshift/release/pull/7411

**Comment by tnozicka** [comment]
/hold cancel
chicken-egg both ways

**Comment by deads2k** [comment]
@tnozicka says this will go green once https://github.com/openshift/release/pull/7411 merges, but something has to go first.  I'll let it be this.

**Pull request merged**
