### PR TITLE
[release-4.17] OCPBUGS-38355: Promote AWSEFSDriverVolumeMetrics to GA

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage 

xref: https://github.com/openshift/api/pull/2013

### CODE REVIEW

**Comment by gcharot** [comment]
PM approved for GA promotion in 4.17

**Comment by knobunc** [comment]
/approve

Staff eng approval for GA promotion

**Comment by chao007** [comment]
lgtm from QE

**Comment by JoelSpeed** [comment]
/override ci/prow/verify 

We only have manual testing for now and QE and Staff eng have signed off

/lgtm

**Pull request merged**
