### PR TITLE
Bug 1947793: Deprecated API in use

### PR DESCRIPTION
**Pull request by coreydaley**
move to v1 since v1beta1 will be removed in 4.9

### CODE REVIEW

**Comment by coreydaley** [comment]
/retest

 ERRO[2021-04-15T17:27:16Z] Some steps failed:                           
ERRO[2021-04-15T17:27:16Z]   * could not run steps: step verify failed: test "verify" failed: the pod ci-op-p150ppq9/verify failed after 1m47s (failed containers: test): ContainerFailed one or more containers exited 
ERRO[2021-04-15T17:27:16Z] Container test exited with code 2, reason Error 
ERRO[2021-04-15T17:27:16Z] W0415 17:27:13.007530   18135 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {http://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting... 
ERRO[2021-04-15T17:27:16Z] W0415 17:27:13.007534   18135 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {http://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting... 
ERRO[2021-04-15T17:27:16Z] W0415 17:27:13.007539   18135 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {http://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting... 
ERRO[2021-04-15T17:27:16Z] make: *** [verify-scripts] Error 1           
ERRO[2021-04-15T17:27:16Z] make: Target `verify' not remade because of errors.

**Comment by adambkaplan** [comment]
A few errors here:

```
[36mINFO[0m[2021-04-15T17:31:29Z] customresourcedefinition.apiextensions.k8s.io "builds.config.openshift.io" deleted 
[36mINFO[0m[2021-04-15T17:31:29Z] E0415 17:31:09.550386   18560 customresource_handler.go:668] error building openapi models for builds.config.openshift.io: ERROR $root.definitions.io.openshift.config.v1.Build.properties.spec.properties.buildDefaults.properties.env.items.<array>.properties.valueFrom.properties.resourceFieldRef.properties.divisor has invalid property: anyOf 
[36mINFO[0m[2021-04-15T17:31:29Z] ERROR $root.definitions.io.openshift.config.v1.Build.properties.spec.properties.buildDefaults.properties.resources.properties.limits.additionalProperties.schema has invalid property: anyOf 
[36mINFO[0m[2021-04-15T17:31:29Z] ERROR $root.definitions.io.openshift.config.v1.Build.properties.spec.properties.buildDefaults.properties.resources.properties.requests.additionalProperties.schema has invalid property: anyOf 
```

```
[36mINFO[0m[2021-04-15T17:31:29Z] error: error validating "./config/v1/0000_10_config-operator_01_build.crd.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false 
[36mINFO[0m[2021-04-15T17:31:29Z] Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "builds.config.openshift.io" not found
```

**Comment by coreydaley** [comment]
@adambkaplan ptal, all tests are passing

**Comment by wewang58** [comment]
Now cluster-bot failed to install the cluster with "invalid configuration: you must define at least one test or image build in 'tests' or 'images'"

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
