### PR TITLE
Update KuryrConfig.MTU setting description

### PR DESCRIPTION
**Pull request by dulek**
This updates the description with information on additional side-effect of the setting based on behavior from
openshift/cluster-network-operator#1586.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
Should `0000_70_cluster-network-operator_01_crd.yaml` and  consequently `operator/v1/zz_generated.swagger_doc_generated.go` be updated as well?

**Comment by dulek** [comment]
I had hard time trying to generate that, let's see.

**Comment by JoelSpeed** [comment]
/approve

> I had hard time trying to generate that, let's see.

@dulek If you can provide any feedback on the issues you saw, I'm currently working on improving the tooling experience in this repo so can take into account your issues

**Comment by dulek** [comment]
> /approve
> 
> > I had hard time trying to generate that, let's see.
> 
> @dulek If you can provide any feedback on the issues you saw, I'm currently working on improving the tooling experience in this repo so can take into account your issues

`make update-scripts` would mess protobuf code, `make update-codegen-Default-crds` wouldn't do anything, `make generate-with-container` failed with some error.

**Pull request merged**
