### PR TITLE
bug 2042049: Delete feature gates removed from k8s.io/kubernetes/pkg/features/kube_features.go

### PR DESCRIPTION
**Pull request by ingvagabund**
Based on https://github.com/kubernetes/kubernetes/pull/100776 LegacyNodeRoleBehavior, NodeDisruptionExclusion and ServiceNodeExclusion were GA-ed/removed in 1.22.
Based on https://github.com/kubernetes/kubernetes/pull/104163 SupportPodPidsLimit was removed/GA-ed in 1.20.

### CODE REVIEW

**Comment by ingvagabund** [comment]
FYI @sjenning @smarterclayton

**Comment by mburke5678** [comment]
@ingvagabund We document that the `SupportPodPidsLimit` feature is [activated by the TechPreviewNoUpdate feature gate](https://docs.openshift.com/container-platform/4.9/nodes/clusters/nodes-cluster-enabling-features.html#nodes-cluster-enabling-features-about_nodes-cluster-enabling).  Do we want to remove this from the docs, 4.7+? As in [this PR](https://github.com/openshift/openshift-docs/pull/40826/files#diff-17f46d9305040639ceb3dfbc0f5bc64625da1d3b3174750c4b2f377abaf90bb5)?

**Comment by ingvagabund** [comment]
It is enabled by default so the `TechPreviewNoUpgrade` no longer applies for it. Based on openshift/kubernetes releases:
```
$ git checkout release-4.10
Switched to branch 'release-4.10'
Your branch is behind 'origin/release-4.10' by 2852 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ grep -rn "SupportPodPidsLimit" --include "*.go"
pkg/features/kube_features.go:155:	SupportPodPidsLimit featuregate.Feature = "SupportPodPidsLimit"
pkg/features/kube_features.go:827:	SupportPodPidsLimit:                            {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.23
vendor/github.com/openshift/api/config/v1/types_feature.go:139:		"SupportPodPidsLimit",            // sig-pod, sjenning

$ git checkout release-4.9
Switched to branch 'release-4.9'
Your branch is up to date with 'origin/release-4.9'.
$ grep -rn "SupportPodPidsLimit" --include "*.go"
pkg/features/kube_features.go:155:	SupportPodPidsLimit featuregate.Feature = "SupportPodPidsLimit"
pkg/features/kube_features.go:827:	SupportPodPidsLimit:                            {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.23
vendor/github.com/openshift/api/config/v1/types_feature.go:139:		"SupportPodPidsLimit",            // sig-pod, sjenning

$ git checkout release-4.8
Switched to branch 'release-4.8'
Your branch is behind 'origin/release-4.8' by 10 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ grep -rn "SupportPodPidsLimit" --include "*.go"
pkg/features/kube_features.go:177:	SupportPodPidsLimit featuregate.Feature = "SupportPodPidsLimit"
pkg/features/kube_features.go:787:	SupportPodPidsLimit:                            {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.23
vendor/github.com/openshift/api/config/v1/types_feature.go:130:		"SupportPodPidsLimit",            // sig-pod, sjenning

$ git checkout release-4.7
Switched to branch 'release-4.7'
Your branch is behind 'origin/release-4.7' by 7 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ grep -rn "SupportPodPidsLimit" --include "*.go"
pkg/features/kube_features.go:195:	SupportPodPidsLimit featuregate.Feature = "SupportPodPidsLimit"
pkg/features/kube_features.go:756:	SupportPodPidsLimit:            {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.23
vendor/github.com/openshift/api/config/v1/types_feature.go:125:		"SupportPodPidsLimit",            // sig-pod, sjenning

$ git checkout release-4.6
Switched to branch 'release-4.6'
Your branch is behind 'origin/release-4.6' by 54 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ grep -rn "SupportPodPidsLimit" --include "*.go"
staging/src/k8s.io/kubelet/config/v1beta1/types.go:485:	// Requires the SupportPodPidsLimit feature gate to be enabled.
test/e2e_node/pids_test.go:121:var _ = SIGDescribe("PodPidsLimit [Serial] [Feature:SupportPodPidsLimit][NodeFeature:SupportPodPidsLimit]", func() {
test/e2e_node/pids_test.go:128:			initialConfig.FeatureGates["SupportPodPidsLimit"] = true
pkg/features/kube_features.go:208:	SupportPodPidsLimit featuregate.Feature = "SupportPodPidsLimit"
pkg/features/kube_features.go:683:	SupportPodPidsLimit:            {Default: true, PreRelease: featuregate.Beta},
pkg/generated/openapi/zz_generated.openapi.go:45670:							Description: "PodPidsLimit is the maximum number of pids in any pod. Requires the SupportPodPidsLimit feature gate to be enabled. Dynamic Kubelet Config (beta): If dynamically updating this field, consider that lowering it may prevent container processes from forking after the change. Default: -1",
pkg/kubelet/cm/pod_container_manager_linux.go:89:		if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) && m.podPidsLimit > 0 {
pkg/kubelet/cm/cgroup_manager_linux.go:280:	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) || utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportNodePidsLimit) {
pkg/kubelet/cm/cgroup_manager_linux.go:359:	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) || utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportNodePidsLimit) {
pkg/kubelet/cm/cgroup_manager_linux.go:421:	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) || utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportNodePidsLimit) {
pkg/kubelet/cm/cgroup_manager_linux.go:550:	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) || utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportNodePidsLimit) {
pkg/kubelet/cm/cgroup_manager_linux.go:611:	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) && cgroupConfig.ResourceParameters != nil && cgroupConfig.ResourceParameters.PidsLimit != nil {
pkg/kubelet/cm/cgroup_manager_linux.go:651:	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) && cgroupConfig.ResourceParameters != nil && cgroupConfig.ResourceParameters.PidsLimit != nil {
vendor/k8s.io/system-validators/validators/types_unix.go:64:		// The pids cgroup is optional since it is only used when at least one of the feature flags "SupportPodPidsLimit" and
vendor/github.com/openshift/api/config/v1/types_feature.go:125:		"SupportPodPidsLimit",            // sig-pod, sjenning
```

The feature gate check is no longer present in 4.7 and higher versions so mention of the `SupportPodPidsLimit` feature gate can be safely removed from the documentation.

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Comment by mburke5678** [comment]
@ingvagabund Forgive my not knowing the process. When will this change be released and which versions will it effect? TIA!

**Comment by ingvagabund** [comment]
The goal is to release the changes in 4.10. I am aware of KS and KCM being currently affected (manifesting as an error message in the logs). Porting the change through:
- https://github.com/openshift/cluster-kube-scheduler-operator/pull/401
- https://github.com/openshift/cluster-kube-controller-manager-operator/pull/592
Both PRs are currently blocked on failing CI tests whose resolution is in process.

**Pull request merged**
