### PR TITLE
NE-1774: Promote `IngressControllerLBSubnetsAWS` to GA

### PR DESCRIPTION
**Pull request by gcs278**
Promotes `IngressControllerLBSubnetsAWS` to from TechPreview/DevPreview to become available by default (GA).

### E2E Test Data:
- This feature gets tested by the [PreSubmit job](https://github.com/openshift/release/blob/d1efafda808dd6d346aa65bd86e01bfda2022485/ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-release-4.17.yaml#L154) `e2e-aws-operator-techpreview` in the [cluster-ingress-operator](https://github.com/openshift/cluster-ingress-operator) repo.
- Specifically, [TestAWSLBSubnets](https://github.com/openshift/cluster-ingress-operator/blob/64eafaef2a4e02056bb1976ce8c8ad25a1509d23/test/e2e/lb_subnets_test.go#L37) and [TestUnmanagedAWSLBSubnets](https://github.com/openshift/cluster-ingress-operator/blob/64eafaef2a4e02056bb1976ce8c8ad25a1509d23/test/e2e/lb_subnets_test.go#L172) both test the functionality of the `IngressControllerLBSubnetsAWS` feature gate.
- There isn't an origin E2E test for this feature, so I expect the `verify` job automation to fail. We will require manual [QE Signoff](https://github.com/openshift/enhancements/blob/master/dev-guide/featuresets.md#obtaining-qe-sign-off)
- Example Successful PreSubmit Runs:
  - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1114/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator-techpreview/1818807049249624064
  - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1114/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator-techpreview/1818845238211383296
  - https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1115/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator-techpreview/1819004886000340992

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Both verify jobs can be overridden once we are content that the testing is in place, the first is failing due to lack of tests, the second because of NoMaps on a CRD rename, which is not something we can fix right now

**Comment by lihongan** [comment]
Checked with pre-merge testing, the featuregate `IngressControllerLBSubnetsAWS` is enabled by default now, but cannot check the function because the ingresscontroller config `spec.endpointPublishingStrategy.loadBalancer.providerParameters.aws.classicLoadBalancer.subnets`  is ignored silently, Also tested in another TP enabled cluster and it works.
```
$ oc get featuregates.config.openshift.io cluster -oyaml
<......>
spec: {}
status:
  featureGates:
  - disabled:
<......>
    enabled:
    - name: IngressControllerLBSubnetsAWS
    version: 4.17.0-0.ci.test-2024-08-01-084745-ci-ln-z29h39b-latest
```
@gcs278 please let me know if this is expected or missing something?

**Comment by gcs278** [comment]
@lihongan I believe it's due to the same [errors](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/1966/pull-ci-openshift-api-master-integration/1818414773075709952) we see in the integration test.

I pushed a fix in this PR. CEL introduced in https://github.com/openshift/api/pull/1826/files#diff-891d2cdcb01603ef2a2c1bfb2f6ef32cf2acf8b1471871a5a6e27308d50050f9R703-R705 should have specified a feature gate. I tried it out in a cluster too. It's a bit odd, but seems like the CEL silently failed, rejected the `Subnets` in the spec, and created the IC anyways. If you checked your IngressController, the spec `Subnets` would look empty:
```yaml
spec:
  endpointPublishingStrategy:
    loadBalancer:
      dnsManagementPolicy: Managed
      providerParameters:
        aws:
          networkLoadBalancer: {}
          type: NLB
        type: AWS
```

**Comment by gcs278** [comment]
Weird, prow didn't run new tests after my push:
/test all

**Comment by gcs278** [comment]
> @lihongan I believe it's due to the same [errors](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/1966/pull-ci-openshift-api-master-integration/1818414773075709952) we see in the integration test.
> 
> I pushed a fix in this PR. CEL introduced in https://github.com/openshift/api/pull/1826/files#diff-891d2cdcb01603ef2a2c1bfb2f6ef32cf2acf8b1471871a5a6e27308d50050f9R703-R705 should have specified a feature gate. I tried it out in a cluster too. It's a bit odd, but seems like the CEL silently failed, rejected the `Subnets` in the spec, and created the IC anyways. If you checked your IngressController, the spec `Subnets` would look empty:

@lihongan Sorry, I think I confused two problems. The issue you see isn't related to the CEL Validation. I realized we _do_ need to re-vendor this change in the IngressOperator to get the updated [IngressController CRD](https://github.com/openshift/cluster-ingress-operator/blob/5a7fd3fbd8edd4176c9bdc711dc82e64abe414e7/manifests/00-custom-resource-definition.yaml).

So when you are doing testing, you must also update apply the IngressController CRD. I think that's why it's not working for you. You will have to apply the one from this PR: `operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml`

The `integration` [failure](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/1966/pull-ci-openshift-api-master-integration/1818414773075709952) exists due to bug where the CEL is restricted to a feature gate, introduced in https://github.com/openshift/api/pull/1826. That's now fixed in this PR.

**Comment by lihongan** [comment]
/label qe-approved

Thanks @gcs278 , after doing `oc apply -f ./0000_50_ingress_00_ingresscontrollers-Default.crd.yaml` then the `.subnets` setting in ingresscontroller works, the annotation is added to LB service. 
```
$ oc -n openshift-ingress get svc router-default -oyaml | grep subnet
    service.beta.kubernetes.io/aws-load-balancer-subnets: ci-ln-9vgmglb-76ef8-sl8sc-subnet-public-us-west-1a

$ oc get co ingress console
NAME      VERSION                                                   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
ingress   4.17.0-0.ci.test-2024-08-02-010240-ci-ln-9vgmglb-latest   True        False         False      21m     
console   4.17.0-0.ci.test-2024-08-02-010240-ci-ln-9vgmglb-latest   True        False         False      10m  
```

**Comment by miheer** [comment]
@JoelSpeed it looks like you might need to over-ride this test ?

**Pull request merged**
