### PR TITLE
Remove references to Docker when they are not needed

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
looks like swagger doc needs a regen too (did you run `make generate`? that should cover everything).

otherwise lgtm.  @openshift/api-review ?

**Comment by rhatdan** [comment]
@bparees I can't get  ./hack/update-deps.sh  to complete it is crashing with 
```
0xc000060e08 pc=0x56416d088da0
net/http.(*http2ClientConn).readLoop(0xc0004f68c0)
	/usr/lib/golang/src/net/http/h2_bundle.go:8197 +0x78 fp=0xc000060fd8 sp=0xc000060f70 pc=0x56416d088678
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000060fe0 sp=0xc000060fd8 pc=0x56416ce421f1
created by net/http.(*http2Transport).newClientConn
	/usr/lib/golang/src/net/http/h2_bundle.go:7272 +0x638
./hack/update-deps.sh: line 23:  6438 Aborted                 (core dumped) glide update --strip-vendor
```

make generate also fails.
```
make generate
hack/update-deepcopy.sh
Generating deepcopy funcs
hack/update-protobuf.sh
Generating protobuf requires protoc 3.0.x. Please download and
install the platform appropriate Protobuf package for your OS:

  https://github.com/google/protobuf/releases

To skip protobuf generation, set $PROTO_OPTIONAL.
2018/10/26 13:39:21 k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto: File not found.
k8s.io/api/core/v1/generated.proto: Import "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto" was not found or had errors.
github.com/openshift/api/apps/v1/generated.proto: Import "k8s.io/api/core/v1/generated.proto" was not found or had errors.
github.com/openshift/api/apps/v1/generated.proto:33:12: "k8s.io.api.core.v1.EnvVar" is not defined.
github.com/openshift/api/apps/v1/generated.proto:53:12: "k8s.io.api.core.v1.ObjectReference" is not defined.
github.com/openshift/api/apps/v1/generated.proto:121:12: "k8s.io.api.core.v1.ObjectReference" is not defined.
github.com/openshift/api/apps/v1/generated.proto:180:12: "k8s.io.api.core.v1.PodTemplateSpec" is not defined.
github.com/openshift/api/apps/v1/generated.proto:312:12: "k8s.io.api.core.v1.ResourceRequirements" is not defined.
github.com/openshift/api/apps/v1/generated.proto:340:12: "k8s.io.api.core.v1.ObjectReference" is not defined.
github.com/openshift/api/apps/v1/generated.proto:375:12: "k8s.io.api.core.v1.EnvVar" is not defined.
github.com/openshift/api/apps/v1/generated.proto:479:12: "k8s.io.api.core.v1.ObjectReference" is not defined.
github.com/openshift/api/apps/v1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/generated.proto but not used.
github.com/openshift/api/apps/v1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto but not used.
2018/10/26 13:39:21 protoc -I . -I /home/dwalsh/go/src -I hack/../vendor/github.com/gogo/protobuf/protobuf -I hack/../vendor --gogo_out=/home/dwalsh/go/src /home/dwalsh/go/src/github.com/openshift/api/apps/v1/generated.proto
2018/10/26 13:39:21 Unable to generate protoc on github.com.openshift.api.apps.v1: exit status 1
make: *** [Makefile:24: generate] Error 1
```

**Comment by rhatdan** [comment]
rpm -qf /usr/bin/protoc
protobuf-compiler-3.5.0-8.fc29.x86_64

**Comment by bparees** [comment]
i think you literally need 3.0 to make it happy.

```
$ protoc --version
libprotoc 3.0.0
```

no sure about the hack/deps update failure.  if you want i can cherry-pick your commit and do the generation on my machine and create a new PR.

**Comment by bparees** [comment]
(also you should not need to do a dep update anyway)

**Comment by rhatdan** [comment]
@bparees That would be awesome.  CherryPick away.

**Comment by bparees** [comment]
replaced by https://github.com/openshift/api/pull/117

**Pull request closed without merging**
