### PR TITLE
Add the memory manager as tech preview feature

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/cc @adambkaplan @sttts 
tagging relevant peoples accoding to the OWNERS file

**Comment by adambkaplan** [comment]
@fromanirh can you please link to the feature enhancement proposal, or other documentation to provide context?

**Comment by cynepco3hahue** [comment]
@adambkaplan Hi Adam,
- it the enhancement proposal - https://github.com/kubernetes/enhancements/pull/1203
- and the relevant PR - https://github.com/kubernetes/kubernetes/pull/95479

**Comment by cynepco3hahue** [comment]
It possible to add feature gate via custom feature set.

**Pull request closed without merging**
