### PR TITLE
OCPBUGS-35214: [Release 4-15] Add transit switch config to 4.15

### PR DESCRIPTION
**Pull request by bpickard22**
"Backport" of https://github.com/openshift/api/pull/1626

The CEL validations used here are not available in 4.15 so we have to use regex to validate the fields

### CODE REVIEW

**Comment by bpickard22** [comment]
@JoelSpeed @trozet PTAL

**Comment by JoelSpeed** [comment]
Validation and structure looks good now. Do we have the relevant QE testing done for the master branch feature? Are we happy that we can backport the feature without introducing any regressions in 4.15?

Have you got ack from a staff eng and your PM for the backport as well?

**Comment by knobunc** [comment]
I grant it Staff Engineer ACK, and PM (Marc Curry) has approved this backport too.

/approve
/lgtm

**Comment by bpickard22** [comment]
@JoelSpeed relevant testing is done on master and I will ask qe to run regression tests once the cno pr is up

**Comment by JoelSpeed** [comment]
> @JoelSpeed relevant testing is done on master and I will ask qe to run regression tests once the cno pr is up

Can the CNO PR not go up prior to this merging? Would that not allow complete testing before we merge anything into the backported branch?

**Comment by bpickard22** [comment]
@JoelSpeed cno pr is up and i have asked qe team to run regression tests, will ping you again once that is done

**Comment by anuragthehatter** [comment]
/label qe-approved

QE regression looks good

**Comment by JoelSpeed** [comment]
Where are we at on this? I see QE approved, is the implementation good to go? Have the team reviewed it and are happy to merge?

**Comment by bpickard22** [comment]
> Where are we at on this? I see QE approved, is the implementation good to go? Have the team reviewed it and are happy to merge?

just waiting on an approver from my team to apply the needed labels then this should merge @JoelSpeed

**Comment by bpickard22** [comment]
@JoelSpeed can you add the necessary labels here. we have staff approval, qe approval, and my team is good with this but does not have the perms to give the labels

**Pull request merged**
