### PR TITLE
Add Nutanix to the LoadBalancerProviderType enum

### PR DESCRIPTION
**Pull request by thunderboltsid**
- Update operator/v1/types_ingress.go to add Nutanix to LoadBalancerProviderType enum
- Regenerate operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- Regenerate operator/v1/zz_generated.swagger_doc_generated.go

### CODE REVIEW

**Comment by Miciah** [comment]
@rfredette, @thunderboltsid, I don't see a change to the godoc for the `EndpointPublishingStrategy` field or type.  Can you confirm for me that the default endpoint publishing strategy on Nutanix will be "HostNetwork" and that OpenShift will not manage wildcard DNS records for ingress on Nutanix?

**Comment by thunderboltsid** [comment]
> @rfredette, @thunderboltsid, I don't see a change to the godoc for the `EndpointPublishingStrategy` field or type.  Can you confirm for me that the default endpoint publishing strategy on Nutanix will be "HostNetwork" and that OpenShift will not manage wildcard DNS records for ingress on Nutanix?  

Yes, the default for Nutanix is HostNetwork.

**Comment by Miciah** [comment]
Thanks!
/lgtm

**Pull request merged**
