### PR TITLE
config.Build Cluster CRD

### PR DESCRIPTION
**Pull request by adambkaplan**
Add .yaml for build config CRD

Per https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/27/files/a7395235deacf2791803ac79a2785c3a569d57ab#r230193874

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by bparees** [comment]
it still lgtm. 

@deads2k bump.

**Comment by adambkaplan** [comment]
Closing per https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/28#issuecomment-436414049

**Pull request closed without merging**
