### PR TITLE
NE-1794: Promote `eipAllocations` API in GA

### PR DESCRIPTION
**Pull request by miheer**
Promote `eipAllocations` API in GA

### CODE REVIEW

**Comment by miheer** [comment]
@JoelSpeed PTAL

**Comment by melvinjoseph86** [comment]
/label qe-approved
Tested with cluster bot image
```
melvinjoseph@mjoseph-mac Downloads % oc get clusterversion 
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.17.0-0.ci.test-2024-08-05-055832-ci-ln-z57xcht-latest   True        False         28m     Cluster version is 4.17.0-0.ci.test-2024-08-05-055832-ci-ln-z57xcht-latest
$ oc get featuregates.config.openshift.io cluster -oyaml
<......>
spec: {}
status:
  featureGates:
  - disabled:
<......>
    enabled:
    - name: SetEIPForNLBIngressController
```

**Comment by JoelSpeed** [comment]
@miheer What is your intention for this feature gate promotion, just looking at the hold you've put on?

I can see the verify is failing due to a lack of automated tests, but you have QE approval.

So we could merge this assuming CI goes green?

@melvinjoseph86 Just looking at your comment, have you tested the complete feature end to end? The promotion isn't about the gate moving, but checking that the feature that it gates is working as expected and ready for GA

**Comment by miheer** [comment]
I see operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-Default.crd.yaml operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-DevPreviewNoUpgrade.crd.yaml operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-TechPreviewNoUpgrade.crd.yaml gets deleted.
From my understanding operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-Default.crd.yaml  should stay ? I see this file in 

Because when I try to run make generate  and make update  in cluster-ingress-operator after bumping this API change I get the following error because of this script https://github.com/openshift/cluster-ingress-operator/blob/master/hack/update-generated-crd.sh#L14-#L32:
GO111MODULE=on GOFLAGS=-mod=vendor go mod edit -replace=[github.com/openshift/api=github.com/miheer/api@3ebc16de700bce945d8c548c6a99d5ab06d083f1](http://github.com/openshift/api=github.com/miheer/api@3ebc16de700bce945d8c548c6a99d5ab06d083f1)
make generate
make update
cp: vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-Default.crd.yaml: No such file or directory
make: *** [crd] Error 1 (

**Comment by miheer** [comment]
@JoelSpeed thanks for explaining me in slack!.

**Comment by lihongan** [comment]
> @melvinjoseph86 Just looking at your comment, have you tested the complete feature end to end? The promotion isn't about the gate moving, but checking that the feature that it gates is working as expected and ready for GA

/remove-label qe-approved
need a feature test before adding the label

**Pull request merged**
