### PR TITLE
BZ 2088533: add subresource.status{} to sharedsecrets and sharedconfigmaps

### PR DESCRIPTION
**Pull request by DennisPeriquet**
relevant slack in case someone needs to [read](https://coreos.slack.com/archives/C01CQA76KMX/p1652975216903949).

### CODE REVIEW

**Comment by gabemontero** [comment]
I'm curious why the existing directives https://github.com/openshift/api/blob/053334452d48575ff5c89431e03e51a26e25c337/sharedresource/v1alpha1/types_shared_configmap.go#L34 and https://github.com/openshift/api/blob/053334452d48575ff5c89431e03e51a26e25c337/sharedresource/v1alpha1/types_shared_secret.go#L33 did not already produced the CRD yaml changes in this PR?

**Comment by DennisPeriquet** [comment]
Fixing the code gen issue is not feasible at this time so we'll try to get this to land in the meantime.

**Pull request merged**
