### PR TITLE
OCPBUGS-14497: Add CRD copies for LatencySensitive FeatureSet

### PR DESCRIPTION
**Pull request by dgrisonnet**
Similar effort to https://github.com/openshift/api/pull/1490, but with the LatencySensitive FeatureSet and based on the Default version of the CRDs.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Is there a plan to remove LatencySensitive over time? Since it is an alias for Default at this point I would expect us to try and move clusters away from it so we don't have to have patches/maintenance like this

**Comment by dgrisonnet** [comment]
I think there is although I don't know much about the context. @wking might have more info.

My intent with this PR is to make sure that OCP users that have the LatencySensitive FeatureSet enabled in 4.13+ still have access to the newest features.

But if we think that we should just move away from that FeatureSet as whole, I am with. However, we will have to find a way to backport whatever we come up with down to 4.13.

Also CCing David since I saw that he was involved in a lot of discussions around that FeatureSet in the past year.
/cc @deads2k

**Comment by JoelSpeed** [comment]
My suggestion is that we create, in some operator, an upgrade blocker that prevents `LatencySensitive` from being upgraded. With an instruction to change the feature set back to empty. This makes it a conscious effort on the user side to change the value, they are aware that the change has happened and that they are now back to the default feature set. We can link to a KCS to explain further detail as well.

I'm not sure how many clusters are impacted, or if that will cause frustration, but it feels like a good/explicit way of handling the issue.

Once we have that in place, we can start removing the feature set

**Comment by JoelSpeed** [comment]
If we backport https://github.com/openshift/cluster-config-operator/pull/324, I don't think we need this, right?

**Comment by dgrisonnet** [comment]
We won't. We can tell 4.13 users to upgrade to the most recent patch version if they encounter the bug.

/close

**Pull request closed without merging**
