### PR TITLE
remove the service catalog crds

### PR DESCRIPTION
**Pull request by jmrodri**
We are removing service catalog in OpenShift 4.5. We don't need the
CRDs. We are leaving the go types until 4.6.

### CODE REVIEW

**Comment by jmrodri** [comment]
@soltysh @shawn-hurley this is what we discussed via email

**Comment by deads2k** [comment]
Can you link to the code in the 4.4 service-catalog operator that goes upgradeable==false if the operator is in managed state?

/hold

**Comment by soltysh** [comment]
For reference release notes deprecating this functionality in 4.1 https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-notable-technical-changes

**Comment by jmrodri** [comment]
@deads2k thanks for that reminder, it looks like it didn't get into 4.4 to set Upgradeable to False. I have two PRs up to add that:
cluster-svcat-apiserver-operator: https://github.com/openshift/cluster-svcat-apiserver-operator/pull/78
cluster-svcat-controller-manager-operator: https://github.com/openshift/cluster-svcat-controller-manager-operator/pull/72

**Comment by jmrodri** [comment]
The PRs in this comment have merged: https://github.com/openshift/api/pull/596#issuecomment-598714872

**Pull request merged**
