### PR TITLE
Bug 1880786: operatorcontrolplane: make structural

### PR DESCRIPTION
**Pull request by sttts**
As v1beta1 CRD without `preserveUnknownFields: false` the CRD was not structural and hence `oc explain` did not work.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
@damemi how this slipped the `hack/verify-crds.sh`? Looks like we're skipping this dir, we should probably re-visit that script and ensure it's applied to all and those that miss it should have BZs opened.

**Comment by damemi** [comment]
@soltysh this dir was added after we created the hack/verify-crds script, so it should have been added then. Maybe we should add a note to the readme to remind devs to add new groups that need verification to that script

**Comment by sttts** [comment]
Why is it not just looking on all CRDs in all dirs?

**Comment by damemi** [comment]
> Why is it not just looking on all CRDs in all dirs?

I believe there were some exceptions when we added this, or we didn't want to roll it out to force on everyone at the time. We can definitely do that now and see where the failures are and address those.

@sttts @soltysh I opened a PR to try that out here: https://github.com/openshift/api/pull/743

**Pull request merged**
