### PR TITLE
NE-1084: Add additional cache ttl time units

### PR DESCRIPTION
**Pull request by brandisher**
* Adds additional time units to DNSCache to avoid time serialization/deserialization issues like those in https://issues.redhat.com/browse/OCPBUGS-236
* Adds a note about the behavior of fractional second units and units less than `1s`.

### CODE REVIEW

**Comment by jerpeter1** [comment]
As this is an API PR, docs & px engagement isn't really needed yet.

/label docs-approved
/label px-approved

**Comment by Miciah** [comment]
For cross-referencing purposes, I'll note that this is a follow-up for <https://github.com/openshift/api/pull/1214>.

**Pull request merged**
