### PR TITLE
Add v1 service-ca operator config

### PR DESCRIPTION
**Pull request by mrogers950**
/cc @openshift/sig-auth @openshift/api-reviewers

### CODE REVIEW

**Comment by ericavonb** [comment]
Do we need this configuration? There's one set of keys used in the three controllers.  Why do they need to be configurable separately? If the CA injected into configmaps and apiservices doesn't match the signing key used to supply certs to services, things will break.

Then I'm not sure we need to let where the certs are mounted into the service-ca pods, or which secret/configmaps, be configurable (beyond configuring it on the deployment itself).

I'm not sure what we're gaining with the extra complexity that can't handled by the CVO or controllers themselves. @smarterclayton am I missing something that makes this bundling layer necessary?

**Comment by mrogers950** [comment]
@ericavonb The service-ca operator will be the only thing managing these individual controllers configs and deployments, we won't be exposing this in a top level config (trying to change the values would get stomped on). They are uniform but separate basically because of the current structure of the operator, and this does not add any additional complexity as the operator already expects this layout (compare with servicecertsigner/v1alpha1). I agree there is redundant information but for the purpose of renaming the operator this is all we need.

**Comment by enj** [comment]
Note that only the ServiceCA struct is an actual CR.  The others are the CLI configs of the controllers (otherwise the operator has no way to configure the controllers).  I suppose those could could be in a different group.  @deads2k what is the expectation on the location of the CLI configs?

The operator CR is required to control the standard functionality of the operator.  The 3 overrides allow the user to mess with the CLI configs of the controllers in the same manner as the unsupported config overrides code.  All of this is existing API with a simple rename.

**Comment by ericavonb** [comment]
@enj we don't need to worry about CLI config in the same way anymore. Those can be defined and managed within the operator repo, since it's the only place that deals with it directly.

**Comment by enj** [comment]
Just as the kube API server CLI config lives in this repo, I expect these and our other CLI configs to live here.  We are allowed great flexibly in changing them, but that does not mean we can skip the API review process.

**Comment by deads2k** [comment]
I would suggest `serviceca.authentication.openshift.io`. Since no user would be supported in directly changing these, I don't see a need for them to be in openshift/api.

/close

**Comment by deads2k** [comment]
> I would suggest `serviceca.authentication.openshift.io`. Since no user would be supported in directly changing these, I don't see a need for them to be in openshift/api.

The binary config types.  Your operator config type that is served can live here.

**Pull request closed without merging**
