### PR TITLE
create the IBMCLoudPlatform type for the ingress operator

### PR DESCRIPTION
**Pull request by AndreaM12345**
- package: github.com/openshift/api
  repo:    https://github.com/AndreaM12345/api.git
  version: "ibm-ingress"

### CODE REVIEW

**Comment by ironcladlou** [comment]
@AndreaM12345 Adding a new platform type is something that affects the entire product and probably won't happen outside the context of a major version release. (The constants for existing platforms are [here](https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go#L70).

@openshift/installer what's the guidance for how contributors can propose new platform types?

**Comment by ironcladlou** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
this will be needed to support IBM ROKS deployment.

**Comment by derekwaynecarr** [comment]
@AndreaM12345 can we document what we would like to see for PlatformStatus?

for AWS, we make it visible inside the cluster what region we are running:
https://github.com/openshift/api/blame/master/config/v1/types_infrastructure.go#L139

for GCP, we let the cluster know the project and region:
https://github.com/openshift/api/blame/master/config/v1/types_infrastructure.go#L156

and for Azure the resource group:
https://github.com/openshift/api/blame/master/config/v1/types_infrastructure.go#L145

For IBM ROKs, I think it would be useful to know location, resource group name, and provider (classic, vpc-classic, etc.) since operators may work differently based on provider.

Agree?

**Comment by csrwng** [comment]
@derekwaynecarr @AndreaM12345 is the intent to add support for IBM public cloud to the Ingress operator? An option I’d suggested before was to use an add-on operator to support IBM public cloud while letting the default Ingress operator simply deploy the router pods (as in the bare metal case). Have we discarded that option?

**Comment by derekwaynecarr** [comment]
@csrwng ingress operator and storage are both the target use cases.

**Comment by csrwng** [comment]
@AndreaM12345 you need to run hack/update-* scripts to update generated artifacts, otherwise you'll keep failing verification.

**Comment by AndreaM12345** [comment]
created https://github.com/openshift/api/pull/557 as this PR seems to be pulling in lots of different files due to rebasing.   Looks like https://github.com/openshift/api/pull/557 is more clear as to what the changes are

**Comment by soltysh** [comment]
Replaced by #557.

**Pull request closed without merging**
