### PR TITLE
BUg 2041940: Fix enablePortPoolsPrepopulation setting definition

### PR DESCRIPTION
**Pull request by MaysaMacedo**
As part of the work to reduce OpenStack resource usage[1]
the Namespace is only now handled when a Pod on Pods
Network is created in it. This new behavior also affects when
the ports pool prepopulation happens requiring update to
the docs.

[1] https://issues.redhat.com/browse/OSASINFRA-2590

### CODE REVIEW

**Comment by dulek** [comment]
/lgtm

Looks good from engineering perspective.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
