### PR TITLE
operator/ingress: change default publishing strategy for unknown platforms

### PR DESCRIPTION
**Pull request by ironcladlou**
Before, the `Private` endpoint publishing strategy was the default for the
`None` infrastructure.config.openshift.io platform type. Now, `HostNetwork` is
the default for the `None` platform. This is expected to be more generally
useful.

As suggested by @abhinavdahiya.

@openshift/sig-network-edge @smarterclayton

### CODE REVIEW

**Comment by ironcladlou** [comment]
@derekwaynecarr rebased, PTAL

**Comment by abhinavdahiya** [comment]
ping @derekwaynecarr @ironcladlou

**Comment by smarterclayton** [comment]
Would prefer it to be NodePorts once we have that, but for now this is fine.

/lgtm
/approve

**Pull request merged**
