### PR TITLE
R.I.P. Policy Objects

### PR DESCRIPTION
**Pull request by simo5**
kill policy objects for good

### CODE REVIEW

**Comment by simo5** [comment]
/hold
@enj PTAL

**Comment by deads2k** [comment]
Rebase is in progress.  We can merge this after the first set of bumps is done. 

@simo5 Can you open a  pull removing references in origin so that this bump will go easier?

**Comment by simo5** [comment]
@deads2k already in progress here: https://github.com/openshift/origin/pull/19683

**Comment by deads2k** [comment]
kicking travis

**Comment by deads2k** [comment]
/hold cancel

The downstream merged.  This should be ok for most people to manage the vendor ok.  I plan to merge on green.

/lgtm

**Pull request merged**
