### PR TITLE
Add an informational message about schema validation failures

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
this is going to be messier than i hoped because the scripts all exit on error(as set in init.sh which everything includes, so we can't even use a temporary `set +e` to turn off the exit on error behavior).

so the right fix needs to:
1) trap the exit signal
2) figure out the exit code (this is the part i don't have an answer for at the moment)
3) print the message if the exit code is non-zero

Alternatively the lazy approach would be to just always print the message even if the job doesn't fail, since no one is going to look at the output for successes anyway (And the message can make it clear it's not relevant to successes)

**Comment by bparees** [comment]
@deads2k @JoelSpeed something for when you have a chance to come up for air.

**Comment by bparees** [comment]
@deads2k @JoelSpeed bump

**Comment by JoelSpeed** [comment]
/lgtm 

I think there are some cases where I've seen we've asked to fix them (where they are minor), but in general this is true.

I think the API approver will be the one to override anyway so they'll understand when to override and when not to

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-ovn 
/override ci/prow/e2e-aws-ovn-techpreview 
/override ci/prow/e2e-upgrade

We do not need E2E for this change

**Pull request merged**
