### PR TITLE
Update dependencies in tests module

### PR DESCRIPTION
**Pull request by JoelSpeed**
This updates the tests module to start running the integration tests against a Kube 1.26 API server.

I've also taken the opportunity to bump a bunch of different dependencies to 1.26 and others to their latest versions as well

### CODE REVIEW

**Comment by JoelSpeed** [comment]
BInaries for linux haven't been published for some reason, only darwin binaries are up, looking into it

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
