### PR TITLE
Bug 1788775: Add ConsoleYAMLSample for console config

### PR DESCRIPTION
**Pull request by rhamilto**
Per @benjaminapetersen, putting this here so it lives alongside the [console config CRD](https://github.com/openshift/api/blob/e7fa4b871a25985ef0cc36c2fbd9f2cb4445dc9c/config/v1/0000_10_config-operator_01_console.crd.yaml).

cc: @spadgett

### CODE REVIEW

**Comment by deads2k** [comment]
We haven't added these in the past.  Where will this be exposed in a cluster and how will it be tested?

**Comment by benjaminapetersen** [comment]
@deads2k the CRD is here:
- https://github.com/openshift/api/blob/master/console/v1/0000_10_consoleyamlsample.crd.yaml
It is installed via the console-operator here, along with its other manifests:
- https://github.com/openshift/console-operator/blob/master/Dockerfile

It was stated that all top level configs should have an `exampleYAML`.  It makes some sense that these would exist next to the original resource, though I am open to alternatives.

Testing is a good question.  It would be unfortunate if there was drift over time.

**Comment by spadgett** [comment]
This is only useful if we're providing a YAML snippet since users are never creating new `Console` config resources themselves. This example in the PR will only appear when creating a new `Console` config. Snippets on the other hand will show up when editing the existing config.

The only thing we might be able to add is a snippet for `logoutRedirect`.

**Comment by benjaminapetersen** [comment]
Yes, whats valuable to show is definitely part of the discussion.  Other resources have a lot more to the top level config.

**Comment by rhamilto** [comment]
Closing per @spadgett's [comment](https://github.com/openshift/api/pull/581#issuecomment-580773356).

**Pull request closed without merging**
