### PR TITLE
MON-3971: Remove MetricsServer feature gate

### PR DESCRIPTION
**Pull request by slashpai**
cluster-monitoring-operator now by default installs and configures metrics-server and it doesn't need
to be behind feature gate anymore.

### CODE REVIEW

**Comment by machine424** [comment]
Thanks!

Maybe we should also clean it in [payload-command/render/renderassets/rendered_manifests_test.go](https://github.com/openshift/api/blob/d6942fb7294e5dea4c617bfcb26e5936dc267481/payload-command/render/renderassets/rendered_manifests_test.go#L108)?

/hold
Let's wait for https://github.com/openshift/api/pull/1780 to set the pace as there are still discussions around "featuregates removing" https://github.com/openshift/api/pull/1780#issuecomment-1993986689

**Comment by machine424** [comment]
FYI https://github.com/openshift/api/pull/1780 was merged.
Reading the latest discussions, I think we should wait until version 4.19 to merge this one.

**Comment by JoelSpeed** [comment]
Feature was promoted to GA 4 months ago in 4.17

/lgtm

**Comment by slashpai** [comment]
@JoelSpeed could you please review again, rebased the branch

**Pull request merged**
