### PR TITLE
CONSOLE-3652: Enable ConsolePlugin v1 CRD storage

### PR DESCRIPTION
**Pull request by jhadvig**
Addressing https://issues.redhat.com/browse/CONSOLE-3652

/assign @JoelSpeed 

cc'ing @spadgett

### CODE REVIEW

**Comment by JoelSpeed** [comment]
To migrate to the new version, I think we will need to do something along the lines of [what is described here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version)

CC @deads2k will need your input here

**Comment by deads2k** [comment]
We install the storage version migrator.  Once the the storage version is updated in the CRD manifest, creating a `StorageVersionMigration` will do the work.

**Comment by jhadvig** [comment]
@deads2k should the `StorageVersionMigration` be created by console-operator ?

**Comment by JoelSpeed** [comment]
The [user-guide](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/master/USER_GUIDE.md) suggests that it should be automatic if the storage-version-migrator is installed, there's a trigger controller monitoring for CRDs that have changed the storage version

**Comment by XiyunZhao** [comment]
@jhadvig Will this PR be ready for 4.14?

**Comment by JoelSpeed** [comment]
This change appears to be valid, but we will need a `StorageVersionMigrator` CRD to be added to the payload in the same release to instruct the kube-storage-version-migrator to perform the migration. @jhadvig Can you link to a PR in the console operator repo that adds this SVM and then we can merge this, and then the SVM with a vendor update, in quick succession

**Comment by jhadvig** [comment]
after testing the change with additional change on the console-operator the storage value is set correctly for `v1`.
Screenshot 2023-11-28 at 15 11 33

@JoelSpeed PTAL

**Comment by JoelSpeed** [comment]
IIUC, storage version migration should only need to execute once per cluster. Once the storage version is moved by the CVO, any object written to either API will be converted to v1 and stored as v1. By running the migration, we read and write all resources meaning there should then be no further v1lalpha1 stored console plugins.

@jhadvig Are you confident that the StorageVersionMigration will be created after the CRD storage versions have been moved across? Can you show CVO logs that show it updates the CRD before the SVM is created?

**Comment by jhadvig** [comment]
@JoelSpeed based on the CVO logs the CRD is submitted first and then the migration happens
```
I1128 13:46:31.892207 1 sync_worker.go:975] Running sync for customresourcedefinition "consoleplugins.console.openshift.io" (582 of 870)
....
I1128 13:46:39.279002 1 sync_worker.go:975] Running sync for storageversionmigration "console-plugin-storage-version-migration" (791 of 870)
```

Should be good then 👍

**Comment by jhadvig** [comment]
```
time="2023-11-28T18:21:27Z" level=info msg="resulting interval message" message="{Unhealthy  Readiness probe failed: HTTP probe failed with statuscode: 503 map[interesting:true reason:Unhealthy]}"
time="2023-11-28T18:21:27Z" level=info msg="processed event" event="{{ } {monitoring-plugin-5bfb879b9d-lscdr.179bdc76e1a4ade8  openshift-monitoring  1c9e253c-5f86-44f6-986f-54c66f60ef2e 49839 0 2023-11-28 18:21:27 +0000 UTC <nil> <nil> map[] map[monitor.openshift.io/observed-recreation-count:0 monitor.openshift.io/observed-update-count:1] [] [] [{kubelet Update v1 2023-11-28 18:21:27 +0000 UTC FieldsV1 {\"f:count\":{},\"f:firstTimestamp\":{},\"f:involvedObject\":{},\"f:lastTimestamp\":{},\"f:message\":{},\"f:reason\":{},\"f:reportingComponent\":{},\"f:reportingInstance\":{},\"f:source\":{\"f:component\":{},\"f:host\":{}},\"f:type\":{}} }]} {Pod openshift-monitoring monitoring-plugin-5bfb879b9d-lscdr a2143740-9585-4cf8-8a1c-63ef27fe3cda v1 49545 } FailedMount MountVolume.SetUp failed for volume \"monitoring-plugin-cert\" : failed to sync secret cache: timed out waiting for the condition {kubelet ip-10-0-127-188.us-east-2.compute.internal} 2023-11-28 18:21:27 +0000 UTC 2023-11-28 18:21:27 +0000 UTC 1 Warning 0001-01-01 00:00:00 +0000 UTC nil  nil kubelet ip-10-0-127-188.us-east-2.compute.internal}"
time="2023-11-28T18:21:27Z" level=info msg="resulting interval locator" locator="{Kind map[hmsg:0f619fd03e namespace:openshift-monitoring node:ip-10-0-127-188.us-east-2.compute.internal pod:monitoring-plugin-5bfb879b9d-lscdr]}"
time="2023-11-28T18:21:27Z" level=info msg="resulting interval message" message="{FailedMount  MountVolume.SetUp failed for volume \"monitoring-plugin-cert\" : failed to sync secret cache: timed out waiting for the condition map[reason:FailedMount]}"
```

Having a hard time to understand what happening here due to the change.

**Comment by wking** [comment]
I've filed [OCPBUGS-24057](https://issues.redhat.com/browse/OCPBUGS-24057) to let the `storage` folks know about their `Progressing` `reason` churn.  It seems unrelated to this pull request.

/retest-required

**Comment by JoelSpeed** [comment]
I've manually verified this change in combination with the storage version migration, and this is a low risk change so I'm going to allow merging this even though it's very late in the release cycle. @jhadvig please let me know if your operator PR doesn't merge as we should revert this out of 4.15 if it doesn't.

/lgtm

**Pull request merged**
