### PR TITLE
STOR-1823: Remove CSIDriverSharedResource feature gate

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1823

/hold for https://github.com/openshift/cluster-storage-operator/pull/509

/cc @openshift/storage @adambkaplan @sayan-biswas

### CODE REVIEW

**Comment by jsafrane** [comment]
lgtm from storage POV
/hold
for https://github.com/openshift/origin/pull/29130 to be merged first

**Comment by dobsonj** [comment]
/unhold
https://github.com/openshift/cluster-storage-operator/pull/509 merged so we can remove this featuregate any time.

**Pull request merged**
