### PR TITLE
Minor wording adjustments

### PR DESCRIPTION
**Pull request by bergerhoffer**
Updates after a request to review text from #681.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sttts @tkashem Just a few minor adjustments after reviewing. I added a few line breaks that should probably be tested for however you consume/display the text. Let me know if you want me to make any changes to this PR, thanks!

**Comment by sttts** [comment]
Looks good.

@bergerhoffer can you rerun the OpenAPI generation? Looks like it's out of sync with the latest changes.

**Comment by bergerhoffer** [comment]
Thanks @sttts I ran `make update-codegen-crds`. I did manually update the `config/v1/zz_generated.swagger_doc_generated.go` file, so let me know if there was something else I should have ran for that instead of a manual update.

**Comment by sttts** [comment]
There is also some make target to update `config/v1/zz_generated.swagger_doc_generated.go`. Shouldn't need manual changes.

**Comment by bergerhoffer** [comment]
@sttts If you let me know what that target is, I can run it and update the PR. Here's the list of update* ones:

```
update
update-codegen-crds
update-codegen-crds-authorization
update-codegen-crds-config
update-codegen-crds-console
update-codegen-crds-imageregistry
update-codegen-crds-network
update-codegen-crds-operator
update-codegen-crds-operator-alpha
update-codegen-crds-operatorcontrolplane
update-codegen-crds-operatoringress
update-codegen-crds-quota
update-codegen-crds-samples
update-codegen-crds-security
update-deps-overrides
update-generated
update-gofmt
update-scripts
```

**Pull request merged**
