### PR TITLE
API-1509: Add aesgcm to EncryptionConfig

### PR DESCRIPTION
**Pull request by dgrisonnet**
This PR reverts https://github.com/openshift/api/pull/1413 that incorrectly added `aesgcm` as a techpreview feature when this feature is targeting GA this release: https://issues.redhat.com/browse/API-1509

### CODE REVIEW

**Comment by deads2k** [comment]
Have the implementation and tests passed?  Once they are in and passing, promoting to GA is appropriate and can be done in the same release

**Comment by deads2k** [comment]
explicitly placing a 

/hold

so there isn't an accident.  The implementation should merge as it is under techpreview, prove itself working across the three components, and then we can promote.

**Comment by dgrisonnet** [comment]
Implementations have been merged in 4.13:
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/1458
- https://github.com/openshift/cluster-authentication-operator/pull/598
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/521

E2E tests have also passed and been merged in cluster-kube-apiserver-operator as part of: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1458.

I am planning to add these new tests to the other operators as a follow up, but it would be great if we could get this PR merged beforehand since having the API as techpreview currently requires the CI jobs to run in special tech-preview environment.

**Comment by dgrisonnet** [comment]
Closing in favor of https://github.com/openshift/api/pull/1419

**Pull request closed without merging**
