### PR TITLE
Bug 1957261: BuildConfigStatus.ImageChangeTriggers godoc cleanup

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan 
/assign @rolfedh 

Here is my pass at addressing your respective godoc comments that came in too late before https://github.com/openshift/api/pull/882 merged

FYI some of the detail that was requested to be pruned did stem from trying to address questions from others earlier during the review ... please see earlier review iterations in https://github.com/openshift/api/pull/882 if you need to full context.

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]

**Comment by gabemontero** [comment]
bump @adambkaplan 

you happy with these last triggered image ID godoc changes?

**Review by adambkaplan — APPROVED** [review]
/lgtm

Do we need a BZ to get this merged?

**Comment by gabemontero** [comment]
> /lgtm
> 
> Do we need a BZ to get this merged?

yep if we want this in 4.8

gonna 

/assign @deads2k 

David - @adambkaplan wanted to simplify some of the godoc I added for our new `BuildConfigStatus.ImageChangeTriggers` related fields that you and I iterated on with https://github.com/openshift/api/pull/882

Are you OK with these simplifications?

**Comment by gabemontero** [comment]
> /approve

thanks @deads2k 

I'll open a bz to get this in here and then track the additional changes needed so that an `oc explain` picks up the new godoc

**Pull request merged**
