### PR TITLE
OCPBUGS-21029: Revert "Console CRDs: Rename files to use the default run-level for updates"

### PR DESCRIPTION
**Pull request by wking**
This reverts commit 9e3e820a70e4b80c3ae2828d644eb68005fb6c64, #1541

The consuming console code (openshift/console-operator#782) did not land until after 4.14 forked off:

```console
console-operator $ git log --oneline origin/release-4.14 | grep 'manifests: Shift the ClusterOperator to 95'
...no hits...
console-operator $ git log --oneline origin/release-4.15 | grep 'manifests: Shift the ClusterOperator to 95'
535d021b9 manifests: Shift the ClusterOperator to 95
```

We don't want to make this API-side bump without the associated console-side changes, and removing both from 4.14 in this revert is the least-disruptive way to re-align.

### CODE REVIEW

**Comment by wking** [comment]
[verify-crd-schema][1]:

```
error running generator schemacheck on group console.openshift.io: 
	could not run schemacheck generator for group/version console.openshift.io/v1: 
		error in 0000_10_consolelink.crd.yaml: NoMaps: crd/consolelinks.console.openshift.io version/v1 field/^.spec.namespaceDashboard.namespaceSelector.matchLabels may not be a map
		error in 0000_10_consoleplugin.crd.yaml: NoBools: crd/consoleplugins.console.openshift.io version/v1alpha1 field/^.spec.proxy[*].authorize may not be a boolean
		error in 0000_10_consoleyamlsample.crd.yaml: NoBools: crd/consoleyamlsamples.console.openshift.io version/v1 field/^.spec.snippet may not be a boolean
	could not run schemacheck generator for group/version console.openshift.io/v1alpha1: 
		error in 0000_10_consoleplugin.crd.yaml: NoBools: crd/consoleplugins.console.openshift.io version/v1alpha1 field/^.spec.proxy[*].authorize may not be a boolean
```

So that will need a "this is just a revert of a rename" `/override ci/prow/verify-crd-schema` from a root approver to unblock this pull.

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/1762/pull-ci-openshift-api-release-4.14-verify-crd-schema/1755722983550226432#1:build-log.txt%3A1128-1134

**Review by jhadvig — APPROVED** [review]

**Pull request merged**
