### PR TITLE
add AttentionRecommended condition for ClusterOperator Status for potent…

### PR DESCRIPTION
**Pull request by gabemontero**
…ial errors around mirroring or proxying

Stemming from a discussion between myself, @smarterclayton , @bparees , and @jwforres around access to external resources in a disconnected environment, per executive order from @smarterclayton (his words, not mine :-) ) a new condition is to be added

See https://docs.google.com/document/d/1LopVzuX2nPVlS4IHkOsUNBuVOeAdkBQ92wkaVB2kTwU/edit# for some additional notes

@derekwaynecarr @adambkaplan fyi since y'all could not make the meeting

PTAL everyone

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero i fixed the PR title but the commit text doesn't match the actual name of the constant you're adding.

(maybe it's not worth fixing that until we get feedback from others on whether they are happy w/ this constant name)

anyway i'm happy with this name but clearly we need some more feedback

**Comment by gabemontero** [comment]
@bparees I followed the same pattern as the existing constants wrt name and associated comment ... they all have that discrepancy

I did not feel confident enough to correct it for all of them, but can if there is a consensus to do so.

**Comment by gabemontero** [comment]
sorry you were talking about commit and PR title, not constant and comment

**Comment by gabemontero** [comment]
commit now in line with PR title

**Comment by smarterclayton** [comment]
/hold

Let's do 3 days of discussion and feedback in the doc, with input from Ben's teams, Michal's teams, Alex's teams, and at least 2 release architects

Let's do name discussions in the doc

**Comment by mfojtik** [comment]
Based on discussion with Clayton, wouldn't be better to use `ActionsRequired` ? Attention means that the human operator must take action to fix problem the machine operator can't fix itself. For example, samples operator is broken because it can't fetch image streams unless you set proxy. The ActionsRequired will be then `[{"severity":"urgent", "reason": "UnableToImportImages", "message": "unable to import images unless the proxy setting is specified"}]`.

The list might make more sense if you have multiple actions required. The severity makes sense if you want to convert these into prometheus metrics and create alerts.

I think eventually we might suggests config name and field JSON patch maybe so web console can take the human operator to exact place where he can correct the problem.

**Comment by bparees** [comment]
> Based on discussion with Clayton, wouldn't be better to use ActionsRequired ?

please take this feedback to the doc and we can discuss there

**Comment by bparees** [comment]
(the doc also discusses why your proposal probably doesn't work for what we need to cover)

**Comment by gabemontero** [comment]
Per email from @bparees last week closing this out.

I'll start updating cluster-samples-operator to implement the proposal from @bparees and @smarterclayton

**Comment by smarterclayton** [comment]
We should update the cvo conditions design doc to include the decision

On Jul 14, 2019, at 3:05 PM, Gabe Montero <notifications@github.com> wrote:

Per email from @bparees <https://github.com/bparees> last week closing this
out.

I'll start updating cluster-samples-operator to implement the proposal from
@bparees <https://github.com/bparees> and @smarterclayton
<https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/api/pull/355?email_source=notifications&email_token=AAI37J6HB5E3OZWFL7VFKALP7N2JLA5CNFSM4H3KK4YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ4LLXA#issuecomment-511227356>,
or mute the thread

**Comment by bparees** [comment]
> We should update the cvo conditions design doc to include the decision

@smarterclayton do you mean my doc, or something else?

**Pull request closed without merging**
