### PR TITLE
IR-91: Add Azure cloudName to imageregistry config

### PR DESCRIPTION
**Pull request by dmage**
Add .spec.storage.azure.cloudName to configs.imageregistry.operator.openshift.io. This field will be used by the operator to bootstrap storage and propagated to the registry.

See openshift/api#650.

### CODE REVIEW

**Comment by dmage** [comment]
I'm not sure if `protobuf:"..."` is needed for this field. For some reason other fields have such annotation, but it's CRD and AFAIK protobuf cannot be used for CRDs

**Comment by bparees** [comment]
/hold

> I'm not sure if protobuf:"..." is needed for this field. For some reason other fields have such annotation, but it's CRD and AFAIK protobuf cannot be used for CRDs

@mfojtik @sttts @deads2k do one of you know what should be done here?

**Comment by sttts** [comment]
It's not needed. Instead of making it non-uniform here, remove all of the protobuf lines.

**Comment by dmage** [comment]
@sttts protobuf tags are removed, ptal

**Pull request merged**
