### PR TITLE
OCPNODE-2333: add imagepolicy to payload crds

### PR DESCRIPTION
**Pull request by QiWang19**
cooperate PR for https://github.com/openshift/machine-config-operator/pull/4587

### CODE REVIEW

**Comment by QiWang19** [comment]
/hold
hold for https://github.com/openshift/machine-config-operator/pull/4587

**Comment by JoelSpeed** [comment]
If the CRDs are not presently being added to payload in the MCO repo, then this can merge first, but I notice your PR is also including these in the install dir for MCO, so, it looks like they possibly need to be removed from the install dir so that they aren't introduced into payload twice?

**Comment by wking** [comment]
I agree with Joel that [the MCO pull should drop its copies of these CRDs][1].  And with that change, I don't see a reason why we can't lift the hold here and land these now.  Although I guess you don't want too much space in between this landing and the MCO pull landing, to avoid too many rounds of clusters that have the CRDs in place (via `payload-manifests/crds` here and the API image) without having a controller in place (via the MCO pull).  During that transition period, anyone tetsting the tech-preview types might be surprised to have no controller delivering the `spec` ask.

[1]: https://github.com/openshift/machine-config-operator/pull/4587#discussion_r1779341025

**Comment by QiWang19** [comment]
The manifests were dropped from MCO PR https://github.com/openshift/machine-config-operator/pull/4587

**Comment by QiWang19** [comment]
@JoelSpeed @wking @mtrmac PTAL.

**Review by wking — APPROVED** [review]
Looks good to me.  [e2e-aws-serial-techpreview failing on cluster-bootstrap][1] is slightly concerning, but poking around there, I'm not seeing a clear signal for what's going wrong, and [e2e-aws-ovn-techpreview passed][2], so seems unlikely that it's "this change breaks TechPreview!" or anything like that.

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/2036/pull-ci-openshift-api-master-e2e-aws-serial-techpreview/1841850190038831104
[2]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/2036/pull-ci-openshift-api-master-e2e-aws-ovn-techpreview/1841850189913001984

**Comment by JoelSpeed** [comment]
/lgtm

/hold

Release the hold when you're ready, the serial techpreview is an unrelated flake

**Comment by JoelSpeed** [comment]
/retest 

unrelated MCO failure

**Pull request merged**
