### PR TITLE
SPLAT-1097: IBMCloud: Add IBM Cloud Service names

### PR DESCRIPTION
**Pull request by cjschaef**
Add a new enum and values for IBM Cloud Service names.

Related: https://issues.redhat.com/browse/SPLAT-1097

### CODE REVIEW

**Comment by cjschaef** [comment]
Should I also change the `IBMCloudServiceEndpoint.Name` to be this enum now, instead of simply a string, perhaps refactoring the type completely?
https://github.com/openshift/api/blob/e54cd96d167c7da4e13b8c029ac0369a45ee2a4d/config/v1/types_infrastructure.go#L1193

We would prefer to keep the structure more flexible, if possible, like it manly is now.

**Comment by jeffnowicki** [comment]
> Should I also change the `IBMCloudServiceEndpoint.Name` to be this enum now, instead of simply a string, perhaps refactoring the type completely?
> 
> https://github.com/openshift/api/blob/e54cd96d167c7da4e13b8c029ac0369a45ee2a4d/config/v1/types_infrastructure.go#L1193
> 
> We would prefer to keep the structure more flexible, if possible, like it manly is now.

I agree Chris.

**Comment by JoelSpeed** [comment]
> Should I also change the IBMCloudServiceEndpoint.Name to be this enum now, instead of simply a string, perhaps refactoring the type completely?

Just change the type of the `Name` field from `string` to the new type. I'd then like you to add a godoc line that says, `Possible values are CIS, COS,...`

**Comment by cjschaef** [comment]
Updated.

Since we changes the `IBMCloudServiceEndpont.Name` type, I don't think the helper functions in `library-go` are necessary any longer. We can use the `IBMCloudServiceName` enum for comparisons as necessary downstream.

**Comment by cjschaef** [comment]
/retitle SPLAT-1097: IBMCloud: Add IBM Cloud Service names

**Comment by JoelSpeed** [comment]
This API was added in https://github.com/openshift/api/pull/1499 which merged during the 4.15 release time frame, therefore the API hasn't hit a release yet. This doesn't change the serialisation of the field but does tighten the validation. Exception to the normal rule of not tightening the validation since this hasn't hit a release yet.

/lgtm

**Pull request merged**
