### PR TITLE
WRKLDS-1449: disable DynamicResourceAllocation in order to upgrade to resource.k8s.io/v1alpha3

### PR DESCRIPTION
**Pull request by atiratree**

### CODE REVIEW

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Comment by atiratree** [comment]
verify-crd-schema error was already present before

```
error in config/v1/zz_generated.featuregated-crd-manifests/schedulers.config.openshift.io/DynamicResourceAllocationSchedulersConfigOnly.yaml: NoBools: crd/schedulers.config.openshift.io version/v1 field/^.spec.mastersSchedulable may not be a boolean
```

**Comment by deads2k** [comment]
/hold

Instead of this please update the kube-apiserver operator to check the version it is installing and enable the correct APIs for the level it is installing.

**Comment by atiratree** [comment]
closing in favor of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1731 and https://github.com/openshift/installer/pull/8973

**Pull request closed without merging**
