### PR TITLE
Bug 1881636: Switch networking CRDs to apiextensions/v1

### PR DESCRIPTION
**Pull request by damemi**
When running CRD validation against all CRDs (https://github.com/openshift/api/pull/743), these 4 fail due to not having a structural schema with pruning enabled. This switch to v1 will be required by k8s 1.22

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/hold
for networking team for final sign-off
@knobunc

**Comment by damemi** [comment]
bump @knobunc could you ptal and remove the hold if this looks good from networking side? Thanks!

**Pull request merged**
