### PR TITLE
Add IntermediateCertFile to ServiceServingCertSignerConfig

### PR DESCRIPTION
**Pull request by marun**
Required by https://github.com/openshift/service-ca-operator/pull/73

cc: @sttts @deads2k

### CODE REVIEW

**Comment by stlaz** [comment]
/hold
I may be wrong but I don't think this is necessary - https://github.com/openshift/service-ca-operator/pull/73#pullrequestreview-303779910

**Comment by marun** [comment]
> /hold
> I may be wrong but this may not be necessary - [openshift/service-ca-operator#73 (comment)](https://github.com/openshift/service-ca-operator/pull/73#discussion_r336450180)

As per [my reply](https://github.com/openshift/service-ca-operator/pull/73#discussion_r336586853), I think this is necessary.

**Comment by marun** [comment]
> /hold
> I may be wrong but this may not be necessary - [openshift/service-ca-operator#73 (comment)](https://github.com/openshift/service-ca-operator/pull/73#discussion_r336450180)

Though I think the change is necessary, thank you for holding. I did not intend this PR to be reviewed until the openshift/service-ca-operator#73 is otherwise ready to be merged.

**Comment by marun** [comment]
Rebased

**Pull request merged**
