### PR TITLE
Build: Clarify that the default value for dockerfilePath is Dockerfile

### PR DESCRIPTION
**Pull request by alvaroaleman**
Inferred from here: https://github.com/openshift/builder/blob/29a32e529226698ae82ea0b8ddaeff5e4c7b79bb/pkg/build/builder/docker.go#L371

### CODE REVIEW

**Comment by bparees** [comment]
@alvaroaleman needs generated code updates (sorry not sure what the make target/script is offhand):

```
diff -Naupr -I 'Auto generated by' -x 'zz_generated.*' -x 'types_swagger*' hack/../build/v1/generated.proto hack/../_tmp/build/v1/generated.proto
--- hack/../build/v1/generated.proto	2020-08-17 17:47:14.046716635 +0000
+++ hack/../_tmp/build/v1/generated.proto	2020-08-17 17:41:15.000000000 +0000
@@ -687,7 +687,6 @@ message DockerBuildStrategy {
 
   // dockerfilePath is the path of the Dockerfile that will be used to build the container image,
   // relative to the root of the context (contextDir).
-  // Defaults to `Dockerfile` if unset.
   optional string dockerfilePath = 6;
 
   // buildArgs contains build arguments that will be resolved in the Dockerfile.  See
+ ret=1
```

/approve

**Comment by alvaroaleman** [comment]
@bparees updated, PTAL

**Pull request merged**
