### PR TITLE
Change to NutanixMachineProviderConfig to allow to configure one or more subnets for a Machine VM

### PR DESCRIPTION
**Pull request by yanhua121**
Change to NutanixMachineProviderConfig to allow to configure one or more subnets for a Machine VM.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Is there a limitation on the maximum number of subnets that might be attached to a Machine?
Are there any implications to the end user if they were to specify more than one subnet?

**Review by elmiko — COMMENTED** [review]
this generally looks good to me
/lgtm

**Comment by yanhua121** [comment]
@JoelSpeed The commits are squashed.

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by deads2k** [comment]
Once we move to streams, you will never be allowed to do this again even in a single release. This breaks serialization compatibility with the existing API.

I don't see this type in 4.10, I think it merged in https://github.com/openshift/api/pull/1124, so this may well break micro upgrades, but I'm willing to try it.

@JoelSpeed this would be a good project for a serialization fuzz test like we have upstream in kube.

/approve

**Comment by elmiko** [comment]
i am adding the other labels as this pr is part of the larger effort to integrate nutanix platform

/docs-approved
/px-approved
/qe-approved

**Comment by elmiko** [comment]
thanks for the explanation @deads2k , we will definitely need to be more thorough in the future before adding api changes.

**Pull request merged**
