### PR TITLE
Bug 1877487: add valid values for ConsoleNotification location

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1877487

### CODE REVIEW

**Comment by rhamilto** [comment]
/bugzilla refresh

cc @spadgett

**Comment by spadgett** [comment]
@rhamilto The CRD is generated from the API here:

https://github.com/openshift/api/blob/master/console/v1/types_console_notification.go#L21-L23

**Comment by spadgett** [comment]
Then you'll need to run `make update-codegen-crds` to generate the CRD.

**Comment by rhamilto** [comment]
Thanks, @spadgett.  Take 2.  Note I was getting changes to `config/v1/0000_10_config-operator_01_build.crd.yaml` and `quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml` when I ran `make update-codegen-crds`, but I did not include those changes in my commit since they are unrelated to my changes and I assume they should not be included.

**Comment by rhamilto** [comment]
I just noticed that `location` is optional, but is actually required.

**Comment by rhamilto** [comment]
> I just noticed that `location` is optional, but is actually required.

Since we can't change the API, I opened https://bugzilla.redhat.com/show_bug.cgi?id=1877858 to address.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/assign @bparees 
for approval

**Review by jhadvig — APPROVED** [review]
Since `console-operator` is [vendoring](https://github.com/openshift/console-operator/blob/master/Dockerfile.rhel7#L16 ) it's CRDs we don't have to do any updated to it's repository.

/lgtm

**Comment by spadgett** [comment]
> Since `console-operator` is [vendoring](Since `console-operator` is ) it's CRDs we don't have to do any updated to it's repository.

@jhadvig Isn't it going to use the CRD manifest here?

https://github.com/openshift/console-operator/blob/master/vendor/github.com/openshift/api/console/v1/0000_10_consolenotification.crd.yaml

https://github.com/openshift/console-operator/blob/master/Dockerfile.rhel7#L16

I'd expect to need to bump openshift/api in the console-operator repo to see the change.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
