### PR TITLE
operator/ingress: remove HostNetwork endpoint publishing strategy

### PR DESCRIPTION
**Pull request by ironcladlou**
Remove the HostNetwork endpoint publishing strategy. It's not yet clear whether
NodePort can replace it, we have no 4.0 use case justification for HostNetwork,
we can add it back if necessary, and we can't take it away once added.

@openshift/sig-network-edge

### CODE REVIEW

**Comment by smarterclayton** [comment]
RHHI needs it to test, what’s their workaround?

**Comment by abhinavdahiya** [comment]
oauth now depends on routes. That means that router is required for all platforms like Libvirt. How is it supposed to work for that case. Libvirt is important for all our dev usecases.

**Comment by ironcladlou** [comment]
Possible workaround: maintain a NodePort service pointing at the ingress controller deployments. (cc @celebdor).

>oauth now depends on routes. That means that router is required for all platforms like Libvirt. How is it supposed to work for that case. Libvirt is important for all our dev usecases.

Would NodePort be sufficient, better, worse for those cases?

Followup: if NodePort is actually preferable for the cases we do care about now, maybe we should implement NodePortService to replace HostNetwork?

**Comment by abhinavdahiya** [comment]
> Possible workaround: maintain a NodePort service pointing at the ingress controller deployments. (cc @celebdor).
> 
> > oauth now depends on routes. That means that router is required for all platforms like Libvirt. How is it supposed to work for that case. Libvirt is important for all our dev usecases.
> 
> Would NodePort be sufficient, better, worse for those cases?
> 
> Followup: if NodePort is actually preferable for the cases we do care about now, maybe we should implement NodePortService to replace HostNetwork?

Libvirt can't use NodePort as there is no load balancer to redirect traffic from the the normal 80/443 to the node port service port.... And I think that's going to be case with RHHI too

**Comment by ironcladlou** [comment]
>Libvirt can't use NodePort as there is no load balancer to redirect traffic from the the normal 80/443 to the node port service port.... And I think that's going to be case with RHHI too

I could have misunderstood, but from talking with @celebdor NodePort was considered preferable to HostNetwork for the RHHI use case. Would like to verify that though

**Comment by celebdor** [comment]
> > Libvirt can't use NodePort as there is no load balancer to redirect traffic from the the normal 80/443 to the node port service port.... And I think that's going to be case with RHHI too
> 
> I could have misunderstood, but from talking with @celebdor NodePort was considered preferable to HostNetwork for the RHHI use case. Would like to verify that though

For NodePort I expected to support it by having a VIP redirecting traffic 80/443 to the nodeport.
For hostnetwork it would be just the VIP, but then the problem is that the traffic always gets to the same router pod (as there is no kube-proxy like there is in nodeport).

**Comment by ironcladlou** [comment]
>For NodePort I expected to support it by having a VIP redirecting traffic 80/443 to the nodeport.
For hostnetwork it would be just the VIP, but then the problem is that the traffic always gets to the same router pod (as there is no kube-proxy like there is in nodeport).

FYI we're deliberately using `externalTrafficPolicy=Local` to prevent east-west router traffic

**Comment by ironcladlou** [comment]
(and for source IP preservation, I believe)

**Comment by ironcladlou** [comment]
@abhinavdahiya would https://metallb.universe.tf provide a foundation for LoadBalancer service to function in libvirt?

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya would https://metallb.universe.tf provide a foundation for LoadBalancer service to function in libvirt?

That's an overkill for libvirt.. libvirt uses RRDNS for all balancing requirements like `api.cluster_domain`. So it is easier to just setup `*.app.cluster_domain` to worker nodes and hit the router directly on host networking.

**Comment by ironcladlou** [comment]
@smarterclayton going to need an executive decision on this one as to what we want to commit at GA.

**Comment by danehans** [comment]
A service of type `NodePort` will use the node(s) IP and a port between 30000-32767 (default range) for external publishing. Unless clients can connect to the service following this pattern, `hostNetworking` for router pods will need to persist or the service must be published as type `LoadBalancer`. MetalLB allows the `LoadBalancer` type to work for bare metal deployments by allocating the service a virtual IP address that can be used for binding standard ports such as 443 for HTTPS.

**Comment by ironcladlou** [comment]
Talked more with @smarterclayton and decided there's enough uncertainty that we should just leave for now.

**Pull request closed without merging**
