### PR TITLE
STOR-1724: Add Samba/CIFS CSI driver provider

### PR DESCRIPTION
**Pull request by mpatlasov**
https://issues.redhat.com/browse/STOR-1724
/cc @openshift/storage

### CODE REVIEW

**Comment by mpatlasov** [comment]
@jsafrane This PR is a copy/pasta of https://github.com/openshift/api/pull/1456 which you lgtm-ed [here](https://github.com/openshift/api/pull/1456#issuecomment-1547659889). Please review

**Comment by jsafrane** [comment]
/lgtm
from storage POV. We plan to ship Samba CSI driver in 4.16 (via OLM, but we re-use ClusterCSIDriver CRD there).

**Comment by mpatlasov** [comment]
/assign @JoelSpeed 
for approval

This feature is going to be similar to [GCP Filestore](https://github.com/openshift/api/blob/83abb00e268469ba4c898c2995ee7f882a35e8a6/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml#L37) and [Secrets Store](https://github.com/openshift/api/blob/release-4.15/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml#L48). This won't be behind a FeatureSet because this is an optional operator that will be deployed via OLM. The admin opts in via OLM instead of changing the FeatureSet to enable this.

**Comment by mpatlasov** [comment]
@jsafrane , @JoelSpeed , please add `lgtm` again (The PR didn't change, I only rebased it)

**Pull request merged**
