### PR TITLE
SPLAT-1851: Make VSphereMultiVCenters feature gate GA

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1851](https://issues.redhat.com//browse/SPLAT-1851)

### Changes
- Promoted VSphereMultiVCenters feature gate to GA (default)

### E2E Test Data:
- This feature gets tested by the [Periodical jobs](https://github.com/openshift/release/blob/09ae0b613da36e3ed3fd95e0bcae55ea235c5be5/ci-operator/config/openshift/release/openshift-release-master__nightly-4.18.yaml#L588)
  - IPI
    - https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-vcenter
    - https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter
  - UPI
    - https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-multi-vcenter
    - https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter
- There isn't an origin E2E test for this feature, so I expect the verify job automation to fail. We will require manual [QE Signoff](https://github.com/openshift/enhancements/blob/master/dev-guide/featuresets.md#obtaining-qe-sign-off)
- Created New pre-submits to help catch issues
  - https://github.com/openshift/release/pull/58794

### CODE REVIEW

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter

**Comment by gnufied** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter

**Comment by duanwei33** [comment]
QE also have CI against vsphere-ipi-multi-vcenter, the storage regression test result looks good. (Although we need a fix in our auto code in some snapshot cases)
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-vsphere-ipi-multi-vcenter-f28
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-vsphere-ipi-multi-vcenter-f28

From the storage part, we are good on the feature.

**Comment by vr4manta** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter 3

**Comment by vr4manta** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter 3

**Comment by vr4manta** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter 6

**Comment by deads2k** [comment]
Updating here so it's in multiple places.  2/3 of attempts using this functionality on [periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.18/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-multi-vcenter%22%7D%5D%7D&sortField=timestamp&sort=desc) have failed this week on PVC related tests.   33% success does not meet our quality bar.  We need to see 95% success prior to merge.

The [IPI jobs](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.18/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-vcenter%22%7D%5D%7D&sortField=timestamp&sort=desc)  are failing on the too many watches and removed API checks.

**Comment by deads2k** [comment]
Jobs are fixed and working except for two identified and unrelated bugs

/approve
/override ci/prow/verify

**Comment by jcpowermac** [comment]
ugh aws serial is taking over 4 hours so failing

/test e2e-aws-serial

**Comment by jsafrane** [comment]
For the record, this PR has broken *single vCenter* vSphere jobs, [e2e-vsphere-operator-test](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-vmware-vsphere-csi-driver-operator-master-e2e-vsphere-operator-test) job in vmware-vsphere-csi-driver-operator repo.

image

Note to storage team: we need a periodic job for e2e-vsphere-operator-test.

**Comment by JoelSpeed** [comment]
@jsafrane Do you understand how it broke? Would be good to have the RCA so that we can try to avoid issues in the future

**Comment by gnufied** [comment]
Yes - https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/276 . It broke tests that disable storage capability from vSphere. Once the feature was turned GA, then it operator started using an interface that didn't had ability to remove storageclasses if users disable storage. So, it started to fail. 

I actually noticed this awhile back - https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/261/commits/eb86108ce549f1c4c9109387240742c1f55ba7bb but then, we chose not to merge that PR because that PR also had code that removes reading of feature-gate. In 4.18 - we decided we are going to keep reading the feature-gate for GA status of multi-VC and hence we will merge #261 in 4.19.

**Pull request merged**
