### PR TITLE
Extend config/v1/scheduler crd with customSchedulerImage field

### PR DESCRIPTION
**Pull request by ingvagabund**
To allow the scheduler operator to set a custom image for the scheduler
in case the default scheduler is not sufficient (e.g. a scheduler framework
built with a custom set of plugins).

/hold

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Thank you for working this @ingvagabund - Should we set the cluster state to unsupported in this case?

**Comment by ingvagabund** [comment]
> Thank you for working this @ingvagabund - Should we set the cluster state to unsupported in this case?

Can we do it? Is there an annotation for that? How is it done?

**Comment by ravisantoshgudimetla** [comment]
> Can we do it? Is there an annotation for that? How is it done?

Not sure about that.

**Pull request closed without merging**
