### PR TITLE
Add models-schema to make clean

### PR DESCRIPTION
**Pull request by soltysh**
/assign @ingvagabund

### CODE REVIEW

**Comment by ingvagabund** [comment]
How does one generate `models-schema` directory?

**Comment by soltysh** [comment]
> How does one generate `models-schema` file?

it's part of `make update` target

**Comment by ingvagabund** [comment]
Worth removing models-schema from https://github.com/openshift/api/blob/master/.gitignore#L19 as well

**Comment by ingvagabund** [comment]
@JoelSpeed is there any significant benefit in keeping `models-schema` directory around?

**Comment by soltysh** [comment]
> @JoelSpeed is there any significant benefit in keeping `models-schema` directory around?

that's not a directory, that's one of the build binaries used during generation



> Worth removing models-schema from https://github.com/openshift/api/blob/master/.gitignore#L19 as well?

Why? It's there to ensure we don't accidentally commit that binary.

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
