### PR TITLE
Machine API: Refactor provider status to use metav1.Condition

### PR DESCRIPTION
**Pull request by RadekManak**
This PR refactors out provider-specific conditions in favour of metav1.Condition type from upstream Kubernetes.

Something that was picked up while the Machine API types were being moved into openshift/api is that we have a bunch of Condition structs that are all identical, we want to consolidate these and just use metav1.Condition instead. From an end-user perspective, there should be no change to the API as a result of this, but it makes our API a bit cleaner

metav1.Condition does not have LastProbeTime field but we believe this change to be safe because the only operators who have write access to these objects are the Machine API providers which are under our control and users/cluster admins don't have access to update these fields, hence there shouldn't be anyone setting the LastProbeTime field.

I have commits ready for all providers that require change.
https://github.com/RadekManak/machine-api-operator/commit/62605c41a01f527eb87195edc5bf41e33821eb3a
https://github.com/RadekManak/machine-api-provider-aws/commit/83efffda6571d28de03c0783ee6f1ed9438fca4b
https://github.com/RadekManak/machine-api-provider-gcp/commit/445538d9c7e2c2d8604e27d31fb12b994fe35d19
https://github.com/RadekManak/machine-api-provider-azure/commit/d917f7113cdc7837580bc7e6f77b1d7e3048ad95

Jira: [OCPCLOUD-1371](https://issues.redhat.com/browse/OCPCLOUD-1371)
Previously discussed here: [#1045](https://github.com/openshift/api/pull/1045/#discussion_r761306395)

### CODE REVIEW

**Comment by JoelSpeed** [comment]
> The only project that is affected by this api change is machine-api-operator for which I have commit ready.

I suspect each of the providers will also need an update as well (MAPA, MAPZ, MAPG)

Do the object serialize in the same way, are the fields within metav1.Condition matching the existing condition types that we have?

**Comment by RadekManak** [comment]
You are right. I tested against cluster-api-provider-* repos instead of machine-api-provider-*.

**Comment by RadekManak** [comment]
The other providers also ready.
https://github.com/RadekManak/machine-api-provider-aws/commit/83efffda6571d28de03c0783ee6f1ed9438fca4b
https://github.com/RadekManak/machine-api-provider-gcp/commit/445538d9c7e2c2d8604e27d31fb12b994fe35d19
https://github.com/RadekManak/machine-api-provider-azure/commit/d917f7113cdc7837580bc7e6f77b1d7e3048ad95

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
As these are API compatible from an end user perspective and the `LastProbeTime` field that is dropped was never actually set by the controllers using these conditions, I think this is ok (while it's technically breaking, users shouldn't have been relying on it as it was never set. This change should be transparent to and API consumer)

**Comment by deads2k** [comment]
> we believe this change to be safe because the only operators who have write access to these objects are the Machine API providers which are under our control and users/cluster admins don't have access to update these fields,

This tightens validation, but status writers are limited to those under our direct control (as distinct from spec).  This means we know that the values we wrote are valid under the new schema.  I'm willing to approve this, *but* if you detect any failure due to validation, you *must* revert this PR, fix the code in 4.11, and try again in 4.12.

/approve

**Comment by JoelSpeed** [comment]
This project is not a part of the no-ff process

/label px-approved
/label qe-approved
/label docs-approved

**Pull request merged**
