### PR TITLE
OCPBUGS-12699: Add additional names to env var allow list

### PR DESCRIPTION
**Pull request by coreydaley**
Adding additional env vars to the whitelist so that we can also set the proxy env vars in lowercase which is required by some well known tools such as CURL. I have also opened https://github.com/openshift/openshift-controller-manager/pull/278 which will automatically set the lowercase env vars along with the uppercase ones.

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @adambkaplan 
Can you please take a look at this and give it an lgtm unless you have questions/concerns?
Then I will assign it to David to get merged.

**Review by adambkaplan — COMMENTED** [review]
Potentially will result in a merge conflict with #1660?

**Comment by coreydaley** [comment]
I will rebase it after #1660 merges, but I wanted to keep them separate

**Comment by adambkaplan** [comment]
/hold

Per Corey's comment, can release once #1660 merges.

**Comment by coreydaley** [comment]
/assign @adambkaplan 
for lgtm

**Comment by coreydaley** [comment]
@adambkaplan bump

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
