### PR TITLE
OCPBUGS-31666: route: Fix insecureEdgeTerminationPolicy default

### PR DESCRIPTION
**Pull request by Miciah**
Fix the godoc for the `spec.tls.insecureEdgeTerminationPolicy` field to say that "None", not "Allow", is the default value.

Also, add a more explicit statement about the default value.

Finally, fix the formatting so that the list displays properly in the output of oc explain.  Before, the output looked like this:

    % oc explain routes.spec.tls.insecureEdgeTerminationPolicy
    KIND:     Route
    VERSION:  route.openshift.io/v1

    FIELD:    insecureEdgeTerminationPolicy <string>

    DESCRIPTION:
         insecureEdgeTerminationPolicy indicates the desired behavior for insecure
         connections to a route. While each router may make its own decisions on
         which ports to expose, this is normally port 80.

         * Allow - traffic is sent to the server on the insecure port
         (edge/reencrypt terminations only) (default). * None - no traffic is
         allowed on the insecure port. * Redirect - clients are redirected to the
         secure port.

After this change, the output looks like this:

    % oc explain routes.spec.tls.insecureEdgeTerminationPolicy
    KIND:     Route
    VERSION:  route.openshift.io/v1

    FIELD:    insecureEdgeTerminationPolicy <string>

    DESCRIPTION:
         insecureEdgeTerminationPolicy indicates the desired behavior for insecure
         connections to a route. While each router may make its own decisions on
         which ports to expose, this is normally port 80. If a route does not
         specify insecureEdgeTerminationPolicy, then the default behavior is "None".
         * Allow - traffic is sent to the server on the insecure port
         (edge/reencrypt terminations only).
         * None - no traffic is allowed on the insecure port (default).
         * Redirect - clients are redirected to the secure port.

### CODE REVIEW

**Comment by ShudiLi** [comment]
It was strange after this change, the output looked as same as before

1. created a cluster by the bot
launch openshift/api#1845 gcp

2.
 % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.0-0.ci.test-2024-04-08-055444-ci-ln-11w2cxk-latest   True        False         11m     Cluster version is 4.16.0-0.ci.test-2024-04-08-055444-ci-ln-11w2cxk-latest

3. the default is Allow
% oc explain routes.spec.tls.insecureEdgeTerminationPolicy
GROUP:      route.openshift.io
KIND:       Route
VERSION:    v1

FIELD: insecureEdgeTerminationPolicy <string>

DESCRIPTION:
    insecureEdgeTerminationPolicy indicates the desired behavior for insecure
    connections to a route. While each router may make its own decisions on
    which ports to expose, this is normally port 80.
    
    * Allow - traffic is sent to the server on the insecure port (edge/reencrypt
    terminations only) (default). * None - no traffic is allowed on the insecure
    port. * Redirect - clients are redirected to the secure port.
    

%

**Comment by deads2k** [comment]
> Fix the godoc for the spec.tls.insecureEdgeTerminationPolicy field to say that "None", not "Allow", is the default value.

I'm taking this to mean that the default isn't changing, we're just fixing the doc.  If I understand correctly, please release the hold at your discretion.

/approve
/hold

**Comment by Miciah** [comment]
> I'm taking this to mean that the default isn't changing, we're just fixing the doc. If I understand correctly, please release the hold at your discretion.

That is correct.  Thanks!

/hold cancel

**Comment by Miciah** [comment]
@frobware, would you mind retagging the PR?

**Comment by frobware** [comment]
> @frobware, would you mind retagging the PR?

/lgtm

**Comment by Miciah** [comment]
https://github.com/openshift/openshift-apiserver/pull/433 bumps openshift/api in openshift-apiserver in order to incorporate the API godoc update from this PR.

**Pull request merged**
