### PR TITLE
SDN-4600: Add NetworkDiagnosticsConfig to the default featureset

### PR DESCRIPTION
**Pull request by kyrtapz**
Enhancement: https://github.com/openshift/enhancements/pull/1585
E2E tests: https://github.com/openshift/origin/pull/28719

### CODE REVIEW

**Comment by huiran0826** [comment]
LGTM

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Looking at the verify-schema, we should probably update the list tags that are missing
```
error in config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml: ListsMustHaveSSATags: crd/networks.config.openshift.io version/v1 field/^.status.serviceNetwork must set x-kubernetes-list-type
		error in config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml: ListsMustHaveSSATags: crd/networks.config.openshift.io version/v1 field/^.status.clusterNetwork must set x-kubernetes-list-type
```
I would assume both of these can just be set to atomic since the only actor on status fields should be the operator right?
```
// +listType=atomic
```

Otherwise as far as I can tell this looks good to go, you have tests (which look [green](https://sippy.dptools.openshift.org/sippy-ng/tests/4.17?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522current_runs%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25227%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522never-stable%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%257D%252C%257B%2522id%2522%253A99%252C%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522NetworkDiagnosticsConfig%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage), you have QE sign off, all generation appears to be up to date

**Comment by kyrtapz** [comment]
> Looking at the verify-schema, we should probably update the list tags that are missing
> 
> ```
> error in config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml: ListsMustHaveSSATags: crd/networks.config.openshift.io version/v1 field/^.status.serviceNetwork must set x-kubernetes-list-type
> 		error in config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml: ListsMustHaveSSATags: crd/networks.config.openshift.io version/v1 field/^.status.clusterNetwork must set x-kubernetes-list-type
> ```
> 
> I would assume both of these can just be set to atomic since the only actor on status fields should be the operator right?
> 
> ```
> // +listType=atomic
> ```
> 

Sounds good, I can look into it. Since this is an unrelated change I would like to keep it separate from this PR.

**Comment by JoelSpeed** [comment]
/lgtm
/override ci/prow/verify-crd-schema
/override ci/prow/verify

We have a follow up to fix the SSA tags, and the verify is complaining of missing E2E but we have that linked here and QE approval

**Comment by kyrtapz** [comment]
Had to rebase to resolve conflicts in the auto-generated files.
@JoelSpeed ptal

**Pull request merged**
