### PR TITLE
removed the workerlatencyprofile status from the config node CR

### PR DESCRIPTION
**Pull request by sairameshv**
Removed the workerlatencyprofile status related data structures from the config node CRD.

The status of the worker latency profile will be updated as part of the respective operator i.e KubeAPIServer operator, Kube Controller Manager Operator whenever there is a change in the confi node custom resource.

### CODE REVIEW

**Comment by sairameshv** [comment]
cc: @harche @swghosh

**Comment by harche** [comment]
Sorry, it was a [different PR](https://github.com/openshift/machine-config-operator/pull/3129#issuecomment-1117049652) I wanted to cancel hold. Adding it back until this one is reviewed by Maciej. 

/hold

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/hold cancel

**Pull request merged**
