### PR TITLE
Bug 1988308: Add feature for Insights operator pulling SCA certs

### PR DESCRIPTION
**Pull request by tremes**
This corresponds to https://github.com/openshift/enhancements/pull/683 enhancement.

### CODE REVIEW

**Comment by bparees** [comment]
why is this being filed as a "bug"?

**Comment by bparees** [comment]
> This corresponds to openshift/enhancements#683 enhancement.

this EP is not approved/merged, so what is the basis for the implementation being merged?

**Comment by bparees** [comment]
/hold

while this change in and of itself looks to be "correct", I am concerned that this PR is enabling the code that implements a feature(https://github.com/openshift/insights-operator/pull/375) that was merged:

1) post feature freeze without a feature exception granted from the OCP organization(has docs agreed to contain this? has qe? has the ocp program granted an exception?) (instead it appears the team created dummy bugs that don't even explain why the bugs were created, in order to bypass merge gates)
https://bugzilla.redhat.com/show_bug.cgi?id=1988351
https://bugzilla.redhat.com/show_bug.cgi?id=1988308

2) implementing an enhancement proposal that is not approved or merged(https://github.com/openshift/enhancements/pull/683)

3) the enhancement proposal also has numerous unresolved comment threads (that doesn't mean the implementation didn't address them, or that the comments are blockers to the implementation, but right now the state of the design is unclear)

4) And all of this is to merge something that can only be enabled by customers who accept the limitation of not being able to ever upgrade their cluster (we could just merge it in 4.10 and let customers who want to try it out pick up an early 4.10-nightly which is likely just as palatable for someone building a throwaway cluster)

If we're going to proceed with this in 4.9, we need to resolve the discussions in the EP and get docs/qe/ocp program ACKs

**Comment by mklika** [comment]
> /hold
> 
> while this change in and of itself looks to be "correct", I am concerned that this PR is enabling the code that implements a feature([openshift/insights-operator#375](https://github.com/openshift/insights-operator/pull/375)) that was merged:
> 
> 1. post feature freeze without a feature exception granted from the OCP organization(has docs agreed to contain this? has qe? has the ocp program granted an exception?) (instead it appears the team created dummy bugs that don't even explain why the bugs were created, in order to bypass merge gates)
>    https://bugzilla.redhat.com/show_bug.cgi?id=1988351
>    https://bugzilla.redhat.com/show_bug.cgi?id=1988308
> 2. implementing an enhancement proposal that is not approved or merged([Insights Operator pulling and exposing data from the OCM API enhancements#683](https://github.com/openshift/enhancements/pull/683))
> 3. the enhancement proposal also has numerous unresolved comment threads (that doesn't mean the implementation didn't address them, or that the comments are blockers to the implementation, but right now the state of the design is unclear)
> 4. And all of this is to merge something that can only be enabled by customers who accept the limitation of not being able to ever upgrade their cluster (we could just merge it in 4.10 and let customers who want to try it out pick up an early 4.10-nightly which is likely just as palatable for someone building a throwaway cluster)
> 
> If we're going to proceed with this in 4.9, we need to resolve the discussions in the EP and get docs/qe/ocp program ACKs

@sbose78 @siamaksade could you clarify this point 4 please - is there any reason to try to have this into 4.9 or 4.10 nightly would work for you as well?

**Comment by sbose78** [comment]
We would need this in 4.9 , especially because customers have been waiting on this capability. The stories on the Build API side that would help leverage this are also done.

**Comment by bparees** [comment]
> The stories on the Build API side that would help leverage this are also done.

@sbose78 i trust those build api implementations will be gated on either this same featuregate, or another techpreviewnoupgrade featuregate?  (otherwise we're shipping a GA feature that's dependent on a techpreview feature, which would be bad)

**Comment by mklika** [comment]
> > The stories on the Build API side that would help leverage this are also done.
> 
> @sbose78 i trust those build api implementations will be gated on either this same featuregate, or another techpreviewnoupgrade featuregate? (otherwise we're shipping a GA feature that's dependent on a techpreview feature, which would be bad)

@sbose78 could you follow up on this point please? Trying to resolve all the comments so we could finally merge it.

**Comment by tremes** [comment]
@bparees The impl for degrading the Insights Operator (in case of error received from the OCM API) is WIP in https://github.com/openshift/insights-operator/pull/486

**Comment by bparees** [comment]
@tremes we're getting close on dates, has the rest of the implementation landed (including the degraded logic updates)?

**Comment by tremes** [comment]
@bparees thanks for heads up. Not yet. The PR for the degraded logic is still waiting for review from our team members. I will do my best to move it forward.

**Comment by tremes** [comment]
@bparees The impl for the degraded state finally landed (see https://github.com/openshift/insights-operator/pull/486). Can you please take care of this one?

**Comment by bparees** [comment]
/lgtm

this has been discussed w/ the team providing the backing implementation and we recognize this change is landing extremely late, however their QE organization is prepared to validate it and their program team is signed off on the change.

if it causes problems (it should not, since it's disabled unless techpreview is enabled, but it could prevent us from being able to turn on techpreview for other features because of the disruption it causes when techpreview is enabled, if it has a catastrophic bug), it will be reverted and we'll try again next release.

**Pull request merged**
