### PR TITLE
Remove RegistriesConfig from builds

### PR DESCRIPTION
**Pull request by adambkaplan**
Will be replaced by RegistrySources on image.config.openshift.io

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold
Will block origin bumps atm

**Comment by adambkaplan** [comment]
Needs https://github.com/openshift/origin/pull/22038 to merge first

**Comment by bparees** [comment]
/lgtm
(still holding pending https://github.com/openshift/origin/pull/22038)

**Pull request merged**
