### PR TITLE
Generate etcd CRD

### PR DESCRIPTION
**Pull request by ironcladlou**

### CODE REVIEW

**Comment by ironcladlou** [comment]
@hexfusion @retroflexer here's part of the CRD migration

**Comment by ironcladlou** [comment]
https://github.com/openshift/cluster-etcd-operator/blob/master/manifests/0000_12_etcd-operator_01_config.crd.yaml is copied from this

**Comment by ironcladlou** [comment]
Once this merges we can update the operator tooling to use the vendored CRD

**Comment by retroflexer** [comment]
This is identical with the current file in cluster-etcd-operator:
https://github.com/openshift/cluster-etcd-operator/blob/master/manifests/0000_12_etcd-operator_01_config.crd.yaml

Looks good to me.

/lgtm

**Pull request merged**
