### PR TITLE
openshift-compatibilty-gen: move compatibility level comments to type definition

### PR DESCRIPTION
**Pull request by sanchezl**
Followup to https://github.com/openshift/api/pull/803.
Add a compatibility statement to the type comments.

### CODE REVIEW

**Comment by sanchezl** [comment]
/hold 
go/ast really sucks when it comes to editing comments. I'm going to re-write this without go/ast.

**Comment by deads2k** [comment]
excellent, the generated comments look very good.

**Comment by sanchezl** [comment]
Combined into #803

**Pull request closed without merging**
