### PR TITLE
features: rename features to FeatureGate

### PR DESCRIPTION
**Pull request by rphillips**
I was getting this error on my informer. Note FeatureList does not exist, and Feature**s**List does. We need to redo the pluralization and update the go-client.

```
I0305 14:38:13.242898   22751 reflector.go:169] Listing and watching *v1.Features from github.com/openshift/client-go/config/informers/externalversions/factory.go:101
E0305 14:38:13.244280   22751 reflector.go:134] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: Failed to list *v1.Features: no kind "FeatureList" is registered for version "config.openshift.io/v1" in scheme "github.com/openshift/client-go/c
onfig/clientset/versioned/scheme/register.go:14" 
```

Reopens: https://github.com/openshift/api/pull/234
/cc @sjenning @derekwaynecarr @deads2k

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
lets rename Feature -> FeatureSet
lets rename FeatureSet -> FeatureSetName

**Comment by derekwaynecarr** [comment]
hmm, naming is hard, wondering if *Set will confuse with replica set or statefulset

**Comment by derekwaynecarr** [comment]
how about Feature -> FeatureGate
and FeatureSet stays put.

**Comment by sjenning** [comment]
fyi PRs that rename types will not pass verify-client-go

**Comment by rphillips** [comment]
@sjenning @derekwaynecarr pushed the rename to this PR

**Comment by derekwaynecarr** [comment]
force merging.

**Comment by adambkaplan** [comment]
@derekwaynecarr this PR blocks bumps on origin:
```
# github.com/openshift/origin/pkg/admission/customresourcevalidation/features
pkg/admission/customresourcevalidation/features/validate_features.go:34:46: undefined: "github.com/openshift/origin/vendor/github.com/openshift/api/config/v1".Features
pkg/admission/customresourcevalidation/features/validate_features.go:41:25: undefined: "github.com/openshift/origin/vendor/github.com/openshift/api/config/v1".Features
pkg/admission/customresourcevalidation/features/validate_features.go:56:37: undefined: "github.com/openshift/origin/vendor/github.com/openshift/api/config/v1".FeaturesSpec
pkg/admission/customresourcevalidation/features/validate_features.go:67:46: undefined: "github.com/openshift/origin/vendor/github.com/openshift/api/config/v1".FeaturesSpec
```

**Comment by sjenning** [comment]
@adambkaplan sorry for letting this sit around.  https://github.com/openshift/origin/pull/22389 should fix.

**Pull request merged**
