### PR TITLE
feat(imageregistry): Support IBMCOS storage type

### PR DESCRIPTION
**Pull request by hasueki**
This adds new type definitions for IBM Cloud's storage backend for the image registry.
Reference: https://github.com/openshift/cluster-image-registry-operator/pull/698

### CODE REVIEW

**Comment by fabianofranz** [comment]
@dmage mind taking a look?

**Comment by dmage** [comment]
@hasueki will UPI flow be supported? Which parameters will be need to set if the bucket is created by a customer?

/assign @bparees

**Comment by hasueki** [comment]
@dmage Yes, in an UPI scenario the user will be able to bring their own IBM COS service instance and bucket. In this case, the user will set bucket, location, resourceGroupName, resourceKeyCRN, serviceInstanceCRN. It is also possible to bring just a service instance (no bucket, no resource key), then the operator will create the missing resources and populate the CR spec.

**Comment by bparees** [comment]
/approve

is the work to consume this value complete?  Normally we try to avoid merging api updates if the implementation work isn't done, so we don't accidentally ship a new api that isn't actually backed by an implementation.

**Comment by hasueki** [comment]
Thank you for the approval @bparees.

I have a draft PR created for the implementation here, https://github.com/openshift/cluster-image-registry-operator/pull/698. I am just waiting on this `openshift/api` PR to land so I can update the go deps, https://github.com/hasueki/cluster-image-registry-operator/blob/0aaa7c01ddf39a28420036522ff8e1e06e3f6a7c/go.mod#L58.

**Pull request merged**
