### PR TITLE
Bump controller-gen to v0.9.2.

### PR DESCRIPTION
**Pull request by benluddy**
With the latest controller-gen, leading and trailing whitespace is
stripped from the generated description text (https://github.com/kubernetes-sigs/controller-tools/pull/517), and topology
markers (e.g. +structType, +mapType) are now being recognized when
applied to types as well as fields (https://github.com/kubernetes-sigs/controller-tools/pull/692).

### CODE REVIEW

**Comment by benluddy** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_api/1203/pull-ci-openshift-api-master-verify/1529842193689219072#1:build-log.txt%3A109

https://github.com/openshift/build-machinery-go/pull/67

/retest-required

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label qe-approved
/label docs-approved
/label px-approved

**Comment by benluddy** [comment]
Need to understand the impact of this topology marker fix first (https://kubernetes.io/docs/reference/using-api/server-side-apply/#compatibility-across-topology-changes).

/hold

**Comment by JoelSpeed** [comment]
@benluddy I was looking into making this bump as a part of some other changes I'm making, did you work out what the impact is likely to be of adding these markers? 

IIUC all lists are atomic by default, so anyone using SSA who would observe a map type can't have been using it yet right? The entire list will currently have a single owner but may then in the future have multiple owners. That said, if the list is currently atomic, none of our consumers can have any logic assuming it is a map or otherwise so will end up preserving the entire list right now

Perhaps if we can enumerate the places this has changed we can determine how many consumers there are and where it is safe and where it is not safe to make the change

**Comment by JoelSpeed** [comment]
I think this is ok. The markers only affect clients using SSA. We don't currently have generated SSA clients so it wouldn't be easy for any consumers of these types to be using SSA yet anyway. Add to that that the default list type behaviour is atomic, this _shouldn't_ be a breaking change for any of these instances.

/lgtm

**Comment by deads2k** [comment]
we need to sweep all slices before 4.12.

/approve
/assign @JoelSpeed

**Comment by JoelSpeed** [comment]
/lgtm

We need the updated generator so that we can continue with the introduction of tech preview fields for openshift APIs

**Review by Miciah — COMMENTED** [review]
/lgtm
/approve
/hold
for other reviewers.

**Comment by Miciah** [comment]
Sorry, wrong PR.  
/hold cancel

**Pull request merged**
