### PR TITLE
CORS-2979: Include AWS Alt Infra in Tech Preview

### PR DESCRIPTION
**Pull request by patrickdillon**
Enables AWS SDK alternate infrastructure in tech preview feature set.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Is the alt infra code merged? If so, can we prove that this isn't going to break TP by running some TP jobs on a bump of cluster config operator including this change

**Comment by r4f4** [comment]
> Is the alt infra code merged?
Yes, it's in `master` now.

**Comment by JoelSpeed** [comment]
Can you link the PRs relating to this feature and in particular where the feature gate is blocking this? I had been keeping an eye on this but hadn't seen where it went in that this switch is to TP is going to effect

**Comment by r4f4** [comment]
SDK provision PR: https://github.com/openshift/installer/pull/7676
Enabling SDK provision with feature gate (still open): https://github.com/openshift/installer/pull/7715

**Comment by JoelSpeed** [comment]
> SDK provision PR: [openshift/installer#7676](https://github.com/openshift/installer/pull/7676) Enabling SDK provision with feature gate (still open): [openshift/installer#7715](https://github.com/openshift/installer/pull/7715)

Ok, so the intention is to get this PR in to promote into tech preview, then merge 7715 to actually activate the feature in the TP jobs?

**Comment by r4f4** [comment]
> > SDK provision PR: [openshift/installer#7676](https://github.com/openshift/installer/pull/7676) Enabling SDK provision with feature gate (still open): [openshift/installer#7715](https://github.com/openshift/installer/pull/7715)
> 
> Ok, so the intention is to get this PR in to promote into tech preview, then merge 7715 to actually activate the feature in the TP jobs?

I think so but I'll let @patrickdillon confirm or deny.

**Comment by patrickdillon** [comment]
Apologies for not providing more context. 

openshift/installer#7676 merged the aws sdk install implementation to the installer, but it is only exposed for usage in the new `installer-altinfra` image, which could be used by ROSA or any users who manually extract that image.

openshift/installer#7715 uses a feature gate to expose the sdk install in the `installer` image, which is normal installer image. openshift/installer#7715 should merge regardless of this PR, but this API pr will have no effect until 7715 merges.

The intent of this PR is to get better test signal on the use case of making the sdk install default for all users (rather than having terraform installs by default and sdk available in a separate image).

**Comment by JoelSpeed** [comment]
/lgtm

We need to make sure config operator is also bumped to include this before 7715 merges.

And then, when you merge 7715, please run a payload aggregate for a techpreview aws job to make sure things are working as expected

**Pull request merged**
